/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 04-Oct-2013.
 */
package tr.gov.tubitak.uekae.esya.asn.esya;

import com.objsys.asn1j.runtime.*;

public class ESYAServiceConfigType extends Asn1Type {
   
	private static final long serialVersionUID = 55;
	static {
		setKey(_esyaRtkey._rtkey);
	}

   public ESYAServiceConfigType_configType configType = null;

   public ESYAServiceConfigType () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public ESYAServiceConfigType (
      ESYAServiceConfigType_configType configType_
   ) {
      super();
      configType = configType_;
   }

   public void init () {
      configType = null;
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode configType

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 10, elemLen, false)) {
         int tval = buffer.decodeEnumValue (ESYAServiceConfigType_configType.TAG, true, elemLen.value);
         configType = ESYAServiceConfigType_configType.valueOf (tval);
      }
      else throw new Asn1MissingRequiredException (buffer, "configType");

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 10))
            throw new Asn1SeqOrderException ();

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode configType

      if (configType != null) {
         len = configType.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("configType");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (configType != null) configType.print (_out, "configType", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }
}
