// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.6.4, Date: 10-Oct-2013.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace tr.gov.tubitak.uekae.esya.asn.crmf {

   using GeneralName = tr.gov.tubitak.uekae.esya.asn.x509.GeneralName;

   public class POPOSigningKeyInput_authInfo : Asn1Choice {
      // Choice element identifier constants
      public const byte _PUBLICKEYMAC = 1;
      public const byte _SENDER = 2;

      static POPOSigningKeyInput_authInfo ()
      {
         Asn1Type.SetKey2 (_crmfValues._rtkey);
      }

      public POPOSigningKeyInput_authInfo () : base()
      {
      }

      public POPOSigningKeyInput_authInfo (byte choiceId_, Asn1Type element_) : base()
      {
         SetElement (choiceId_, element_);
      }

      public override string ElemName {
         get {
            switch (choiceID) {
            case _PUBLICKEYMAC: return "publicKeyMAC";
            case _SENDER: return "sender";
            default: return "UNDEFINED";
            }
         }
      }

      public void Set_publicKeyMAC (PKMACValue value) {
         SetElement (_PUBLICKEYMAC, value);
      }

      public void Set_sender (GeneralName value) {
         SetElement (_SENDER, value);
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = implicitLength;

         // decode CHOICE

         Asn1Tag tag = new Asn1Tag ();
         buffer.Mark ();
         int len = buffer.DecodeTagAndLength (tag);

         if (tag.Equals (Asn1Tag.UNIV, Asn1Tag.CONS, 16))
         {
            buffer.Reset();
            PKMACValue publicKeyMAC;
            publicKeyMAC = new PKMACValue();
            publicKeyMAC.Decode (buffer, true, len);
            SetElement (_PUBLICKEYMAC, publicKeyMAC);
         }
         else if (tag.Equals (Asn1Tag.CTXT, Asn1Tag.CONS, 0))
         {
            GeneralName sender;
            sender = new GeneralName();
            sender.Decode (buffer, false, len);
            SetElement (_SENDER, sender);
         }
         else {
            throw new Asn1InvalidChoiceOptionException (buffer, tag);
         }
      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = 0, len;
         switch (choiceID) {
         // encode publicKeyMAC
         case _PUBLICKEYMAC:
            PKMACValue publicKeyMAC = (PKMACValue) GetElement();
            len = publicKeyMAC.Encode (buffer, true);
            _aal += len;
            break;

         // encode sender
         case _SENDER:
            GeneralName sender = (GeneralName) GetElement();
            len = sender.Encode (buffer, false);
            len += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
            _aal += len;
            break;

         default:
            throw new Asn1InvalidChoiceOptionException();
         }

         return _aal;
      }

      public override void Print (System.IO.TextWriter _out, 
                                  string _varName, int _level)
      {
         Indent (_out, _level);
         _out.WriteLine (_varName + " {");
         if (element != null) {
            element.Print (_out, ElemName, _level+1);
         }
         Indent (_out, _level);
         _out.WriteLine ("}");
      }
   }
}
