package tr.gov.tubitak.uekae.esya.api.common.bundle;

import java.util.ListResourceBundle;



public class GenelBundle_en extends ListResourceBundle
{
protected static Object[][] mGenelContents =
{
{GenelDil.ACIKLAMA,"Explanation"},
{GenelDil.ACIKLAMA_GIRINIZ,"Please fill in the explanation field"},
{GenelDil.AD,"Name"},
{GenelDil.ADRES,"Address"},
{GenelDil.AKTIF,"Active"},
{GenelDil.AKTIF_YAP,"Activate"},
{GenelDil.ALGORITMA,"Algorithm"},
{GenelDil.ANAHTAR,"Key"},
{GenelDil.ANAHTAR_ADI,"Key Name"},
{GenelDil.ANAHTAR_BOYU,"Key Length"},
{GenelDil.Anahtar_Bilgileri,"Key Information"},
{GenelDil.ARA,"Search"},
{GenelDil.ASKIDA,"On Hold"},
{GenelDil.BASARILI,"Successful"},
{GenelDil.BASARISIZ,"Unsuccessful"},
{GenelDil.IL,"Province"},
{GenelDil.ILCE,"County"},
{GenelDil.HEPSI,"All"},
{GenelDil.HAKKINDA,"About"},
{GenelDil.DOSYA_KAYDET,"Save to file"},
{GenelDil.DOSYA_OKUNAMADI,"File could not be read"},
{GenelDil.DOSYA_SECILMEDI,"Select a file"},
{GenelDil.DOSYA_YOLU,"File Path"},
{GenelDil.EPOSTA,"Email"},
{GenelDil.EVET,"Yes"},
{GenelDil.GECERLI,"Valid"},
{GenelDil.KAYIT_MAKAMI,"Registration Authority"},
{GenelDil.ESYA_KONTROL_MERKEZI,"ESYA Administration Center"},
{GenelDil.ESYA_KONTROL_MERKEZI_B,"ESYA ADMINISTRATION CENTER"},
{GenelDil.KONTROL_MERKEZI,"Administration Center"},
{GenelDil.IMZALA,"Sign"},
{GenelDil.SIFRELE,"Encrypt"},
{GenelDil._0_1_ARALIGINDA_OLMALI,"The numbers should be between {0}-{1}"},
{GenelDil._0_ALGORITMASIYLA_SIFRECOZME_YAPILAMIYOR,"Could not decrypt with algorithm {0}"},
{GenelDil._0_ISLEMI_ICIN_YETERLI_YETKINIZ_YOK,"Not authorized for the operation \"{0}\""},
{GenelDil.AKTARIM_BILGILERI,"Importing Info"},
{GenelDil.ANA_DIZIN,"Home Folder"},
{GenelDil.ANAH_URETILEMEDI,"Error occurred in key generation!"},
{GenelDil.ANAHTAR_HATALI,"Symmetric encryption key can not be used!"},
{GenelDil.ANAHTAR_SERTIFIKA_BETIGI,"Key/Certificate Script"},
{GenelDil.ANAHTAR_URETILIYOR,"Creating Key(s)"},
{GenelDil.ANAHTAR_URETME,"Key Generation"},
{GenelDil.ARAMA,"Search"},
{GenelDil.ARAMA_FILTRESI_HATALI,"Error in search filter"},
{GenelDil.ARAMADA_BILINMEYEN_HATA,"Unknown error in search! Make sure the search point is correct!"},
{GenelDil.ARANAN_TKA_0_BULUNAMADI,"Searched DN \"{0}\" not found!"},
{GenelDil.ARGUMAN_BILINMIYOR,"Given argument is not known!"},
{GenelDil.ASKIYAAL,"Hold"},
{GenelDil.ASN1_DECODE_HATASI,"Error occurred while decoding the Asn1 structure!"},
{GenelDil.ASN1_ENCODE_HATASI,"Error occurred while encoding the Asn1 structure!"},
{GenelDil.ATTRIBUTE_BILINMIYOR,"Unknown attribute!"},
{GenelDil.ATTRIBUTEA_VERILMEK_ISTENEN_DEGER_HATALI,"Conflict between the value to be given to the attribute and schema definition of the attribute!"},
{GenelDil.AYARLAR,"Settings"},
{GenelDil.BAKILACAK_YER,"Look In"},
{GenelDil.BASLIK_ANAHTAR_PARCALAMA,"Key Division"},
{GenelDil.BASLIK_HAKKINDA,"About"},
{GenelDil.BASLIK_SIFRENIZ,"Password"},
{GenelDil.BASLIK_SLOTLISTESI,"Slot List Selection"},
{GenelDil.BELGE,"Document"},
{GenelDil.BELGE_NO,"Document No"},
{GenelDil.BELGE_YOLU,"Document Path"},
{GenelDil.BILGI,"Information"},
{GenelDil.BIRDEN_FAZLA_EMAIL,"More than one result is found though e-mail search! Returning only one!"},
{GenelDil.BLOKUZUNLUGU_0_ALGI_1_DESTEKLEMIYOR,"Error in block length! {0} algorithm does not support {1} block length!"},
{GenelDil.CA_CERT_ERROR,"Error occurred while getting CA certificate!"},
{GenelDil.CALISTIRILMAMASI_GEREKEN_FONKSIYON,"A function which should not be called is called."},
{GenelDil.CARD_NO_CONFLICT,"Card serial numbers read from card and database are not same!"},
{GenelDil.CERT_HATALI,"Error in given certificate!"},
{GenelDil.CKR_DEVICE_MEMORY_M,"Error in smart card memory"},
{GenelDil.CKR_PIN_INCORRECT_M,"Password is not correct"},
{GenelDil.CKR_PIN_INVALID_M,"Password is not valid"},
{GenelDil.CKR_PIN_LOCKED_M,"Smart card PIN is locked."},
{GenelDil.CKR_TOKEN_NOT_PRESENT_M,"Insert your smart card (Token not present)"},
{GenelDil.CKR_USER_ALREADY_LOGGED_IN_M,"User already logged in"},
{GenelDil.COMMONNAME,"CommonName"},
{GenelDil.COUNTRYCITIZENSHIP,"CountryCitizenship"},
{GenelDil.COUNTRYNAME,"Country Name"},
{GenelDil.COUNTRYRESIDENCE,"Country Residence"},
{GenelDil.CRLSIGN,"CRL Signing"},
{GenelDil.DATAENCIPHERMENT,"Data encipherement"},
{GenelDil.DATEOFBIRTH,"Date Of Birth"},
{GenelDil.DECIPHERONLY,"Decipher Only"},
{GenelDil.DEFAULT_KURUM,"CA owner Default Institution"},
{GenelDil.DEGISME_TARIHI,"Date Of Change"},
{GenelDil.DENEME_YAZISI,"Sample Text"},
{GenelDil.DESTEKLENEN_MECHANIZMA_YOK,"Supported PKCS#11 mechanism is not found!"},
{GenelDil.DETAYLAR,"Details"},
{GenelDil.DIGITALSIGNATURE,"Digital Signature"},
{GenelDil.DIL,"Language"},
{GenelDil.DIZIN_ADI,"Directory Name"},
{GenelDil.DIZINSIF_VEYA_KULLADI_HATALI,"Wrong LDAP Directory user name or password!"},
{GenelDil.DLL_LOAD_EDILEMEDI,"Dll could not be loaded"},
{GenelDil.DNSNAME,"DNS Name"},
{GenelDil.DOMAIN_COMPONENT,"Domain Component"},
{GenelDil.DOSYA_ADI,"File Name"},
{GenelDil.DOSYA_GORUNTULE,"Show File"},
{GenelDil.DOSYA_SEC,"Select File"},
{GenelDil.DOSYA_SECINIZ,"Please Select a File"},
{GenelDil.DOSYA_TURU,"File Type"},
{GenelDil.DUGME_AC,"Open"},
{GenelDil.DUGME_BITIR,"Finish"},
{GenelDil.DUGME_DIZIN_DNEKLE,"Add DN"},
{GenelDil.DUGME_DIZINDENSEC,"Select from Directory"},
{GenelDil.DUGME_DN_OLUSTUR,"Create DN"},
{GenelDil.DUGME_EKLE,"Add"},
{GenelDil.DUGME_ETKINLESTIR,"Activate"},
{GenelDil.DUGME_EVET,"Yes"},
{GenelDil.DUGME_GUNCELLE,"Update"},
{GenelDil.DUGME_HAYIR,"No"},
{GenelDil.DUGME_INIYAZ,"Write INI"},
{GenelDil.DUGME_KAYDET,"Save"},
{GenelDil.DUGME_KOPYA_CIKAR,"Make Copy"},
{GenelDil.DUGME_ONAYLA,"Approve"},
{GenelDil.DUGME_PKCS10ISTEGI,"Make PKCS10 Request"},
{GenelDil.DUGME_SERTIFIKAAL,"Request Certificate"},
{GenelDil.DUGME_SERVISI_BASLAT,"Start Service"},
{GenelDil.DUGME_SERVISI_DURDUR,"Stop Service"},
{GenelDil.DUGME_SIL,"Delete"},
{GenelDil.DUGME_SILYAYINLA,"Publish New CRL"},
{GenelDil.DUGME_TAMAM,"OK"},
{GenelDil.DUGME_TARIH_SEC,"Select Date"},
{GenelDil.DUGME_TEMIZLE,"Clear"},
{GenelDil.DUGME_TUMUNUKALDIR,"Unselect All"},
{GenelDil.DUGME_TUMUNUSEC,"Select All"},
{GenelDil.DUGME_VAZGEC,"Cancel"},
{GenelDil.DUGME_VT_TEMIZLE,"Clean DB"},
{GenelDil.DUGME_YENILE,"Renew"},
{GenelDil.DURUM,"Status"},
{GenelDil.ECDSAANAHTARBOYU_0_BILINMIYOR,"The parameters for ECDSA key length {0} are not known."},
{GenelDil.EKLENECEK_NOKTA_BULUNAMADI,"The point to add new entry could not be found!"},
{GenelDil.EKLERKEN_AYNI_TKA,"There is an entry with the same DN or e-mail!"},
{GenelDil.EKLERKEN_BILINMEYEN_HATA,"Unknown error while adding new entry!"},
{GenelDil.EKLERKEN_EKSIK_ATTRIBUTE,"Missing attribute while adding new entry!"},
{GenelDil.ENCIPHERONLY,"Encipher Only"},
{GenelDil.ENCODEDECODE_HATASI,"Encode and/or decode error!"},
{GenelDil.GENDER,"Gender"},
{GenelDil.GIVENNAME,"Given Name"},
{GenelDil.GETATTRIBUTELIST_YANLIS_ARGUMANLA_CAGRILDI,"getAttributeList function is called with a wrong argument!"},
{GenelDil.GUNCELLEME,"Update"},
{GenelDil.GUNCELLEME_IS_HATALI,"Update is not suitable for this operation type. Operation type ADD_VALUE, will be used instead!"},
{GenelDil.GUNCELLEMEDE_HATA,"Update error!"},
{GenelDil.GUNCELLENECEK_TKA_0_BULUNAMADI,"DN \"{0}\" to be updated is not found!"},
{GenelDil.GUNCELLERKEN_CIKACAK_DEGER_BULUNAMADI,"The value to be deleted could not be found while updating!"},
{GenelDil.GUNCELLERKEN_DEGER_EKLENEMIYOR,"The value to be added cannot be added while updating!"},
{GenelDil.HATA,"Error"},
{GenelDil.HATALI,"Absent or Erroneous"},
{GenelDil.HATASIZ,"Exists with No Error"},
{GenelDil.HAYIR,"No"},
{GenelDil.HIC_GELMEMELI,"Should not come here"},
{GenelDil.HSM_INI_0_OKUNAMADI,"'{0}' from HSM setting file could not be read"},
{GenelDil.HSM_INIDEN_DEGERLER_OKUNAMADI,"The values from HSM setting file could not be read!"},
{GenelDil.HSME_ULASILAMADI,"HSM device could not be reached to !"},
{GenelDil.ILKLENDIRME_ANAHTAR_GRUP_NO,"Initialization Key Group No"},
{GenelDil.ILKLENDIRME_BETIGI,"Initialization Script"},
{GenelDil.ILKLENDIRME_KART_TIPI,"Initialization Card Type"},
{GenelDil.ILKLENDIRME_SABLON_ADI,"Initialization Template Name"},
{GenelDil.ILKLENDIRME_SABLON_MAJOR_SURUMU,"Initialization Template Major Version"},
{GenelDil.ILKLENDIRME_SABLON_MINOR_SURUMU,"Initialization Template Minor Version"},
{GenelDil.IMZA_ANAHTAR_ALGORITMA_UYUMSUZLUGU, "Incompatible key type and signing algorithm"},
{GenelDil.IMZA_DOGRULAMA_HATASI,"Error in signature verification!"},
{GenelDil.IMZALAMA,"Signing"},
{GenelDil.IMZALAMA_HATASI,"Error in signing process!"},
{GenelDil.IMZALAMADA_HATA,"Error in signing process!"},
{GenelDil.IMZALG_0_BILINMIYOR,"Signing algorithm {0} is not known!"},
{GenelDil.IMZALG_0_ICIN_1_BOYUNDAANAH_OLMAZ,"For Signing algorithm {0}, {1} key length is not supported!"},
{GenelDil.IMZALG_0_ICIN_OZET_1_BILINMIYOR,"For Signing algorithm {0}, hash algorithm {1} is not known!"},
{GenelDil.IMZALG_YOK,"There is not Signing algorithm!"},
{GenelDil.IMZALGOZET_YOK,"There is not hash algorithm!"},
{GenelDil.IMZANAH_HATALI,"Error in signing key!"},
{GenelDil.IMZANAHBOY_YOK,"There is no Signing key length!"},
{GenelDil.IMZSERTSERINO_HATALI,"Error in the signing certificate serial number of the authority!"},
{GenelDil.INIT_EDILMEMIS,"Not initialized!"},
{GenelDil.INIT_EDILMIS,"Already initialized!"},
{GenelDil.INVALID_CERT,"Certificate could not be validated!"},
{GenelDil.IP,"IP"},
{GenelDil.IP_PORTTA_DIZIN_BULUNAMADI,"Cannot connect to LDAP through the given IP and port!"},
{GenelDil.ISLEM_TIPI,"Operation Type"},
{GenelDil.KART_TIPI,"Card Type"},
{GenelDil.KART_TIPI_VE_PAROLA,"Card Type and Password"},
{GenelDil.KART_TIPLERI_OKUNAMADI,"Card types could not be read"},
{GenelDil.KARTA_LOGIN_OLUNAMADI,"Could not login to card!"},
{GenelDil.KARTA_ULASILAMADI,"Could not reach to card!"},
{GenelDil.KARTINIZ_TAKILIMI,"Make sure your card is inserted!"},
{GenelDil.KARTTA_0_ANAHTARI_VAR,"There is key {0} in the card!"},
{GenelDil.KARTTA_0_ANAHTARI_YOK,"Key {0} is not found in the card!"},
{GenelDil.KARTTA_HATA_0,"Error in smart card! {0}"},
{GenelDil.KARTTA_SIFRECOZME_HATA,"Decryption could not be done in the card!"},
{GenelDil.KARTTA_SIFRELEME_YAPILAMADI,"Encryption could not be done in the card!"},
{GenelDil.KARTTAN_BILGILER_ALINAMADI,"Information could not be taken from the card!"},
{GenelDil.KAYDEDILECEK_YER,"Save In"},
{GenelDil.KEYAGREEMENT,"Key Agreement"},
{GenelDil.KEYCERTSIGN,"Key Cert Sign"},
{GenelDil.KEYENCIPHERMENT,"Key Encipherment"},
{GenelDil.KIMLIK,"Identity"},
{GenelDil.KIMLIKNO,"Identity number"},
{GenelDil.KIRMIZI,"Red"},
{GenelDil.KRIPTO_GENEL_HATA,"General error in crypto processes!"},
{GenelDil.KRIPTOMOD_ANAH_BUTUN,"Complete Key"},
{GenelDil.KRIPTOMOD_ANAH_PARCALI_MOFN,"Shared Key (MofN)"},
{GenelDil.KRIPTOMOD_HSM,"HSM (Hardware Security Module)"},
{GenelDil.KRITIKLOGOLUSTURULAMADI,"Critic log could not be created"},
{GenelDil.KULLANIM_BILINMIYOR,"Symmetric algorithm to be used for given purpose is not known"},
{GenelDil.LABEL_KARTPAROLASINIGIRINIZ,"Enter card password:"},
{GenelDil.LABEL_SADECETAKILISLOTLAR,"Only inserted slots"},
{GenelDil.LABEL_SLOTLISTESI,"Slot List"},
{GenelDil.LDAP_TIP_HATALI,"Wrong LDAP type!"},
{GenelDil.LDAPA_BAGLANILAMADI,"Could not connect to LDAP!"},
{GenelDil.LDAPA_BAGLANTI_BULUNAMADI,"Could not find LDAP connection!"},
{GenelDil.LISTE_GIRILIRKEN_HATA,"Error while listing"},
{GenelDil.LISTELE,"List"},
{GenelDil.LOCALITYNAME,"Locality Name"},
{GenelDil.LOG,"Log"},
{GenelDil.LOG_METNI,"Log Text"},
{GenelDil.LOG_MODULU,"Log Modul"},
{GenelDil.LOG_OLAYTIPI,"Log Event Type"},
{GenelDil.LOG_SONUCU,"Log Result"},
{GenelDil.LOG_TARIHI,"Log Date"},
{GenelDil.LUTFEN_DOLDURUNUZ,"Please fill in "},
{GenelDil.MAVI,"Blue"},
{GenelDil.MESAJ_AKILLIKARTBILGILERIALINAMADI,"Smart card data could not be taken!"},
{GenelDil.MESAJ_ANAHTAR_PARCALAR_BOLUNUYOR,"The key is being divided..."},
{GenelDil.MESAJ_BILINMEYENHATA,"Unknown error in license check!"},
{GenelDil.MESAJ_BOSALANKALMASIN,"Fill in all the blanks!"},
{GenelDil.MESAJ_DOSYABULUNAMADI,"Licence file could not be found!"},
{GenelDil.MESAJ_ENAZ_0_BUYUKHARFOLMALI,"The password must contain at least {0} uppercase letter(s)."},
{GenelDil.MESAJ_ENAZ_0_KARAKTEROLMALI,"The password length must be at least {0}."},
{GenelDil.MESAJ_ENAZ_0_KUCUKHARFOLMALI,"The password must contain at least {0} lowercase letter(s)."},
{GenelDil.MESAJ_ENAZ_0_OZELKARAKTEROLMALI,"The password must contain at least {0} special character(s).  {1}"},
{GenelDil.MESAJ_ENAZ_0_RAKAMOLMALI,"The password must contain at least {0} digit(s)."},
{GenelDil.MESAJ_ENCOK_0_KARAKTEROLMALI,"The password length must be at most {0}."},
{GenelDil.MESAJ_ESNEKZDYOK, "Permissive timestamp field could not be found in the licence. Please renew the licence file!"},
{GenelDil.MESAJ_HOSTADIBILINMIYOR,"Unknown host name!"},
{GenelDil.MESAJ_HOSTHATALI,"The computer name does not match with data in the licence."},
{GenelDil.MESAJ_IMPL,"Application           :"},
{GenelDil.MESAJ_IMPLURETICI,"Application producer :"},
{GenelDil.MESAJ_IMPLVERSION,"Application Version  :"},
{GenelDil.MESAJ_IPHATALI,"The IP number does not match with data in the licence."},
{GenelDil.MESAJ_LISANSBASLAMAMIS,"Your licence period has not started yet."},
{GenelDil.MESAJ_LISANSBITMIS,"Your licence period is over."},
{GenelDil.MESAJ_SPEC,"Spec           :"},
{GenelDil.MESAJ_SPECURETICI,"Spec producer :"},
{GenelDil.MESAJ_SPECVERSION,"Spec Version  :"},
{GenelDil.MOBIL_IMZA_KULLANICI_IPTALI, "Mobile signature request was cancelled by user."},
{GenelDil.MOBIL_COKLU_IMZA_KULLANICI_IPTALI, "Mobile signature request #{0} was cancelled by user."},
{GenelDil.MOBIL_IMZA_ZAMAN_ASIMI, "Mobile signature request timed out."},
{GenelDil.MOD_0_BILINMIYOR,"Unknown Mode {0}!"},
{GenelDil.MOD_SECILMEMIS,"Mode has not been selected!"},
{GenelDil.MOD_SECILMIS,"Mode has been selected!"},
{GenelDil.MOFN_KART_OKUNMUS,"The key part in this card has been already read. Try another card!"},
{GenelDil.NESNE_OKUNAMADI,"Object could not be read"},
{GenelDil.NO,"No"},
{GenelDil.NO_DBCONNECTION,"Database connection error!"},
{GenelDil.NO_SUCH_CARD_NO,"No card number of this authority is found in the database!"},
{GenelDil.NO_SUCH_USER,"No user having this authority name!"},
{GenelDil.NONREPUDIATION,"Non Repudation"},
{GenelDil.NUMARA,"Number"},
{GenelDil.OID_0_BILINMIYOR,"Algorithm OID {0} is not known!"},
{GenelDil.OID_ADI,"OID Name"},
{GenelDil.OID_DEGERI,"OID Value"},
{GenelDil.ONCA_0_FONKSIYONU_CAGRILMALI,"First init_SMKurulumIcin(...) function must be called!"},
{GenelDil.ONCEKI,"Previous"},
{GenelDil.ONIZLEME,"Preview"},
{GenelDil.ORGANIZATIONAL_UNIT_NAME,"Organizational Unit Name"},
{GenelDil.ORGANIZATION_NAME,"Organization Name"},
{GenelDil.OZETALG_0_BILINMIYOR,"Hash algorithm {0} is not known!"},
{GenelDil.PADDING_BILINMIYOR,"Given padding is not known!"},
{GenelDil.PADDING_HATALI,"Wrong padding bytes!"},
{GenelDil.PARAMETRELER,"Parameters"},
{GenelDil.PAROLA,"Password"},
{GenelDil.PAROLA_HATALI,"Incorrect password!"},
{GenelDil.PAROLA_SURESI_DOLMUS,"Password period is over!"},
{GenelDil.PASIF,"Pasive"},
{GenelDil.PASIF_YAP,"Make Pasive"},
{GenelDil.PFX_UZANTISI,"PFX Extension"},
{GenelDil.PRIVBYTES_HATALI,"Error in PrivateKey byte array!"},
{GenelDil.PRIVKEY_OLUSTURULAMADI,"Data could not be retrieved for private key generation!"},
{GenelDil.PUBBYTES_HATALI,"Error in PublicKey byte!"},
{GenelDil.PUBKEY_YOK,"No Public key!"},
{GenelDil.PUBLICKEY_OKUNAMADI,"Public key could not be read from the card!"},
{GenelDil.RASTGELE,"Random"},
{GenelDil.RB_HATA_44105,"No certificate serial number of this authority in the database!"},
{GenelDil.RB_HATA_44106,"Certificate serial numbers read from card and database are not same!"},
{GenelDil.ROLU_KAYITCI_OLAN_IMZ_SERT_BULUNAMADI,"Signing certificate which has registrar role cannot be found or more than one is found!"},
{GenelDil.SCHEMA_HATASI,"Schema error in LDAP!"},
{GenelDil.SEARCH_KONTROL_HATALI,"Error in given search controls!"},
{GenelDil.SERTIFIKA_ALMA,"Certification"},
{GenelDil.SERTIFIKA_IPTAL_TALEBI,"Certification Revoke Request"},
{GenelDil.SERTIFIKA_IPTALASKI,"Certificate Revoke/Hold"},
{GenelDil.SERTIFIKA_ISLEMLERI,"Certificate Operations"},
{GenelDil.SERTIFIKA_TALEP,"Certification Request"},
{GenelDil.SIFALG_0_BILINMIYOR,"Encryption algorithm {0} is not known!"},
{GenelDil.SIFALG_0_ICIN_1_BOYUNDAANAH_OLMAZ,"For encryption algorithm {0}, {1} key length is not supported!"},
{GenelDil.SIFALG_YOK,"No encryption key!"},
{GenelDil.SIFANAH_HATALI,"Error in encryption key!"},
{GenelDil.SIFANAHBOY_YOK,"No encryption key length!"},
{GenelDil.SIFRE_COZME_HATASI,"Error while decrypting:"},
{GenelDil.SIFRELEME_HATASI,"Error while encrypting:"},
{GenelDil.SIFSERTSERINO_OKUMA_HATASI,"Error in reading encryption certficate serial number of the authority!"},
{GenelDil.SILERKEN_BILINMEYEN_HATA,"Unknown error while deleting DN from LDAP!"},
{GenelDil.SILINECEK_TKA_HATALI,"Incorrect DN to be deleted!"},
{GenelDil.SILINECEK_TKADA_ENTRY_VAR,"There are entries in DN to be deleted!"},
{GenelDil.SIMALG_BILINMIYOR,"Unknown symmetric algorithm!"},
{GenelDil.SIMALG_OID_BILINMIYOR,"Unknown OID for the symmetric algorithm"},
{GenelDil.SIMMOD_BILINMIYOR,"Unknown symmetric mode!"},
{GenelDil.SONRAKI,"Next"},
{GenelDil.SORU,"Question"},
{GenelDil.SOYAD,"Surname"},
{GenelDil.STATE_OR_PROVINCE_NAME,"StateOrProvinceName"},
{GenelDil.SUNIMZOBJE_DOGRU_INIT_EDILMEMIS,"SUN signing object has not been initialized correctly!"},
{GenelDil.TC_KIMLIK_NO,"TC Identity Number"},
{GenelDil.TIP,"Type"},
{GenelDil.TOOLTIP_ISLEMDEVAMEDIYOR,"Your request is being processed."},
{GenelDil.TUM_DOSYALAR,"All Files"},
{GenelDil.TUM_TABLOYU_IMZALA,"Sign Whole Table"},
{GenelDil.UPN,"UPN"},
{GenelDil.UST_DIZIN,"Up Folder"},
{GenelDil.UYARI,"Warning"},
{GenelDil.VARSAYILAN,"Default"},
{GenelDil.VERILEN_ARAMA_NOKTASI_NULL_VEYA_BOS,"Given search point is null or empty!"},
{GenelDil.VT_ERROR,"Database error!"},
{GenelDil.X400NAME,"X400Name"},
{GenelDil.YAPILANDIRMADA_EKLENDI,"Added during system configuration"},
{GenelDil.YENI_DIZIN_OLUSTUR,"Create New Folder"},
{GenelDil.YESIL,"Green"},
{GenelDil.YON_SAY_FARKLI,"Administrator number is not same with the one given earlier!"},
{GenelDil.YONETICI_EPOSTA,"Administrator Email"},
{GenelDil.YONSAY_MIN_0_OLMALI,"Administrator number must be at least {0}!"},
{GenelDil.PSEUDONYM,"Pseudonym"},
{GenelDil.SERTIFIKA_AUTHORITY_KEY_ID,"Authority Key Identifier"},
{GenelDil.ISSUER_ALT_NAME,"Issuer Alternative Name"},
{GenelDil.SERTIFIKA_BASIC_CONS,"Basic Contraints"},
{GenelDil.SERTIFIKA_KEY_USAGE,"Key Usage"},
{GenelDil.SERTIFIKA_SUBJECT_KEY_ID,"Subject Key Identifier"},
{GenelDil.SERTIFIKA_POLICY_MAPPINGS,"Policy Mappings"},
{GenelDil.SERTIFIKA_SERIAL_NUMBER,"Serial Number"},
{GenelDil.SERTIFIKA_POLICIES,"Certificate Policies"},
{GenelDil.PLACEOFBIRTH,"Place of Birth"},
{GenelDil.ROLE,"Role"},
{GenelDil.VERSION,"Version"},
{GenelDil.ISSUER,"Issuer"},
{GenelDil.SUBJECT,"Subject"},
{GenelDil.SERTIFIKA,"Certificate"},
{GenelDil.CERTSIGN,"Certificate Signing"},
{GenelDil.SERTIFIKA_EXTENDED_KEY_USAGE,"Extended Key Usage"},
{GenelDil.SIL_ISSUING_DIST_POINT,"CRL Issuing Distribution Point"},
{GenelDil.SIL_REASON_CODE,"Revocation Reason"},
{GenelDil.SIL_REASON_CODE_IMZ, "Sign Certificate Revocation Reason"},
{GenelDil.SIL_REASON_CODE_SIF, "Encyrption Certificate Revocation Reason"},
{GenelDil.SIL_HOLD_INST_CODE,"Hold Instruction Code"},
{GenelDil.SERTIFIKA_AIA,"Authority Key Identifier"},
{GenelDil.SERTIFIKA_CDP,"CRL Distribution Points"},
{GenelDil.SERTIFIKA_SAN,"Subject Alternative Name"},
{GenelDil.SERTIFIKA_QC_STATEMENTS,"Qualified Certificate Statements"},
{GenelDil.SERTIFIKA_SUBJECT_DIRECTORY_ATTR,"Subject Directory Attributes"},
{GenelDil.DUGME_DETAY,"Details"},
{GenelDil.EKU_CLIENT_AUTHENTICATION,"Client Authentication"},
{GenelDil.EKU_SERVER_AUTHENTICATION,"Server Authentication"},
{GenelDil.EKU_CODE_SIGNING,"Code Signing"},
{GenelDil.EKU_EMAIL_PROTECTION,"E-mail protection"},
{GenelDil.EKU_IPSEC_TUNNEL,"IPSEC Tunnel"},
{GenelDil.EKU_IPSEC_USER,"IPSEC User"},
{GenelDil.EKU_IPSEC_END_SYSTEM,"IPSEC End System"},
{GenelDil.EKU_OCSP_SIGNING,"OCSP Signing"},
{GenelDil.EKU_TIME_STAMPING,"Time Stamping"},
{GenelDil.EKU_DVCS,"DVCS"},
{GenelDil.key_let_logYazmaGirisimi,"Log Writing Attempt"},
{GenelDil.key_let_denetlenenOlaylarinDegistirilmesi,"Audited Events Change"},
{GenelDil.key_let_denetlemeLoglariSilmeGirisimi,"Audited Log Changing Attempt"},
{GenelDil.key_let_sertifikaImzalanmasi,"Certificate Signing"},
{GenelDil.key_let_sertifikaAskiyaAlinmasi,"Certificate Hold"},
{GenelDil.key_let_sertifikaAskidanIndirilmesi,"Removing Certificate from Hold"},
{GenelDil.key_let_sertifikaIptalEdilmesi,"Certificate Revoke"},
{GenelDil.key_let_sertifikaSablonuOlusturulmasi,"Creating Certificate Template"},
{GenelDil.key_let_sertifikaSablonuSilinmesi,"Deleting Certificate Template"},
{GenelDil.key_let_sertifikaIstekMesajiGelmesi,"Certification Request Arriving"},
{GenelDil.key_let_sertifikaAskiyaAlmaIstegi,"Certificate Hold Request"},
{GenelDil.key_let_sertifikaAskidanIndirmeIstegi,"Removing Certificate from Hold Request"},
{GenelDil.key_let_sertifikaIptalIstegi,"Certificate Revoke Request"},
{GenelDil.key_let_yetkiDegisiklikleri,"Authorization Change"},
{GenelDil.key_let_sistemParametreleriDegistirilmesi,"System Parameters Change"},
{GenelDil.key_let_yetkiliEkleme,"Authorized User Adding"},
{GenelDil.key_let_silOlusturma,"CRL Publishing"},
{GenelDil.key_let_kullaniciOlusturma,"Creating User"},
{GenelDil.key_let_cihazOlusturma,"Creating Device"},
{GenelDil.key_let_kullaniciSilinmesi,"Deleting User"},
{GenelDil.key_let_cihazSilinmesi,"Deleting Device"},
{GenelDil.key_let_kullaniciBilgilerindeDegisiklikYapilmasi,"Changing User Info"},
{GenelDil.key_let_cihazBilgilerindeDegisiklikYapilmasi,"Changing Device Info"},
{GenelDil.key_let_sifrelemeAnahtariGonderilmesi,"Sending Enciphering Key"},
{GenelDil.key_let_sifrelemeAnahtarinaUlasim,"Enciphering Key Arriving"},
{GenelDil.key_let_smServisininCalismasi,"Certificate Service Start"},
{GenelDil.key_let_smServisininDurmasi,"Certificate Service Stop"},
{GenelDil.key_let_kontrolMerkezininCalismasi,"Administration Center Start"},
{GenelDil.key_let_kontrolMerkezininDurmasi,"Administration Center Stop"},
{GenelDil.key_let_webKayitMakamininCalismasi,"Registration Authority Start"},
{GenelDil.key_let_webKayitMakamininDurmasi,"Registration Authority Stop"},
{GenelDil.key_let_silServisininCalismasi,"CRL Service Start"},
{GenelDil.key_let_silServisininDurmasi,"CRL Service Stop"},
{GenelDil.key_let_kayitcininSistemeGirmesi,"Registrar Starts System"},
{GenelDil.key_let_kayitcininSistemdenCikmasi,"Registrar Stops System"},
{GenelDil.key_let_ksmAnahtarDegisimi,"Root CA Key Update"},
{GenelDil.key_let_smAnahtarDegisimiIcinIstekUretilmesi,"Creating Request for CA Key Update"},
{GenelDil.key_let_smAnahtarDegisimi,"CA Key Update"},
{GenelDil.key_let_silKonfigurasyonuEklenmesi,"CRL Configuration Adding"},
{GenelDil.key_let_silKonfigurasyonuGuncellenmesi,"CRL Configuration Updating"},
{GenelDil.key_let_silSablonuEklenmesi,"CRL Template Adding"},
{GenelDil.key_let_silSablonuGuncellenmesi,"CRL Template Updating"},
{GenelDil.adresine_baglanilamadi,"Can not connect to {0}"},
};

     @Override
     public Object[][] getContents () //NOPMD
     {
          return mGenelContents;
     }

}
