package tr.gov.tubitak.uekae.esya.api.common.bundle;

import java.util.ListResourceBundle;


public class GenelBundle_az extends ListResourceBundle
{
    protected static Object[][] mGenelContents =
    {

          {GenelDil.ACIKLAMA, "Açıqlama"},
          {GenelDil.ACIKLAMA_GIRINIZ, "Zəhmət olmasa, açıqlama daxil edin!"},
          {GenelDil.AD, "Ad"},
          {GenelDil.ADRES, "Ünvan"},
          {GenelDil.AKTARIM_BILGILERI, "Ötürmə Məlumatları"},
          {GenelDil.AKTIF, "Aktiv"},
          {GenelDil.AKTIF_YAP, "Aktiv et"},
          {GenelDil.ALGORITMA, "Alqoritm"},
          {GenelDil.ANAHTAR, "Açar"},
          {GenelDil.ANAHTAR_ADI, "Açar Adı"},
          {GenelDil.ANAHTAR_BOYU, "Açar Boyu"},
          {GenelDil.ANAHTAR_URETME, "Açar Yaratma"},
          {GenelDil.Anahtar_Bilgileri, "Açar Məlumatları"},
          {GenelDil.ARA, "Axtar"},
          {GenelDil.ARAMA, "Axtarış"},
          {GenelDil.ASKIDA, "Asqıda"},
          {GenelDil.ASKIYAAL, "Asqıya Alma Tələbi Yarat"},
          {GenelDil.AYARLAR, "Ayarlar"},
          {GenelDil.BASARILI, "Uğurlu"},
          {GenelDil.BASARISIZ, "Uğursuz"},
          {GenelDil.IL, "Vilayət"},
          {GenelDil.ILCE, "Rayon"},
          {GenelDil.HEPSI, "Hamısı"},
          {GenelDil.HAKKINDA, "Haqqında"},
          {GenelDil.DOSYA_KAYDET, "Dosyeyə qeyd et"},
          {GenelDil.DOSYA_OKUNAMADI, "Dosye oxuna bilmədi!"},
          {GenelDil.DOSYA_SECILMEDI, "Dosye seçilmədi!"},
          {GenelDil.DOSYA_YOLU, "Dosye yolu"},
          {GenelDil.EPOSTA, "Elektron poçt"},
          {GenelDil.EVET, "Bəli"},
          {GenelDil.GECERLI, "Etibarlı"},
          {GenelDil.KAYIT_MAKAMI, "Qeydiyyat Orqanı"},
          {GenelDil.ESYA_KONTROL_MERKEZI, "ESYA Nəzarət Mərkəzi"},
          {GenelDil.ESYA_KONTROL_MERKEZI_B, "ESYA NƏZARƏT MƏRKƏZİ"},
          {GenelDil.KONTROL_MERKEZI, "Nəzarət Mərkəzi"},
          {GenelDil.IMZALA, "İmzala"},
          {GenelDil.SIFRELE, "Şifrələ"},
          {GenelDil._0_1_ARALIGINDA_OLMALI, "Saylar {0}-{1} aralığında olmalı!"},
          {GenelDil._0_ALGORITMASIYLA_SIFRECOZME_YAPILAMIYOR, "{0} alqoritmi ilə şifrə açma aparıla bilmir!"},
          {GenelDil._0_ISLEMI_ICIN_YETERLI_YETKINIZ_YOK, "{0} əməliyyatını gerçəkləşdirmək üçün yetərli səlahiyyətə malik deyilsiniz!"},
          {GenelDil.ANA_DIZIN, "Ana kataloq"},
          {GenelDil.ANAH_URETILEMEDI, "Açar istehsalında xəta!"},
          {GenelDil.ANAHTAR_HATALI, "Simmetrik Şifrələmə açarı istifadə edilmir!"},
          {GenelDil.ANAHTAR_SERTIFIKA_BETIGI, "Açar/Sertifikatt Skripti"},
          {GenelDil.ANAHTAR_URETILIYOR, "Açar(lar) yaradılır"},
          {GenelDil.ARAMA_FILTRESI_HATALI, "Verilən axtarış filtri xətalıdır! (Axtarış filter)"},
          {GenelDil.ARAMADA_BILINMEYEN_HATA, "Axtarışda bilinməyən bir xəta baş verdi! Axtarış nöqtəsini doğru verdiyinizdən əmin olun!"},
          {GenelDil.ARANAN_TKA_0_BULUNAMADI, "Axtarılan TKA \"{0}\" tapıla bilmədi!"},
          {GenelDil.ARGUMAN_BILINMIYOR, "Verilən arqument bilinmir!"},
          {GenelDil.ASN1_DECODE_HATASI, "Asn1 strukturu DECODE edilərkən xəta ilə qarşılaşıldı!"},
          {GenelDil.ASN1_ENCODE_HATASI, "Asn1 strukturu ENCODE edilərkən xəta ilə qarşılaşıldı!"},
          {GenelDil.ATTRIBUTE_BILINMIYOR, "LDAP'dan gətirilməsi istənən atribut bilinməyən bir atribut!"},
          {GenelDil.ATTRIBUTEA_VERILMEK_ISTENEN_DEGER_HATALI, "Atributa verilmək istənən dəyər atributun sxem təsviri ilə düz gəlmir!"},
          {GenelDil.BAKILACAK_YER, "Baxılacaq Yer"},
          {GenelDil.BASLIK_ANAHTAR_PARCALAMA, "Açar Parçalama"},
          {GenelDil.BASLIK_HAKKINDA, "Haqqında"},
          {GenelDil.BASLIK_SIFRENIZ, "Şifrəniz"},
          {GenelDil.BASLIK_SLOTLISTESI, "Slot Siyahısı Seçimi"},
          {GenelDil.BELGE, "Sənəd"},
          {GenelDil.BELGE_NO, "Sənəd No"},
          {GenelDil.BELGE_YOLU, "Sənəd Yolu"},
          {GenelDil.BILGI, "Məlumat"},
          {GenelDil.BIRDEN_FAZLA_EMAIL, "Email ilə axtarış aparılmasına baxmayaraq birdən artıq nəticə tapıldı! Yalnız birini qaytarıram!"},
          {GenelDil.BLOKUZUNLUGU_0_ALGI_1_DESTEKLEMIYOR, "Blok uzunluğunda xəta var! {0} alqoritmi {1} blok uzunluğunu dəstəkləmir!"},
          {GenelDil.CA_CERT_ERROR, "SM sertifikatı alınarkən xəta baş verdi!"},
          {GenelDil.CALISTIRILMAMASI_GEREKEN_FONKSIYON, "Çağrılmaması lazım gələn bir funksiya çağırıldı."},
          {GenelDil.CARD_NO_CONFLICT, "Kartdan və məlumat bazasından oxunan kart seriya nömrələri eyni deyil!"},
          {GenelDil.CERT_HATALI, "Verilən sertifikat xətalıdır!"},
          {GenelDil.CERTSIGN, "Sertifikat İmzalama"},
          {GenelDil.CKR_DEVICE_MEMORY_M, "Ağıllı kart hafizəsində xəta baş verdi"},
          {GenelDil.CKR_PIN_INCORRECT_M, "Parolunuz xətalı"},
          {GenelDil.CKR_PIN_INVALID_M, "Parolunuz etibarsız"},
          {GenelDil.CKR_PIN_LOCKED_M, "Ağıllı kartınızın PIN parolu kilidləndi."},
          {GenelDil.CKR_TOKEN_NOT_PRESENT_M, "Ağıllı Kartınızı Taxın"},
          {GenelDil.CKR_USER_ALREADY_LOGGED_IN_M, "İstifadəçi login olmuş vəziyyətdədir."},
          {GenelDil.COMMONNAME, "CommonName (ÜmumiAd)"},
          {GenelDil.COUNTRYCITIZENSHIP, "CountryCitizenship (Vətəndaşı olduğu ölkə)"},
          {GenelDil.COUNTRYNAME, "CountryName (Ölkənin adı)"},
          {GenelDil.COUNTRYRESIDENCE, "CountryResidence (Yaşadığı ölkə)"},
          {GenelDil.CRLSIGN, "CRL İmzalama"},
          {GenelDil.DATAENCIPHERMENT, "Verilən şifrələmə"},
          {GenelDil.DATEOFBIRTH, "DateOfBirth (Doğum tarixi)"},
          {GenelDil.DECIPHERONLY, "DecipherOnly (yalnız deşifrə et)"},
          {GenelDil.DEFAULT_KURUM, "Default qurum, SM sahibidir"},
          {GenelDil.DEGISME_TARIHI, "Dəyişmə tarixi"},
          {GenelDil.DENEME_YAZISI, "Yoxlama yazısı"},
          {GenelDil.DESTEKLENEN_MECHANIZMA_YOK, "Dəstəklənən bir PKCS#11 mexanizmi tapıla bilmədi!"},
          {GenelDil.DETAYLAR, "Detallar"},
          {GenelDil.DIGITALSIGNATURE, "Rəqəmli imza"},
          {GenelDil.DIL, "Dil"},
          {GenelDil.DIZIN_ADI, "Kataloq Adı"},
          {GenelDil.DIZINSIF_VEYA_KULLADI_HATALI, "LDAP'a bağlanarkən kataloq şifrəsi və ya istifadəçi adı yanlış verildi!"},
          {GenelDil.DLL_LOAD_EDILEMEDI, "Dll yüklənə bilmədi"},
          {GenelDil.DNSNAME, "DNS Adı"},
          {GenelDil.DOMAIN_COMPONENT, "domainKomponent"},
          {GenelDil.DOSYA_ADI, "Dosye adı"},
          {GenelDil.DOSYA_GORUNTULE, "Dosyeni ekrana çıxar"},
          {GenelDil.DOSYA_SEC, "Dosye seç"},
          {GenelDil.DOSYA_SECINIZ, "Dosye seçin"},
          {GenelDil.DOSYA_TURU, "Dosye növü"},
          {GenelDil.DUGME_AC, "Aç"},
          {GenelDil.DUGME_BITIR, "Bitir"},
          {GenelDil.DUGME_DETAY, "Detallar"},
          {GenelDil.DUGME_DIZIN_DNEKLE, "DN əlavə et"},
          {GenelDil.DUGME_DIZINDENSEC, "Kataloqdan seç"},
          {GenelDil.DUGME_DN_OLUSTUR, "DN yarat"},
          {GenelDil.DUGME_EKLE, "Əlavə et"},
          {GenelDil.DUGME_ETKINLESTIR, "Aktivləşdir"},
          {GenelDil.DUGME_EVET, "Bəli"},
          {GenelDil.DUGME_GUNCELLE, "Aktivləşdir"},
          {GenelDil.DUGME_HAYIR, "Xeyir"},
          {GenelDil.DUGME_INIYAZ, "INI yaz"},
          {GenelDil.DUGME_KAYDET, "Qeyd et"},
          {GenelDil.DUGME_KOPYA_CIKAR, "Surət çıxar"},
          {GenelDil.DUGME_ONAYLA, "Təsdiq et"},
          {GenelDil.DUGME_PKCS10ISTEGI, "PKCS10 İstəyini yarat"},
          {GenelDil.DUGME_SERTIFIKAAL, "Sertifikat Al"},
          {GenelDil.DUGME_SERVISI_BASLAT, "Servisi Başlat"},
          {GenelDil.DUGME_SERVISI_DURDUR, "Servisi Durdur"},
          {GenelDil.DUGME_SIL, "Sil"},
          {GenelDil.DUGME_SILYAYINLA, "Yeni CRL Yayınla"},
          {GenelDil.DUGME_TAMAM, "Tamam"},
          {GenelDil.DUGME_TARIH_SEC, "Tarix Seç"},
          {GenelDil.DUGME_TEMIZLE, "Təmizlə"},
          {GenelDil.DUGME_TUMUNUKALDIR, "Hamısını Qaldır"},
          {GenelDil.DUGME_TUMUNUSEC, "Hamısını Seç"},
          {GenelDil.DUGME_VAZGEC, "Vaz keç"},
          {GenelDil.DUGME_VT_TEMIZLE, "VT Təmizlə"},
          {GenelDil.DUGME_YENILE, "Yenilə"},
          {GenelDil.DURUM, "Durum"},
          {GenelDil.ECDSAANAHTARBOYU_0_BILINMIYOR, "ECDSA açar boyu {0} üçün parametrlər bilinmir."},
          {GenelDil.EKLENECEK_NOKTA_BULUNAMADI, "Yeni daxiletmənin əlavə ediləcəyi nöqtə tapıla bilmədi!"},
          {GenelDil.EKLERKEN_AYNI_TKA, "LDAP'ta, LDAP'a yeni əlavə edilmək istənən məlumat ilə eyni TKA-lı və ya elektron poçt ünvanlı bir daxiletmə var!"},
          {GenelDil.EKLERKEN_BILINMEYEN_HATA, "LDAP'ta yeni daxiletmə yaradarkən bilinməyən bir xəta baş verdi!"},
          {GenelDil.EKLERKEN_EKSIK_ATTRIBUTE, "LDAP'a yeni əlavə edilməsi istənən daxiletmənin məcburi atributlarının hamısı verilməyib!"},
          {GenelDil.ENCIPHERONLY, "EncipherOnly (Yalnız deşifrə et)"},
          {GenelDil.ENCODEDECODE_HATASI, "Encode və/və ya decode xətası ilə qarşılaşıldı!"},
          {GenelDil.GENDER, "Gender (Cins)"},
          {GenelDil.GETATTRIBUTELIST_YANLIS_ARGUMANLA_CAGRILDI, "getAtributList funksiyası yanlış arqumentlə çağırıldı!"},
          {GenelDil.GIVENNAME, "VerilmişAd"},
          {GenelDil.GUNCELLEME, "Aktuallaşdırma"},
          {GenelDil.GUNCELLEME_IS_HATALI, "Verilən aktuallaşdırma aparılacaq iş dəyəri standartlar xaricindədir. Default DƏYƏR_ƏLAVƏ ET alınır!"},
          {GenelDil.GUNCELLEMEDE_HATA, "Aktuallaşdırma əməliyyatında xəta baş verdi!"},
          {GenelDil.GUNCELLENECEK_TKA_0_BULUNAMADI, "Aktuallaşmaq istənən TKA \"{0}\" tapıla bilmədi!"},
          {GenelDil.GUNCELLERKEN_CIKACAK_DEGER_BULUNAMADI, "Aktuallaşdırma sırasında çıxarılmaq istənən dəyər tapıla bilmədi!"},
          {GenelDil.GUNCELLERKEN_DEGER_EKLENEMIYOR, "Aktuallaşdırma sırasında əlavə edilmək istənən dəyər əlavə oluna bilmir!"},
          {GenelDil.HATA, "Xəta"},
          {GenelDil.HATALI, "Yok yada Xətalı"},
          {GenelDil.HATASIZ, "Var və Xətasız"},
          {GenelDil.HAYIR, "Xeyir"},
          {GenelDil.HIC_GELMEMELI, "Buraya heç gəlməməli"},
          {GenelDil.HSM_INI_0_OKUNAMADI, "HSM ayar dosyesi '{0}' oxuna bilmədi:"},
          {GenelDil.HSM_INIDEN_DEGERLER_OKUNAMADI, "HSM ayar Dosyesindən dəyərlər oxuna bilmədi!"},
          {GenelDil.HSME_ULASILAMADI, "HSM cihazına çatmaq mümkün olmadı!"},
          {GenelDil.ILKLENDIRME_ANAHTAR_GRUP_NO, "Inisiallaşdırma Açar Qrup No"},
          {GenelDil.ILKLENDIRME_BETIGI, "Inisiallaşdırma Skripti"},
          {GenelDil.ILKLENDIRME_KART_TIPI, "Inisiallaşdırma Kart Tipi"},
          {GenelDil.ILKLENDIRME_SABLON_ADI, "Inisiallaşdırma Şablon Adı"},
          {GenelDil.ILKLENDIRME_SABLON_MAJOR_SURUMU, "Inisiallaşdırma Şablon Böyük Versiyası"},
          {GenelDil.ILKLENDIRME_SABLON_MINOR_SURUMU, "Inisiallaşdırma Şablon Kiçik Versiyası"},
          {GenelDil.IMZA_DOGRULAMA_HATASI, "İmza təsdiq edərkən xəta baş verdi!"},
          {GenelDil.IMZALAMA, "İmzalama"},
          {GenelDil.IMZALAMA_HATASI, "İmzalama apararkən xəta baş verdi!"},
          {GenelDil.IMZALAMADA_HATA, "İmzalamada xəta!"},
          {GenelDil.IMZALG_0_BILINMIYOR, "İmzalama alqoritmi {0} bilinmir!"},
          {GenelDil.IMZALG_0_ICIN_1_BOYUNDAANAH_OLMAZ, "İmzalama alqoritmi {0} üçün {1} boyunda açar dəstəklənmir!"},
          {GenelDil.IMZALG_0_ICIN_OZET_1_BILINMIYOR, "İmzalama alqoritmi {0} üçün qısa məzmun alqoritmi {1} bilinmir!"},
          {GenelDil.IMZALG_YOK, "İmzalama alqoritmi yoxdur!"},
          {GenelDil.IMZALGOZET_YOK, "İmzalama qısa məzmun alqoritmi yoxdur!"},
          {GenelDil.IMZANAH_HATALI, "İmzalama açarı xətalıdır!"},
          {GenelDil.IMZANAHBOY_YOK, "İmzalama açar boyu yoxdur!"},
          {GenelDil.IMZSERTSERINO_HATALI, "Səlahiyyətli istifadəçinin imzalama sertifikatının seriya nömrəsi xətalıdır!"},
          {GenelDil.INIT_EDILMEMIS, "İnisiallaşdırma aparılmadan istifadə edilmək istənir!"},
          {GenelDil.INIT_EDILMIS, "Daha əvvəlcə inisiallaşdırılıb!"},
          {GenelDil.INVALID_CERT, "Sertifikat təsdiq oluna bilmədi!"},
          {GenelDil.IP, "IP"},
          {GenelDil.IP_PORTTA_DIZIN_BULUNAMADI, "LDAP'a bağlanıla bilmədi. Verilən IP və portda kataloq tapıla bilmədi!"},
          {GenelDil.ISLEM_TIPI, "Əməliyyat Tipi"},
          {GenelDil.ISSUER, "Sertifikatı Verən ESHS"},
          {GenelDil.KART_TIPI, "Kart Tipi"},
          {GenelDil.KART_TIPI_VE_PAROLA, "Kart Tipi və Parol"},
          {GenelDil.KART_TIPLERI_OKUNAMADI, "Kart tipləri oxuna bilmədi"},
          {GenelDil.KARTA_LOGIN_OLUNAMADI, "Karta Login oluna bilmədi!"},
          {GenelDil.KARTA_ULASILAMADI, "Ağıllı karta çatmaq olmadı!"},
          {GenelDil.KARTINIZ_TAKILIMI, "Kartınızın taxılmış olmasından əmin olun!"},
          {GenelDil.KARTTA_0_ANAHTARI_VAR, "Kartda {0} adında açar var!"},
          {GenelDil.KARTTA_0_ANAHTARI_YOK, "Kartda {0} adında açar tapıla bilmədi!"},
          {GenelDil.KARTTA_HATA_0, "Ağıllı Kartda xəta baş verdi! {0}"},
          {GenelDil.KARTTA_SIFRECOZME_HATA, "Kartda şifrə açma əməliyyatı aparıla bilmədi!"},
          {GenelDil.KARTTA_SIFRELEME_YAPILAMADI, "Kartda şifrələmə əməliyyatı yapıla bilmədi!"},
          {GenelDil.KARTTAN_BILGILER_ALINAMADI, "Taxılmış kartdan lazımi məlumatlar alına bilməyib!"},
          {GenelDil.KAYDEDILECEK_YER, "Qeyd ediləcək yer"},
          {GenelDil.KEYAGREEMENT, "Açar Müqaviləsi"},
          {GenelDil.KEYCERTSIGN, "AçarSertİmza"},
          {GenelDil.KEYENCIPHERMENT, "Açar Şifrələmə"},
          {GenelDil.KIMLIKNO, "Ş/v nömrəsi"},
          {GenelDil.KIRMIZI, "Qırmızı"},
          {GenelDil.KRIPTO_GENEL_HATA, "Kripto əməliyyatlarında ümumi bir xəta ilə qarşılaşıldı!"},
          {GenelDil.KRIPTOMOD_ANAH_BUTUN, "Açarlar Bütün"},
          {GenelDil.KRIPTOMOD_ANAH_PARCALI_MOFN, "Açarlar Parçalı (MofN)"},
          {GenelDil.KRIPTOMOD_HSM, "HSM (Hardware Security Rejimile)"},
          {GenelDil.KRITIKLOGOLUSTURULAMADI, "Kritik log yaradıla bilmədi"},
          {GenelDil.KULLANIM_BILINMIYOR, "Verilən məqsəd üçün istifadə ediləcək simmetrik alqoritm bilinmir"},
          {GenelDil.LABEL_KARTPAROLASINIGIRINIZ, "Zəhmət olmasa, kartınızın parolunu daxil edin:"},
          {GenelDil.LABEL_SADECETAKILISLOTLAR, "Yalnız taxılmış slotlar"},
          {GenelDil.LABEL_SLOTLISTESI, "Slot Siyahısı"},
          {GenelDil.LDAP_TIP_HATALI, "LDAP tipi xətalıdır!"},
          {GenelDil.LDAPA_BAGLANILAMADI, "LDAP'a bağlanıla bilmədi!"},
          {GenelDil.LDAPA_BAGLANTI_BULUNAMADI, "LDAP bağlantısı qurulmadan əməliyyat keçirilə bilməz. LDAP'a bağlantı tapıla bilmədi!"},
          {GenelDil.LISTE_GIRILIRKEN_HATA, "Siyahı daxil edilərkən xəta"},
          {GenelDil.LISTELE, "Siyahıya al"},
          {GenelDil.LOCALITYNAME, "LokallıqAdı"},
          {GenelDil.LOG, "Log"},
          {GenelDil.LOG_METNI, "Log Mətni"},
          {GenelDil.LOG_MODULU, "Log Rejimli"},
          {GenelDil.LOG_OLAYTIPI, "Log Hadisə Tipi"},
          {GenelDil.LOG_SONUCU, "Log Nəticəsi"},
          {GenelDil.LOG_TARIHI, "Log Tarixi"},
          {GenelDil.LUTFEN_DOLDURUNUZ, "Zəhmət olmasa, doldurun :"},
          {GenelDil.MAVI, "Mavi"},
          {GenelDil.MESAJ_AKILLIKARTBILGILERIALINAMADI, "Ağıllı kart məlumatları alına bilmədi!"},
          {GenelDil.MESAJ_ANAHTAR_PARCALAR_BOLUNUYOR, "Açar parçalara bölünür..."},
          {GenelDil.MESAJ_BILINMEYENHATA, "Lisenziya nəzarətində bilinməyən bir xəta baş verdi!"},
          {GenelDil.MESAJ_BOSALANKALMASIN, "Boş sahə qalmamalı. Zəhmət olmasa, bütün sahələri doldurun!"},
          {GenelDil.MESAJ_DOSYABULUNAMADI, "Lisenziya dosyesi tapıla bilmədi!"},
          {GenelDil.MESAJ_ENAZ_0_BUYUKHARFOLMALI, "Parolda ən azı {0} böyük hərf olmalıdır."},
          {GenelDil.MESAJ_ENAZ_0_KARAKTEROLMALI, "Parol uzunluğu  ən azı {0} olmalıdır."},
          {GenelDil.MESAJ_ENAZ_0_KUCUKHARFOLMALI, "Parolda ən azı {0} kiçik hərf olmalıdır."},
          {GenelDil.MESAJ_ENAZ_0_OZELKARAKTEROLMALI, "Parolda ən azı {0} xüsusi simvol olmalıdır. {1}"},
          {GenelDil.MESAJ_ENAZ_0_RAKAMOLMALI, "Parolda ən azı {0} rəqəm olmalıdır."},
          {GenelDil.MESAJ_ENCOK_0_KARAKTEROLMALI, "Parol uzunluğu ən artıq {0} olmalıdır."},
          {GenelDil.MESAJ_HOSTADIBILINMIYOR, "Host adı bilinmir!"},
          {GenelDil.MESAJ_HOSTHATALI, "Bu kompüterin adı lisenziyadakı məlumatlarla uyğun gəlmir."},
          {GenelDil.MESAJ_IMPL, "Tətbiq :"},
          {GenelDil.MESAJ_IMPLURETICI, "Tətbiq yaradıcısı :"},
          {GenelDil.MESAJ_IMPLVERSION, "Tətbiq Versiya :"},
          {GenelDil.MESAJ_IPHATALI, "Bu kompüterin IP nömrəsi lisenziyadakı məlumatlarla uyğun deyil."},
          {GenelDil.MESAJ_LISANSBASLAMAMIS, "Lisenziyanızın müddəti başlamamışdır."},
          {GenelDil.MESAJ_LISANSBITMIS, "Lisenziyanızın müddəti bitmişdir."},
          {GenelDil.MESAJ_SPEC, "Spec :"},
          {GenelDil.MESAJ_SPECURETICI, "Spec yaradıcısı :"},
          {GenelDil.MESAJ_SPECVERSION, "Spec Versiya :"},
          {GenelDil.MOD_0_BILINMIYOR, "Rejim {0} bilinmir!"},
          {GenelDil.MOD_SECILMEMIS, "istifadə ediləcək rejim seçilməyib!"},
          {GenelDil.MOD_SECILMIS, "Rejim daha əvvəldən seçilib!"},
          {GenelDil.MOFN_KART_OKUNMUS, "Bu Kartdakı açar parçası daha əvvəlcə oxunmuşdur. Zəhmət olmasa, başqa bir kart ilə yoxlayın!"},
          {GenelDil.NESNE_OKUNAMADI, "Predmet oxuna bilmədi"},
          {GenelDil.NO, "No"},
          {GenelDil.NO_DBCONNECTION, "Məlumat bazasına bağlantı xətası!"},
          {GenelDil.NO_SUCH_CARD_NO, "Bu səlahiyyətli istifadəçinin məlumat bazasında kart seriya nömrəsi müəyyən edilməyib!"},
          {GenelDil.NO_SUCH_USER, "Bu istifadəçi adına sahib bir səlahiyyətli istifadəçi sistemdə müəyyən edilməyib!"},
          {GenelDil.NONREPUDIATION, "Red olmayan"},
          {GenelDil.NUMARA, "Nömrə"},
          {GenelDil.OID_0_BILINMIYOR, "Alqoritm OID {0} bilinmir!"},
          {GenelDil.OID_ADI, "OID Adı"},
          {GenelDil.OID_DEGERI, "OID Dəyəri"},
          {GenelDil.ONCA_0_FONKSIYONU_CAGRILMALI, "Əvvəlcə init_SMQurulumIcin(...) funksiyası çağırılmalıdır!"},
          {GenelDil.ONCEKI, "Əvvəlki"},
          {GenelDil.ONIZLEME, "Ön izləmə"},
          {GenelDil.ORGANIZATIONAL_UNIT_NAME, "Təşkilat vahidinin adı"},
          {GenelDil.ORGANIZATION_NAME, "organizationName (Təşkilat Adı)"},
          {GenelDil.OZETALG_0_BILINMIYOR, "Qısa məzmun alqoritmi {0} bilinmir!"},
          {GenelDil.PADDING_BILINMIYOR, "Verilən paddinq bilinmir!"},
          {GenelDil.PADDING_HATALI, "Yanlış paddinq byte'ları ilə qarşılaşıldı!"},
          {GenelDil.PARAMETRELER, "Parametrlər"},
          {GenelDil.PAROLA, "Parol"},
          {GenelDil.PAROLA_HATALI, "Verilən parol xətalıdır!"},
          {GenelDil.PAROLA_SURESI_DOLMUS, "Parol müddəti dolmuşdur!"},
          {GenelDil.PASIF, "Passiv"},
          {GenelDil.PASIF_YAP, "Passiv Et"},
          {GenelDil.PFX_UZANTISI, "PFX Uzantısı"},
          {GenelDil.PLACEOFBIRTH, "Doğum Yeri"},
          {GenelDil.PRIVBYTES_HATALI, "PrivateKey (xüsusi açar) olaraq alınan byte array (bayt oxu) xətalıdır!"},
          {GenelDil.PRIVKEY_OLUSTURULAMADI, "Xüsusi açar yaratmaq üçün məlumatlar alına bilmədi!"},
          {GenelDil.PSEUDONYM, "Psevdonim"},
          {GenelDil.PUBBYTES_HATALI, "PublicKey (xüsusi açar) olaraq alınan byte array xətalıdır!"},
          {GenelDil.PUBKEY_YOK, "Açıq açar əlimdə yoxdur!"},
          {GenelDil.PUBLICKEY_OKUNAMADI, "Kartdan açıq açar oxuna bilmədi!"},
          {GenelDil.RASTGELE, "Təsadüfi"},
          {GenelDil.SONRAKI, "Sonrakı"},
          {GenelDil.SORU, "Sual"},
          {GenelDil.STATE_OR_PROVINCE_NAME, "stateOrProvinceName (dövlət və ya əyalət adı)"},
          {GenelDil.SUBJECT, "Sertifikat Sahibi"},
          {GenelDil.RB_HATA_44105, "Bu səlahiyyətli istifadəçinin məlumat bazasında sertifikat seriya nömrəsi yoxdur!"},
          {GenelDil.RB_HATA_44106, "Kartdan və məlumat bazasından oxunan sertifikat seriya nömrələri eyni deyil!"},
          {GenelDil.ROLE, "Rol (Vəzifə)"},
          {GenelDil.ROLU_KAYITCI_OLAN_IMZ_SERT_BULUNAMADI, "Rolu qeydiyyatçı olan etibarlı imzalama sertifikatı tapıla bilmədi və ya sayı birdən artıqdır!"},
          {GenelDil.SCHEMA_HATASI, "LDAP'da sxem xətası... Sxemə zidd bir iş görülmək istəndi!"},
          {GenelDil.SEARCH_KONTROL_HATALI, "Verilən axtarış nəzarətlərində xəta var!"},
          {GenelDil.SERTIFIKA_ALMA, "Sertifikat alma"},
          {GenelDil.SERTIFIKA_IPTALASKI, "Sertifikat Ləğv/Asqı"},
          {GenelDil.SERTIFIKA_IPTAL_TALEBI, "Sertifikat Ləğv Tələbi"},
          {GenelDil.SERTIFIKA_ISLEMLERI, "Sertifikat Əməliyyatları"},
          {GenelDil.SERTIFIKA_TALEP, "Sertifikat Tələb"},
          {GenelDil.SIFALG_0_BILINMIYOR, "Şifrələmə alqoritmi {0} bilinmir!"},
          {GenelDil.SIFALG_0_ICIN_1_BOYUNDAANAH_OLMAZ, "Şifrələmə alqoritmi {0} üçün {1} boyunda açar dəstəklənmir!"},
          {GenelDil.SIFALG_YOK, "Şifrələmə alqoritmi yoxdur!"},
          {GenelDil.SIFANAH_HATALI, "Şifrələmə açarı xətalıdır!"},
          {GenelDil.SIFANAHBOY_YOK, "Şifrələmə açar boyu yoxdur!"},
          {GenelDil.SIFRE_COZME_HATASI, "Şifrə açma xətası:"},
          {GenelDil.SIFRELEME_HATASI, "Şifrələmə xətası:"},
          {GenelDil.SIFSERTSERINO_OKUMA_HATASI, "Səlahiyyətli istifadəçinin Şifrələmə sertifikat seriya nömrəsi oxunarkən xəta baş verdi!"},
          {GenelDil.SILERKEN_BILINMEYEN_HATA, "LDAP'dan TKA silərkən bilinməyən bir xəta baş verdi!"},
          {GenelDil.SILINECEK_TKA_HATALI, "LDAP'dan silinməsi istənən TKA yanlış verildi!"},
          {GenelDil.SILINECEK_TKADA_ENTRY_VAR, "LDAP'dan silinmək istənən TKA başqa daxiletmə(lər) ehtiva edir!"},
          {GenelDil.SIMALG_BILINMIYOR, "Verilən Simmetrik alqoritm bilinmir!"},
          {GenelDil.SIMALG_OID_BILINMIYOR, "Bu simmetrik alqoritm üçün obyekt ID bilinmir!"},
          {GenelDil.SIMMOD_BILINMIYOR, "Verilən simmetrik alqoritm rejimi bilinmir!"},
          {GenelDil.SOYAD, "Soyad"},
          {GenelDil.SUNIMZOBJE_DOGRU_INIT_EDILMEMIS, "SUN İmzalama obyekti doğru inisiallaşdırılmayıb!"},
          {GenelDil.TC_KIMLIK_NO, "TC Ş/v No"},
          {GenelDil.TIP, "Tip"},
          {GenelDil.TOOLTIP_ISLEMDEVAMEDIYOR, "Əməliyyat davam edir"},
          {GenelDil.TUM_DOSYALAR, "Bütün dosyelər"},
          {GenelDil.TUM_TABLOYU_IMZALA, "Bütün cədvəli imzala"},
          {GenelDil.UPN, "UPN"},
          {GenelDil.UST_DIZIN, "Üst Kataloq"},
          {GenelDil.UYARI, "Xəbərdarlıq"},
          {GenelDil.VARSAYILAN, "Fərz edilən"},
          {GenelDil.VERILEN_ARAMA_NOKTASI_NULL_VEYA_BOS, "Verilən axtarış nöqtəsi sıfır və ya boş!"},
          {GenelDil.VERSION, "Versiya"},
          {GenelDil.VT_ERROR, "Məlumat bazası xətası!"},
          {GenelDil.X400NAME, "X400Name"},
          {GenelDil.YAPILANDIRMADA_EKLENDI, "Konfiqurasiyada əlavə olundu"},
          {GenelDil.YENI_DIZIN_OLUSTUR, "Yeni kataloq yarat"},
          {GenelDil.YESIL, "Yaşıl"},
          {GenelDil.YON_SAY_FARKLI, "Rəhbər sayı köhnə verilənlə eyni deyil!"},
          {GenelDil.YONSAY_MIN_0_OLMALI, "Rəhbər sayı ən azı {0} olmalı!"},
          {GenelDil.YONETICI_EPOSTA, "Rəhbər elektron poçt"},
          {GenelDil.SERTIFIKA, "Sertifikat"},
          {GenelDil.SERTIFIKA_AUTHORITY_KEY_ID, "Xidmət Təminedici Açarın Təyinedicisi (İdentifikatoru)"},
          {GenelDil.SERTIFIKA_AIA, "Xidmət Təminedici Məlumata Çatma"},
          {GenelDil.SERTIFIKA_CDP, "CRL Paylama Nöqtələri"},
          {GenelDil.SERTIFIKA_SAN, "Subyekt Digər Adı"},
          {GenelDil.SERTIFIKA_QC_STATEMENTS, "Keyfiyyətli Sertifikat Aksesuarları"},
          {GenelDil.SERTIFIKA_BASIC_CONS, "Əsas Məhdudiyyətlər"},
          {GenelDil.SERTIFIKA_SUBJECT_DIRECTORY_ATTR, "Subyekt Kataloq Məlumatları"},
          {GenelDil.ISSUER_ALT_NAME, "Issuer Alternative Name (Verənin alternativ adı)"},
          {GenelDil.SERTIFIKA_KEY_USAGE, "Açarın istifadəsi"},
          {GenelDil.SERTIFIKA_SUBJECT_KEY_ID, "Subyekt Açarı Təyinedicisi (İdentifikatoru)"},
          {GenelDil.SERTIFIKA_SERIAL_NUMBER, "Seriya nömrəsi"},
          {GenelDil.SERTIFIKA_POLICY_MAPPINGS, "Prinsip Bərabərləşdirmələri"},
          {GenelDil.SERTIFIKA_POLICIES, "Sertifikat Prinsipləri"},
          {GenelDil.SERTIFIKA_EXTENDED_KEY_USAGE, "Genişləndirilmiş açar istifadəsi"},
          {GenelDil.SIL_ISSUING_DIST_POINT, "Sil Issuing Distribution Point (Paylama Nöqtəsinin Verilməsi)"},
          {GenelDil.SIL_REASON_CODE, "Ləğv səbəbi"},
          {GenelDil.SIL_REASON_CODE_IMZ, "İmzalama sertifikatı ləğv səbəbi"},
          {GenelDil.SIL_REASON_CODE_SIF, "Şifrələmə sertifikatı ləğv səbəbi"},
          {GenelDil.SIL_HOLD_INST_CODE, "Hold Instruction Code"},
          {GenelDil.EKU_CLIENT_AUTHENTICATION, "Müştəri Tanıma"},
          {GenelDil.EKU_SERVER_AUTHENTICATION, "Server Tanıma"},
          {GenelDil.EKU_CODE_SIGNING, "Kod İmzalama"},
          {GenelDil.EKU_EMAIL_PROTECTION, "Elektron Poçt Koruma"},
          {GenelDil.EKU_IPSEC_TUNNEL, "IPSEC tuneli"},
          {GenelDil.EKU_IPSEC_USER, "IPSEC istifadəçisi"},
          {GenelDil.EKU_IPSEC_END_SYSTEM, "IPSEC Yekunlaşdırma Sistemi"},
          {GenelDil.EKU_OCSP_SIGNING, "OCSP İmzalama"},
          {GenelDil.EKU_TIME_STAMPING, "Zaman Damğası"},
          {GenelDil.EKU_DVCS, "DVCS"},
          {GenelDil.key_let_logYazmaGirisimi, "Log yazma təşəbbüsü"},
          {GenelDil.key_let_denetlenenOlaylarinDegistirilmesi, "Yoxlanılan hadisələrin dəyişdirilməsi"},
          {GenelDil.key_let_denetlemeLoglariSilmeGirisimi, "Yoxlanılan Logları Silmə Təşəbbüsü"},
          {GenelDil.key_let_sertifikaImzalanmasi, "Sertifikatın İmzalanması"},
          {GenelDil.key_let_sertifikaAskiyaAlinmasi, "Sertifikatın Asqıya Alınması"},
          {GenelDil.key_let_sertifikaAskidanIndirilmesi, "Sertifikatın Asqıdan Endirilməsi"},
          {GenelDil.key_let_sertifikaIptalEdilmesi, "Sertifikatın Ləğv Edilməsi"},
          {GenelDil.key_let_sertifikaSablonuOlusturulmasi, "Sertifikat Şablonu Yaradılması"},
          {GenelDil.key_let_sertifikaSablonuSilinmesi, "Sertifikat Şablonunun Silinməsi"},
          {GenelDil.key_let_sertifikaIstekMesajiGelmesi, "Sertifikat İstək Mesajının Gəlməsi"},
          {GenelDil.key_let_sertifikaAskiyaAlmaIstegi, "Sertifikat Asqıya Alma İstəyi"},
          {GenelDil.key_let_sertifikaAskidanIndirmeIstegi, "Sertifikat Asqıdan Endirmə İstəyi"},
          {GenelDil.key_let_sertifikaIptalIstegi, "Sertifikatı Ləğv İstəyi"},
          {GenelDil.key_let_yetkiDegisiklikleri, "Səlahiyyət Dəyişiklikləri"},
          {GenelDil.key_let_sistemParametreleriDegistirilmesi, "Sistem Parametrlərinin Dəyişdirilməsi"},
          {GenelDil.key_let_yetkiliEkleme, "Səlahiyyətli Əlavəetmə"},
          {GenelDil.key_let_silOlusturma, "CRL Yaratma"},
          {GenelDil.key_let_kullaniciOlusturma, "İstifadəçi Yaratma"},
          {GenelDil.key_let_cihazOlusturma, "Cihaz Yaratma"},
          {GenelDil.key_let_kullaniciSilinmesi, "İstifadəçinin silinməsi"},
          {GenelDil.key_let_cihazSilinmesi, "Cihazın Silinməsi"},
          {GenelDil.key_let_kullaniciBilgilerindeDegisiklikYapilmasi, "İstifadəçi Məlumatlarında Dəyişiklik Edilməsi"},
          {GenelDil.key_let_cihazBilgilerindeDegisiklikYapilmasi, "Cihaz Məlumatlarında Dəyişiklik Edilməsi"},
          {GenelDil.key_let_sifrelemeAnahtariGonderilmesi, "Şifrələmə Açarı Göndərilməsi"},
          {GenelDil.key_let_sifrelemeAnahtarinaUlasim, "Şifrələmə Açarına Çatma"},
          {GenelDil.key_let_smServisininCalismasi, "SM Servisinin Çalışması"},
          {GenelDil.key_let_smServisininDurmasi, "SM Servisinin Dayanması"},
          {GenelDil.key_let_kontrolMerkezininCalismasi, "Nəzarət Mərkəzinin Çalışması"},
          {GenelDil.key_let_kontrolMerkezininDurmasi, "Nəzarət Mərkəzinin Dayanması"},
          {GenelDil.key_let_webKayitMakamininCalismasi, "Qeydiyyat Orqanının Çalışması"},
          {GenelDil.key_let_webKayitMakamininDurmasi, "Qeydiyyat Orqanının Dayanması"},
          {GenelDil.key_let_silServisininCalismasi, "CRL Servisinin Çalışması"},
          {GenelDil.key_let_silServisininDurmasi, "CRL Servisinin Dayanması"},
          {GenelDil.key_let_kayitcininSistemeGirmesi, "Qeydiyyatçının Sistemə Girməsi"},
          {GenelDil.key_let_kayitcininSistemdenCikmasi, "Qeydiyyatçının Sistemdən Çıxması"},
          {GenelDil.key_let_ksmAnahtarDegisimi, "KSM Açar Dəyişikliyi"},
          {GenelDil.key_let_smAnahtarDegisimiIcinIstekUretilmesi, "SM Açar Dəyişikliyi Üçün İstək Yaradılması"},
          {GenelDil.key_let_smAnahtarDegisimi, "SM Açar Dəyişikliyi"},
          {GenelDil.key_let_silKonfigurasyonuEklenmesi, "CRL Konfiqurasiyasının Əlavə Edilməsi"},
          {GenelDil.key_let_silKonfigurasyonuGuncellenmesi, "CRL Konfiqurasiyasının Aktivləşdirilməsi"},
          {GenelDil.key_let_silSablonuEklenmesi, "CRL Şablonunun Əlavə Edilməsi"},
          {GenelDil.key_let_silSablonuGuncellenmesi, "CRL Şablonunun Aktuallaşdırılması"},
          {GenelDil.adresine_baglanilamadi, "{0} qoşula bilmədi."},
    };


    @Override
    public Object[][] getContents() //NOPMD
    {
        return mGenelContents;
    }

}