package tr.gov.tubitak.uekae.esya.api.common.bundle;

import java.util.ListResourceBundle;

public class GenelBundle_tr extends ListResourceBundle
{
protected static Object[][] mGenelContents =
{
{GenelDil.ACIKLAMA,"Açıklama"},
{GenelDil.ACIKLAMA_GIRINIZ,"Lütfen Açıklama giriniz!"},
{GenelDil.AD,"Ad"},
{GenelDil.ADRES,"Adres"},
{GenelDil.AKTIF,"Aktif"},
{GenelDil.AKTIF_YAP,"Aktif Yap"},
{GenelDil.ALGORITMA,"Algoritma"},
{GenelDil.ANAHTAR,"Anahtar"},
{GenelDil.ANAHTAR_ADI,"Anahtar Adı"},
{GenelDil.ANAHTAR_BOYU,"Anahtar Boyu"},
{GenelDil.Anahtar_Bilgileri,"Anahtar Bilgileri"},
{GenelDil.ARA,"Ara"},
{GenelDil.ASKIDA,"Askıda"},
{GenelDil.BASARILI,"Başarılı"},
{GenelDil.BASARISIZ,"Başarısız"},
{GenelDil.IL,"İl"},
{GenelDil.ILCE,"İlçe"},
{GenelDil.HEPSI,"Hepsi"},
{GenelDil.HAKKINDA,"Hakkında"},
{GenelDil.DOSYA_KAYDET,"Dosyaya Kaydet"},
{GenelDil.DOSYA_OKUNAMADI,"Dosya okunamadı!"},
{GenelDil.DOSYA_SECILMEDI,"Dosya seçilmedi!"},
{GenelDil.DOSYA_YOLU,"Dosya Yolu"},
{GenelDil.EPOSTA,"Eposta"},
{GenelDil.EVET,"Evet"},
{GenelDil.GECERLI,"Geçerli"},
{GenelDil.KAYIT_MAKAMI,"Kayıt Makamı"},
{GenelDil.ESYA_KONTROL_MERKEZI,"ESYA Kontrol Merkezi"},
{GenelDil.ESYA_KONTROL_MERKEZI_B,"ESYA KONTROL MERKEZİ"},
{GenelDil.KONTROL_MERKEZI,"Kontrol Merkezi"},
{GenelDil.IMZALA,"İmzala"},
{GenelDil.SIFRELE,"Şifrele"},
{GenelDil._0_1_ARALIGINDA_OLMALI,"Sayılar {0}-{1} aralığında olmalı!"},
{GenelDil._0_ALGORITMASIYLA_SIFRECOZME_YAPILAMIYOR,"{0} algoritması ile şifre çözme yapılamıyor!"},
{GenelDil._0_ISLEMI_ICIN_YETERLI_YETKINIZ_YOK,"\"{0}\" işlemini gerçekleştirmek için yeterli yetkiye sahip değilsiniz!"},
{GenelDil.AKTARIM_BILGILERI,"Aktarım Bilgileri"},
{GenelDil.ANA_DIZIN,"Ana Dizin"},
{GenelDil.ANAH_URETILEMEDI,"Anahtar üretiminde hata!"},
{GenelDil.ANAHTAR_HATALI,"Simetrik şifreleme anahtarı kullanılamıyor!"},
{GenelDil.ANAHTAR_SERTIFIKA_BETIGI,"Anahtar/Sertifika Betiği"},
{GenelDil.ANAHTAR_URETILIYOR,"Anahtar(lar) Üretiliyor"},
{GenelDil.ANAHTAR_URETME,"Anahtar Üretme"},
{GenelDil.ARAMA,"Arama"},
{GenelDil.ARAMA_FILTRESI_HATALI,"Verilen arama filtresi hatalı! (Search filter)"},
{GenelDil.ARAMADA_BILINMEYEN_HATA,"Aramada bilinmeyen bir hata oluştu! Arama noktasını doğru verdiğinizden emin olunuz!"},
{GenelDil.ARANAN_TKA_0_BULUNAMADI,"Aranan TKA \"{0}\" bulunamadı!"},
{GenelDil.ARGUMAN_BILINMIYOR,"Verilen argüman bilinmiyor!"},
{GenelDil.ASKIYAAL,"Askıya Alma Talebi Oluştur"},
{GenelDil.ASN1_DECODE_HATASI,"Asn1 yapısı DECODE edilirken hata ile karşılaşıldı!"},
{GenelDil.ASN1_ENCODE_HATASI,"Asn1 yapısı ENCODE edilirken hata ile karşılaşıldı!"},
{GenelDil.ATTRIBUTE_BILINMIYOR,"LDAP'tan getirilmesi istenen attribute bilinmeyen bir attribute!"},
{GenelDil.ATTRIBUTEA_VERILMEK_ISTENEN_DEGER_HATALI,"Attribute'a verilmek istenen değer, attribute'un şema tanımıyla çelişiyor!"},
{GenelDil.AYARLAR,"Ayarlar"},
{GenelDil.BAKILACAK_YER,"Bakılacak Yer"},
{GenelDil.BASLIK_ANAHTAR_PARCALAMA,"Anahtar Parçalama"},
{GenelDil.BASLIK_HAKKINDA,"Hakkında"},
{GenelDil.BASLIK_SIFRENIZ,"Şifreniz"},
{GenelDil.BASLIK_SLOTLISTESI,"Slot Listesi Seçimi"},
{GenelDil.BELGE,"Belge"},
{GenelDil.BELGE_NO,"Belge No"},
{GenelDil.BELGE_YOLU,"Belge Yolu"},
{GenelDil.BILGI,"Bilgi"},
{GenelDil.BIRDEN_FAZLA_EMAIL,"Email ile arama yapılmasına rağmen birden fazla sonuç bulundu! Sadece birini dönüyorum!"},
{GenelDil.BLOKUZUNLUGU_0_ALGI_1_DESTEKLEMIYOR,"Blok uzunluğunda hata var! {0} algoritması {1} blok uzunluğunu desteklemiyor!"},
{GenelDil.CA_CERT_ERROR,"SM sertifikası alınırken hata oluştu!"},
{GenelDil.CALISTIRILMAMASI_GEREKEN_FONKSIYON,"Çağrılmaması gereken bir fonksiyon çağrıldı."},
{GenelDil.CARD_NO_CONFLICT,"Karttan ve veritabanından okunan kart seri numaraları aynı değil!"},
{GenelDil.CERT_HATALI,"Verilen sertifika hatalı!"},
{GenelDil.CKR_DEVICE_MEMORY_M,"Akıllı kart hafızasında hata oluştu"},
{GenelDil.CKR_PIN_INCORRECT_M,"Parolanız Hatalı"},
{GenelDil.CKR_PIN_INVALID_M,"Parolanız Geçersiz"},
{GenelDil.CKR_PIN_LOCKED_M,"Akıllı Kartınızın PIN parolası kilitlendi."},
{GenelDil.CKR_TOKEN_NOT_PRESENT_M,"Akıllı Kartınızı Takın"},
{GenelDil.CKR_USER_ALREADY_LOGGED_IN_M,"Kullanıcı login olmuş durumda."},
{GenelDil.COMMONNAME,"CommonName"},
{GenelDil.COUNTRYCITIZENSHIP,"CountryCitizenship (Uyruk)"},
{GenelDil.COUNTRYNAME,"CountryName (Ülke Adı)"},
{GenelDil.COUNTRYRESIDENCE,"CountryResidence (İkamet Edilen Ülke)"},
{GenelDil.CRLSIGN,"SİL İmzalama"},
{GenelDil.DATAENCIPHERMENT,"Veri Şifreleme"},
{GenelDil.DATEOFBIRTH,"DateOfBirth (Doğum Tarihi)"},
{GenelDil.DECIPHERONLY,"DecipherOnly"},
{GenelDil.DEFAULT_KURUM,"Default kurum, SM sahibidir"},
{GenelDil.DEGISME_TARIHI,"Değişme Tarihi"},
{GenelDil.DENEME_YAZISI,"Deneme Yazısı"},
{GenelDil.DESTEKLENEN_MECHANIZMA_YOK,"Desteklenen bir PKCS#11 mekanizması bulunamadı!"},
{GenelDil.DETAYLAR,"Detaylar"},
{GenelDil.DIGITALSIGNATURE,"Sayısal İmza"},
{GenelDil.DIL,"Dil"},
{GenelDil.DIZIN_ADI,"Dizin Adı"},
{GenelDil.DIZINSIF_VEYA_KULLADI_HATALI,"LDAP'a bağlanırken dizin şifresi veya kullanıcı adı yanlış verildi!"},
{GenelDil.DLL_LOAD_EDILEMEDI,"Dll load edilemedi"},
{GenelDil.DNSNAME,"DNS Name"},
{GenelDil.DOMAIN_COMPONENT,"domainComponent"},
{GenelDil.DOSYA_ADI,"Dosya Adı"},
{GenelDil.DOSYA_GORUNTULE,"Dosya Görüntüle"},
{GenelDil.DOSYA_SEC,"Dosya Seç"},
{GenelDil.DOSYA_SECINIZ,"Dosya Seçiniz"},
{GenelDil.DOSYA_TURU,"Dosya Türü"},
{GenelDil.DUGME_AC,"Aç"},
{GenelDil.DUGME_BITIR,"Bitir"},
{GenelDil.DUGME_DIZIN_DNEKLE,"DN Ekle"},
{GenelDil.DUGME_DIZINDENSEC,"Dizinden Seç"},
{GenelDil.DUGME_DN_OLUSTUR,"DN Oluştur"},
{GenelDil.DUGME_EKLE,"Ekle"},
{GenelDil.DUGME_ETKINLESTIR,"Etkinleştir"},
{GenelDil.DUGME_EVET,"Evet"},
{GenelDil.DUGME_GUNCELLE,"Güncelle"},
{GenelDil.DUGME_HAYIR,"Hayır"},
{GenelDil.DUGME_INIYAZ,"INI Yaz"},
{GenelDil.DUGME_KAYDET,"Kaydet"},
{GenelDil.DUGME_KOPYA_CIKAR,"Kopya Çıkar"},
{GenelDil.DUGME_ONAYLA,"Onayla"},
{GenelDil.DUGME_PKCS10ISTEGI,"PKCS10 İsteği Üret"},
{GenelDil.DUGME_SERTIFIKAAL,"Sertifika Al"},
{GenelDil.DUGME_SERVISI_BASLAT,"Servisi Başlat"},
{GenelDil.DUGME_SERVISI_DURDUR,"Servisi Durdur"},
{GenelDil.DUGME_SIL,"Sil"},
{GenelDil.DUGME_SILYAYINLA,"Yeni SİL Yayınla"},
{GenelDil.DUGME_TAMAM,"Tamam"},
{GenelDil.DUGME_TARIH_SEC,"Tarih Seç"},
{GenelDil.DUGME_TEMIZLE,"Temizle"},
{GenelDil.DUGME_TUMUNUKALDIR,"Tümünü Kaldır"},
{GenelDil.DUGME_TUMUNUSEC,"Tümünü Seç"},
{GenelDil.DUGME_VAZGEC,"Vazgeç"},
{GenelDil.DUGME_VT_TEMIZLE,"VT Temizle"},
{GenelDil.DUGME_YENILE,"Yenile"},
{GenelDil.DURUM,"Durum"},
{GenelDil.ECDSAANAHTARBOYU_0_BILINMIYOR,"ECDSA Anahtar boyu {0} icin parametreler bilinmiyor."},
{GenelDil.EKLENECEK_NOKTA_BULUNAMADI,"Yeni entry'nin ekleneceği nokta bulunamadı!"},
{GenelDil.EKLERKEN_AYNI_TKA,"LDAP'ta, LDAP'a yeni eklenmek istenen entry ile aynı TKA'lı veya eposta adresli bir entry var!"},
{GenelDil.EKLERKEN_BILINMEYEN_HATA,"LDAP'ta yeni entry oluştururken bilinmeyen bir hata oluştu!LDAP'ta yeni entry oluştururken bilinmeyen bir hata oluştu!"},
{GenelDil.EKLERKEN_EKSIK_ATTRIBUTE,"LDAP'a yeni eklenmesi istenen entry'nin zorunlu attribute'larının tümü verilmemiş!"},
{GenelDil.ENCIPHERONLY,"EncipherOnly"},
{GenelDil.ENCODEDECODE_HATASI,"Encode ve/veya decode hatası ile karşılaşıldı!"},
{GenelDil.GENDER,"Gender (Cinsiyet)"},
{GenelDil.GIVENNAME,"GivenName"},
{GenelDil.GETATTRIBUTELIST_YANLIS_ARGUMANLA_CAGRILDI,"getAttributeList fonksiyonu yanlış argümanla çağrıldı!"},
{GenelDil.GUNCELLEME,"Güncelleme"},
{GenelDil.GUNCELLEME_IS_HATALI,"Verilen güncelleme yapilacak is değeri standartlar dışında. Default DEGER_EKLE alınıyor!"},
{GenelDil.GUNCELLEMEDE_HATA,"Güncelleme işleminde hata oluştu!"},
{GenelDil.GUNCELLENECEK_TKA_0_BULUNAMADI,"Güncellenmek istenen TKA \"{0}\" bulunamadı!"},
{GenelDil.GUNCELLERKEN_CIKACAK_DEGER_BULUNAMADI,"Güncelleme sırasında çıkarılmak istenen değer bulunamadı!"},
{GenelDil.GUNCELLERKEN_DEGER_EKLENEMIYOR,"Güncelleme sırasında eklenmek istenen değer eklenemiyor!"},
{GenelDil.HATA,"Hata"},
{GenelDil.HATALI,"Yok yada Hatalı"},
{GenelDil.HATASIZ,"Var ve Hatasız"},
{GenelDil.HAYIR,"Hayır"},
{GenelDil.HIC_GELMEMELI,"Buraya hic gelmemeli"},
{GenelDil.HSM_INI_0_OKUNAMADI,"HSM ayar dosyası '{0}' okunamadı:"},
{GenelDil.HSM_INIDEN_DEGERLER_OKUNAMADI,"HSM ayar dosyasından değerler okunamadı!"},
{GenelDil.HSME_ULASILAMADI,"HSM cihazına erişilemedi!"},
{GenelDil.ILKLENDIRME_ANAHTAR_GRUP_NO,"İlklendirme Anahtar Grup No"},
{GenelDil.ILKLENDIRME_BETIGI,"İlklendirme Betiği"},
{GenelDil.ILKLENDIRME_KART_TIPI,"İlklendirme Kart Tipi"},
{GenelDil.ILKLENDIRME_SABLON_ADI,"İlklendirme Şablon Adı"},
{GenelDil.ILKLENDIRME_SABLON_MAJOR_SURUMU,"İlklendirme Şablon Majör Sürümü"},
{GenelDil.ILKLENDIRME_SABLON_MINOR_SURUMU,"İlklendirme Şablon Minör Sürümü"},
{GenelDil.IMZA_ANAHTAR_ALGORITMA_UYUMSUZLUGU,"Seçilen imzalama algoritması ile kullanılan anahtar tipi uyumsuz"},
{GenelDil.IMZA_DOGRULAMA_HATASI,"İmza doğrulanırken hata oluştu!"},
{GenelDil.IMZALAMA,"İmzalama"},
{GenelDil.IMZALAMA_HATASI,"İmzalama yaparken hata oluştu!"},
{GenelDil.IMZALAMADA_HATA,"İmzalamada hata!"},
{GenelDil.IMZALG_0_BILINMIYOR,"İmzalama algoritması {0} bilinmiyor!"},
{GenelDil.IMZALG_0_ICIN_1_BOYUNDAANAH_OLMAZ,"İmzalama algoritması {0} için {1} boyunda anahtar desteklenmiyor!"},
{GenelDil.IMZALG_0_ICIN_OZET_1_BILINMIYOR,"İmzalama algoritması {0} için özet algoritması {1} bilinmiyor!"},
{GenelDil.IMZALG_YOK,"İmzalama algoritması yok!"},
{GenelDil.IMZALGOZET_YOK,"İmzalama özet algoritması yok!"},
{GenelDil.IMZANAH_HATALI,"İmzalama anahtarı hatalı!"},
{GenelDil.IMZANAHBOY_YOK,"İmzalama anahtar boyu yok!"},
{GenelDil.IMZSERTSERINO_HATALI,"Yetkilinin imzalama sertifika seri numarası hatalı!"},
{GenelDil.INIT_EDILMEMIS,"\"Initialize\" edilmeden kullanılmak isteniyor!"},
{GenelDil.INIT_EDILMIS,"Daha önce \"initialize\" edilmiş!"},
{GenelDil.INVALID_CERT,"Sertifika doğrulanamadı!"},
{GenelDil.IP,"IP"},
{GenelDil.IP_PORTTA_DIZIN_BULUNAMADI,"LDAP'a bağlanılamadı. Verilen IP ve portta dizin bulunamadı!"},
{GenelDil.ISLEM_TIPI,"İşlem Tipi"},
{GenelDil.KART_TIPI,"Kart Tipi"},
{GenelDil.KART_TIPI_VE_PAROLA,"Kart Tipi ve Parola"},
{GenelDil.KART_TIPLERI_OKUNAMADI,"Kart tipleri okunamadı"},
{GenelDil.KARTA_LOGIN_OLUNAMADI,"Karta Login olunamadı!"},
{GenelDil.KARTA_ULASILAMADI,"Akıllı karta ulaşılamadı!"},
{GenelDil.KARTINIZ_TAKILIMI,"Kartınızın takılı olduğundan emin olunuz!"},
{GenelDil.KARTTA_0_ANAHTARI_VAR,"Kartta {0} isminde anahtar var!"},
{GenelDil.KARTTA_0_ANAHTARI_YOK,"Kartta {0} isminde anahtar bulunamadı!"},
{GenelDil.KARTTA_HATA_0,"Akıllı kartta hata oluştu! {0}"},
{GenelDil.KARTTA_SIFRECOZME_HATA,"Kartta şifre çözme işlemi yapılamadı!"},
{GenelDil.KARTTA_SIFRELEME_YAPILAMADI,"Kartta şifreleme işlemi yapılamadı!"},
{GenelDil.KARTTAN_BILGILER_ALINAMADI,"Takılı olan karttan gerekli bilgiler alınamamıştır!"},
{GenelDil.KAYDEDILECEK_YER,"Kaydedilecek Yer"},
{GenelDil.KEYAGREEMENT,"Anahtar Anlaşması"},
{GenelDil.KEYCERTSIGN,"KeyCertSign"},
{GenelDil.KEYENCIPHERMENT,"Anahtar Şifreleme"},
{GenelDil.KIMLIK,"Kimlik"},
{GenelDil.KIMLIKNO,"Kimlik Numarası"},
{GenelDil.KIRMIZI,"Kırmızı"},
{GenelDil.KRIPTO_GENEL_HATA,"Kripto işlemlerinde genel bir hata ile karşılaşıldı!"},
{GenelDil.KRIPTOMOD_ANAH_BUTUN,"Anahtarlar Bütün"},
{GenelDil.KRIPTOMOD_ANAH_PARCALI_MOFN,"Anahtarlar Parçalı (MofN)"},
{GenelDil.KRIPTOMOD_HSM,"HSM (Hardware Security Module)"},
{GenelDil.KRITIKLOGOLUSTURULAMADI,"Kritik log oluşturulamadı"},
{GenelDil.KULLANIM_BILINMIYOR,"Verilen amaç için kullanılacak simetrik algoritma bilinmiyor"},
{GenelDil.LABEL_KARTPAROLASINIGIRINIZ,"Lütfen Kartınızın Parolasını Giriniz:"},
{GenelDil.LABEL_SADECETAKILISLOTLAR,"Sadece Takılı Slotlar"},
{GenelDil.LABEL_SLOTLISTESI,"Slot Listesi"},
{GenelDil.LDAP_TIP_HATALI,"LDAP tipi hatali!"},
{GenelDil.LDAPA_BAGLANILAMADI,"LDAP'a bağlanılamadı!"},
{GenelDil.LDAPA_BAGLANTI_BULUNAMADI,"LDAP bağlantısı kurulmadan işlem yapılamaz. LDAP'a bağlantı bulunamadı!"},
{GenelDil.LISTE_GIRILIRKEN_HATA,"Liste girilirken hata"},
{GenelDil.LISTELE,"Listele"},
{GenelDil.LOCALITYNAME,"LocalityName"},
{GenelDil.LOG,"Log"},
{GenelDil.LOG_METNI,"Log Metni"},
{GenelDil.LOG_MODULU,"Log Modülü"},
{GenelDil.LOG_OLAYTIPI,"Log Olay Tipi"},
{GenelDil.LOG_SONUCU,"Log Sonucu"},
{GenelDil.LOG_TARIHI,"Log Tarihi"},
{GenelDil.LUTFEN_DOLDURUNUZ,"Lütfen doldurunuz: "},
{GenelDil.MAVI,"Mavi"},
{GenelDil.MESAJ_AKILLIKARTBILGILERIALINAMADI,"Akıllı kart bilgileri alınamadı!"},
{GenelDil.MESAJ_ANAHTAR_PARCALAR_BOLUNUYOR,"Anahtar parçalara bölünüyor..."},
{GenelDil.MESAJ_BILINMEYENHATA,"Lisans kontrolünde bilinmeyen bir hata oluştu!"},
{GenelDil.MESAJ_BOSALANKALMASIN,"Boş alan kalmamalı. Lütfen tüm alanları doldurunuz!"},
{GenelDil.MESAJ_DOSYABULUNAMADI,"Lisans dosyası bulunamadı!"},
{GenelDil.MESAJ_ENAZ_0_BUYUKHARFOLMALI,"Parolada en az {0} büyük harf olmalı."},
{GenelDil.MESAJ_ENAZ_0_KARAKTEROLMALI,"Parola uzunluğu  en az {0} olmalı."},
{GenelDil.MESAJ_ENAZ_0_KUCUKHARFOLMALI,"Parolada en az {0} küçük harf olmalı."},
{GenelDil.MESAJ_ENAZ_0_OZELKARAKTEROLMALI,"Parolada en az {0} özel karakter olmalı.  {1}"},
{GenelDil.MESAJ_ENAZ_0_RAKAMOLMALI,"Parolada en az {0} rakam olmalı."},
{GenelDil.MESAJ_ENCOK_0_KARAKTEROLMALI,"Parola uzunluğu  en fazla {0} olmalı."},
{GenelDil.MESAJ_ESNEKZDYOK, "Lisans dosyasında esnek zaman damgası alanı bulunamadı. Lisans dosyasını yenileyiniz!"},
{GenelDil.MESAJ_HOSTADIBILINMIYOR,"Host adı bilinmiyor!"},
{GenelDil.MESAJ_HOSTHATALI,"Bu bilgisayarın adı lisanstaki bilgilerle uyuşmuyor."},
{GenelDil.MESAJ_IMPL,"Uygulama           :"},
{GenelDil.MESAJ_IMPLURETICI,"Uygulama üreticisi :"},
{GenelDil.MESAJ_IMPLVERSION,"Uygulama Versiyon  :"},
{GenelDil.MESAJ_IPHATALI,"Bu bilgisayarın IP numarası lisanstaki bilgilerle uyuşmuyor."},
{GenelDil.MESAJ_LISANSBASLAMAMIS,"Lisansınızın süresi başlamamıştır."},
{GenelDil.MESAJ_LISANSBITMIS,"Lisansınızın süresi bitmiştir."},
{GenelDil.MESAJ_SPEC,"Spec           :"},
{GenelDil.MESAJ_SPECURETICI,"Spec üreticisi :"},
{GenelDil.MESAJ_SPECVERSION,"Spec Versiyon  :"},
{GenelDil.MOBIL_IMZA_KULLANICI_IPTALI, "Mobil imza isteği kullanıcı tarafından iptal edildi."},
{GenelDil.MOBIL_COKLU_IMZA_KULLANICI_IPTALI, "{0}. mobil imza isteği kullanıcı tarafından iptal edildi."},
{GenelDil.MOBIL_IMZA_ZAMAN_ASIMI, "Mobil imza isteği zaman aşımına uğradı."},
{GenelDil.MOD_0_BILINMIYOR,"Mod {0} bilinmiyor!"},
{GenelDil.MOD_SECILMEMIS,"Kullanılacak mod seçilmemiş!"},
{GenelDil.MOD_SECILMIS,"Mod daha önce seçilmiş!"},
{GenelDil.MOFN_KART_OKUNMUS,"Bu karttaki anahtar parçası daha önce okunmuştur. Lütfen başka bir kart ile deneyiniz!"},
{GenelDil.NESNE_OKUNAMADI,"Nesne okunamadı"},
{GenelDil.NO,"No"},
{GenelDil.NO_DBCONNECTION,"Veritabanına bağlantı hatası!"},
{GenelDil.NO_SUCH_CARD_NO,"Bu yetkilinin veritabanında kart seri numarası tanımlı değil!"},
{GenelDil.NO_SUCH_USER,"Bu kullanıcı adına sahip bir yetkili sistemde tanımlı değil!"},
{GenelDil.NONREPUDIATION,"Red Olmayan"},
{GenelDil.NUMARA,"Numara"},
{GenelDil.OID_0_BILINMIYOR,"Algoritma OID {0} bilinmiyor!"},
{GenelDil.OID_ADI,"OID Adı"},
{GenelDil.OID_DEGERI,"OID Değeri"},
{GenelDil.ONCA_0_FONKSIYONU_CAGRILMALI,"Önce init_SMKurulumIcin(...) fonksiyonu çağrılmalı!"},
{GenelDil.ONCEKI,"Önceki"},
{GenelDil.ONIZLEME,"Önizleme"},
{GenelDil.ORGANIZATIONAL_UNIT_NAME,"organizationalUnitName"},
{GenelDil.ORGANIZATION_NAME,"organizationName (Organizasyon Adı)"},
{GenelDil.OZETALG_0_BILINMIYOR,"Özet algoritması {0} bilinmiyor!"},
{GenelDil.PADDING_BILINMIYOR,"Verilen padding bilinmiyor!"},
{GenelDil.PADDING_HATALI,"Yanlış padding byte'ları ile karşılaşıldı!"},
{GenelDil.PARAMETRELER,"Parametreler"},
{GenelDil.PAROLA,"Parola"},
{GenelDil.PAROLA_HATALI,"Verilen parola hatalı!"},
{GenelDil.PAROLA_SURESI_DOLMUS,"Parola süresi dolmuş!"},
{GenelDil.PASIF,"Pasif"},
{GenelDil.PASIF_YAP,"Pasif Yap"},
{GenelDil.PFX_UZANTISI,"PFX Uzantısı"},
{GenelDil.PRIVBYTES_HATALI,"PrivateKey olarak alınan byte array hatalı!"},
{GenelDil.PRIVKEY_OLUSTURULAMADI,"Private key oluşturmak için bilgiler alınamadı!"},
{GenelDil.PUBBYTES_HATALI,"PublicKey olarak alınan byte array hatalı!"},
{GenelDil.PUBKEY_YOK,"Public key elimde yok!"},
{GenelDil.PUBLICKEY_OKUNAMADI,"Karttan public key okunamadı!"},
{GenelDil.RASTGELE,"Rastgele"},
{GenelDil.RB_HATA_44105,"Bu yetkilinin veritabanında sertifika seri numarası yok!"},
{GenelDil.RB_HATA_44106,"Karttan ve veritabanından okunan sertifika seri numaraları aynı değil!"},
{GenelDil.ROLU_KAYITCI_OLAN_IMZ_SERT_BULUNAMADI,"Rolü kayıtçı olan geçerli imzalama sertifikası bulunamadı veya 1'den fazla var!"},
{GenelDil.SCHEMA_HATASI,"LDAP'ta şema hatası... Şemaya aykırı bir iş yapılmak istendi!"},
{GenelDil.SEARCH_KONTROL_HATALI,"Verilen Search kontrollerinde hata var!"},
{GenelDil.SERTIFIKA_ALMA,"Sertifika Alma"},
{GenelDil.SERTIFIKA_IPTAL_TALEBI,"Sertifika İptal Talebi"},
{GenelDil.SERTIFIKA_IPTALASKI,"Sertifika İptal/Askı"},
{GenelDil.SERTIFIKA_ISLEMLERI,"Sertifika İşlemleri"},
{GenelDil.SERTIFIKA_TALEP,"Sertifika Talep"},
{GenelDil.SIFALG_0_BILINMIYOR,"Şifreleme algoritması {0} bilinmiyor!"},
{GenelDil.SIFALG_0_ICIN_1_BOYUNDAANAH_OLMAZ,"Şifreleme algoritması {0} için {1} boyunda anahtar desteklenmiyor!"},
{GenelDil.SIFALG_YOK,"Şifreleme algoritması yok!"},
{GenelDil.SIFANAH_HATALI,"Şifreleme anahtarı hatalı!"},
{GenelDil.SIFANAHBOY_YOK,"Şifreleme anahtar boyu yok!"},
{GenelDil.SIFRE_COZME_HATASI,"Şifre çözme hatası:"},
{GenelDil.SIFRELEME_HATASI,"Şifreleme hatası:"},
{GenelDil.SIFSERTSERINO_OKUMA_HATASI,"Yetkilinin şifreleme sertifika seri numarası okunurken hata oluştu!"},
{GenelDil.SILERKEN_BILINMEYEN_HATA,"LDAP'tan TKA silerken bilinmeyen bir hata oluştu!"},
{GenelDil.SILINECEK_TKA_HATALI,"LDAP'tan silinmesi istenen TKA yanlış verildi!"},
{GenelDil.SILINECEK_TKADA_ENTRY_VAR,"LDAP'tan silinmek istenen TKA başka entry(ler) içeriyor!"},
{GenelDil.SIMALG_BILINMIYOR,"Verilen simetrik algoritma bilinmiyor!"},
{GenelDil.SIMALG_OID_BILINMIYOR,"Bu Simetrik algoritma icin Object ID bilinmiyor!"},
{GenelDil.SIMMOD_BILINMIYOR,"Verilen simetrik algoritma modu bilinmiyor!"},
{GenelDil.SONRAKI,"Sonraki"},
{GenelDil.SORU,"Soru"},
{GenelDil.SOYAD,"Soyad"},
{GenelDil.STATE_OR_PROVINCE_NAME,"stateOrProvinceName"},
{GenelDil.SUNIMZOBJE_DOGRU_INIT_EDILMEMIS,"SUN İmzalama objesi doğru initialize edilmemiş!"},
{GenelDil.TC_KIMLIK_NO,"TC Kimlik No"},
{GenelDil.TIP,"Tip"},
{GenelDil.TOOLTIP_ISLEMDEVAMEDIYOR,"İşlem devam ediyor"},
{GenelDil.TUM_DOSYALAR,"Tüm Dosyalar"},
{GenelDil.TUM_TABLOYU_IMZALA,"Tüm Tabloyu İmzala"},
{GenelDil.UPN,"UPN"},
{GenelDil.UST_DIZIN,"Üst Dizin"},
{GenelDil.UYARI,"Uyarı"},
{GenelDil.VARSAYILAN,"Varsayılan"},
{GenelDil.VERILEN_ARAMA_NOKTASI_NULL_VEYA_BOS,"Verilen arama noktası null veya boş!"},
{GenelDil.VT_ERROR,"Veritabanı hatası!"},
{GenelDil.X400NAME,"X400Name"},
{GenelDil.YAPILANDIRMADA_EKLENDI,"Yapılandırmada eklendi"},
{GenelDil.YENI_DIZIN_OLUSTUR,"Yeni Dizin Oluştur"},
{GenelDil.YESIL,"Yeşil"},
{GenelDil.YON_SAY_FARKLI,"Yönetici sayısı eski verilenle aynı değil!"},
{GenelDil.YONETICI_EPOSTA,"Yönetici Eposta"},
{GenelDil.YONSAY_MIN_0_OLMALI,"Yönetici sayısı en az {0} olmalı!"},
{GenelDil.PSEUDONYM,"Pseudonym"},
{GenelDil.SERTIFIKA_AUTHORITY_KEY_ID,"Hizmet Sağlayıcı Anahtarı Tanımlayıcısı"},
{GenelDil.ISSUER_ALT_NAME, "Issuer Alternative Name"},
{GenelDil.SERTIFIKA_BASIC_CONS,"Temel Kısıtlamalar"},
{GenelDil.SERTIFIKA_KEY_USAGE,"Anahtar Kullanımı"},
{GenelDil.SERTIFIKA_SUBJECT_KEY_ID,"Özne Anahtarı Tanımlayıcısı"},
{GenelDil.SERTIFIKA_POLICY_MAPPINGS,"İlke Eşleştirmeleri"},
{GenelDil.SERTIFIKA_SERIAL_NUMBER,"Seri Numarası"},
{GenelDil.SERTIFIKA_POLICIES,"Sertifika İlkeleri"},
{GenelDil.PLACEOFBIRTH,"Doğum Yeri"},
{GenelDil.ROLE,"Role (Görev)"},
{GenelDil.VERSION,"Versiyon"},
{GenelDil.ISSUER,"Sertifikayı Veren ESHS"},
{GenelDil.SUBJECT,"Sertifika Sahibi"},
{GenelDil.SERTIFIKA,"Sertifika"},
{GenelDil.CERTSIGN,"Sertifika İmzalama"},
{GenelDil.SERTIFIKA_EXTENDED_KEY_USAGE,"Gelişmiş Anahtar Kullanımı"},
{GenelDil.SIL_ISSUING_DIST_POINT, "Sil Issuing Distribution Point"},
{GenelDil.SIL_REASON_CODE, "İptal Nedeni"},
{GenelDil.SIL_REASON_CODE_IMZ, "İmzalama Sertifikası İptal Nedeni"},
{GenelDil.SIL_REASON_CODE_SIF, "Şifreleme Sertifikası İptal Nedeni"},
{GenelDil.SIL_HOLD_INST_CODE, "Hold Instruction Code"},
{GenelDil.SERTIFIKA_AIA,"Hizmet Sağlayıcı Bilgi Erişimi"},
{GenelDil.SERTIFIKA_CDP,"SİL Dağıtım Noktaları"},
{GenelDil.SERTIFIKA_SAN,"Özne Diğer Adı"},
{GenelDil.SERTIFIKA_QC_STATEMENTS,"Nitelikli Sertifika Eklentileri"},
{GenelDil.SERTIFIKA_SUBJECT_DIRECTORY_ATTR,"Özne Dizin Bilgileri"},
{GenelDil.DUGME_DETAY,"Detay"},
{GenelDil.EKU_CLIENT_AUTHENTICATION,"İstemci Tanıma"},
{GenelDil.EKU_SERVER_AUTHENTICATION,"Sunucu Tanıma"},
{GenelDil.EKU_CODE_SIGNING,"Kod İmzalama"},
{GenelDil.EKU_EMAIL_PROTECTION,"Elektronik Posta Koruma"},
{GenelDil.EKU_IPSEC_TUNNEL,"IPSEC tunnel"},
{GenelDil.EKU_IPSEC_USER,"IPSEC Kullanıcısı"},
{GenelDil.EKU_IPSEC_END_SYSTEM,"IPSEC Sonlandırma Sistemi"},
{GenelDil.EKU_OCSP_SIGNING,"OCSP İmzalama"},
{GenelDil.EKU_TIME_STAMPING,"Zaman Damgası"},
{GenelDil.EKU_DVCS,"DVCS"},
{GenelDil.key_let_logYazmaGirisimi,"Log Yazma Girişimi"},
{GenelDil.key_let_denetlenenOlaylarinDegistirilmesi,"Denetlenen Olayların Değiştirilmesi"},
{GenelDil.key_let_denetlemeLoglariSilmeGirisimi,"Denetlenen Logları Silme Girişimi"},
{GenelDil.key_let_sertifikaImzalanmasi,"Sertifikanın İmzalanması"},
{GenelDil.key_let_sertifikaAskiyaAlinmasi,"Sertifikanın Askıya Alınması"},
{GenelDil.key_let_sertifikaAskidanIndirilmesi,"Sertifikanın Askıdan İndirilmesi"},
{GenelDil.key_let_sertifikaIptalEdilmesi,"Sertifikanın İptal Edilmesi"},
{GenelDil.key_let_sertifikaSablonuOlusturulmasi,"Sertifika Şablonu Oluşturulması"},
{GenelDil.key_let_sertifikaSablonuSilinmesi,"Sertifika Şablonunun Silinmesi"},
{GenelDil.key_let_sertifikaIstekMesajiGelmesi,"Sertifika İstek Mesajı Gelmesi"},
{GenelDil.key_let_sertifikaAskiyaAlmaIstegi,"Sertifika Askıya Alma İsteği"},
{GenelDil.key_let_sertifikaAskidanIndirmeIstegi,"Sertifika Askıdan İndirme İsteği"},
{GenelDil.key_let_sertifikaIptalIstegi,"Sertifika İptal İsteği"},
{GenelDil.key_let_yetkiDegisiklikleri,"Yetki Değişiklikleri"},
{GenelDil.key_let_sistemParametreleriDegistirilmesi,"Sistem Parametrelerinin Değiştirilmesi"},
{GenelDil.key_let_yetkiliEkleme,"Yetkili Ekleme"},
{GenelDil.key_let_silOlusturma,"SİL Oluşturma"},
{GenelDil.key_let_kullaniciOlusturma,"Kullanıcı Oluşturma"},
{GenelDil.key_let_cihazOlusturma,"Cihaz Oluşturma"},
{GenelDil.key_let_kullaniciSilinmesi,"Kullanıcı Silinmesi"},
{GenelDil.key_let_cihazSilinmesi,"Cihaz Silinmesi"},
{GenelDil.key_let_kullaniciBilgilerindeDegisiklikYapilmasi,"Kullanıcı Bilgilerinde Değişiklik Yapılması"},
{GenelDil.key_let_cihazBilgilerindeDegisiklikYapilmasi,"Cihaz Bilgilerinde Değişiklik Yapılması"},
{GenelDil.key_let_sifrelemeAnahtariGonderilmesi,"Şifreleme Anahtarı Gönderilmesi"},
{GenelDil.key_let_sifrelemeAnahtarinaUlasim,"Şifreleme Anahtarına Ulaşım"},
{GenelDil.key_let_smServisininCalismasi,"SM Servisinin Çalışması"},
{GenelDil.key_let_smServisininDurmasi,"SM Servisinin Durması"},
{GenelDil.key_let_kontrolMerkezininCalismasi,"Kontrol Merkezinin Çalışması"},
{GenelDil.key_let_kontrolMerkezininDurmasi,"Kontrol Merkezinin Durması"},
{GenelDil.key_let_webKayitMakamininCalismasi,"Kayıt Makamının Çalışması"},
{GenelDil.key_let_webKayitMakamininDurmasi,"Kayıt Makamının Durması"},
{GenelDil.key_let_silServisininCalismasi,"SİL Servisinin Çalışması"},
{GenelDil.key_let_silServisininDurmasi,"SİL Servisinin Durması"},
{GenelDil.key_let_kayitcininSistemeGirmesi,"Kayıtçının Sisteme Girmesi"},
{GenelDil.key_let_kayitcininSistemdenCikmasi,"Kayıtçının Sistemden Çıkması"},
{GenelDil.key_let_ksmAnahtarDegisimi,"KSM Anahtar Değişimi"},
{GenelDil.key_let_smAnahtarDegisimiIcinIstekUretilmesi,"SM Anahtar Değişimi İçin İstek Üretilmesi"},
{GenelDil.key_let_smAnahtarDegisimi,"SM Anahtar Değişimi"},
{GenelDil.key_let_silKonfigurasyonuEklenmesi,"SİL Konfigürasyonu Eklenmesi"},
{GenelDil.key_let_silKonfigurasyonuGuncellenmesi,"SİL Konfigürasyonu Güncellenmesi"},
{GenelDil.key_let_silSablonuEklenmesi,"SİL Şablonu Eklenmesi"},
{GenelDil.key_let_silSablonuGuncellenmesi,"SİL Şablonu Güncellenmesi"},
{GenelDil.adresine_baglanilamadi,"{0} adresine bağlanılamadı."},
};

@Override
public Object[][] getContents () //NOPMD
{
     return mGenelContents;
}

}