/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 04-Oct-2013.
 */
package tr.gov.tubitak.uekae.esya.asn.cmp;

import com.objsys.asn1j.runtime.*;

public class PKIStatus extends Asn1Integer {

	private static final long serialVersionUID = 55;
	static {
		setKey(_cmpRtkey._rtkey);
	}

   public final static int accepted = 0;
   public final static int grantedWithMods = 1;
   public final static int rejection = 2;
   public final static int waiting = 3;
   public final static int revocationWarning = 4;
   public final static int revocationNotification = 5;
   public final static int keyUpdateWarning = 6;

   public PKIStatus () {
      super();
   }

   public PKIStatus (long value_) {
      super (value_);
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " = " + toString());
   }
}
