#ifndef __CMSLIBRARY_GLOBAL_H__
#define __CMSLIBRARY_GLOBAL_H__

#include "esyaOrtak.h"


/*
#define CMS_FUNC_BEGIN		FUNCTRY_BEGIN(ESYACMS_MOD)
#define CMS_FUNC_END		FUNCTRY_END(ESYACMS_MOD)
*/

#define CMS_FUNC_BEGIN		DEBUGLOGYAZ(ESYACMS_MOD,QString("%1 fonksiyonu BASLADI").arg(__EFUNC__));
#define CMS_FUNC_END		DEBUGLOGYAZ(ESYACMS_MOD,QString("%1 fonksiyonu BITTI").arg(__EFUNC__));


#define CMS_FUNC_TRY_BEGIN	FUNCTRY_BEGIN(ESYACMS_MOD)
#define CMS_FUNC_TRY_END	FUNCTRY_END(ESYACMS_MOD)

#ifdef CMSLIBRARY_LIB
# define CMSLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define CMSLIBRARY_EXPORT Q_DECL_IMPORT
#endif




#endif // CMSLIBRARY_GLOBAL_H
