// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.6.4, Date: 10-Oct-2013.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace tr.gov.tubitak.uekae.esya.asn.signaturepolicies {

   public class SignatureValidationPolicy : Asn1Type {
      public SigningPeriod signingPeriod;
      public CommonRules commonRules;
      public CommitmentRules commitmentRules;
      public SignPolExtensions signPolExtensions;  // optional

      static SignatureValidationPolicy ()
      {
         Asn1Type.SetKey2 (_signaturepoliciesValues._rtkey);
      }

      public SignatureValidationPolicy () : base()
      {
         Init();
      }

      /// <summary>
      /// This constructor sets all elements to references to the 
      /// given objects
      /// </summary>
      public SignatureValidationPolicy (
         SigningPeriod signingPeriod_,
         CommonRules commonRules_,
         CommitmentRules commitmentRules_,
         SignPolExtensions signPolExtensions_
      )
         : base ()
      {
         signingPeriod = signingPeriod_;
         commonRules = commonRules_;
         commitmentRules = commitmentRules_;
         signPolExtensions = signPolExtensions_;
      }

      /// <summary>
      /// This constructor is for required elements only.  It sets 
      /// all elements to references to the given objects
      /// </summary>
      public SignatureValidationPolicy (
         SigningPeriod signingPeriod_,
         CommonRules commonRules_,
         CommitmentRules commitmentRules_
      )
         : base ()
      {
         signingPeriod = signingPeriod_;
         commonRules = commonRules_;
         commitmentRules = commitmentRules_;
      }

      public void Init () {
         signingPeriod = null;
         commonRules = null;
         commitmentRules = null;
         signPolExtensions = null;
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = (explicitTagging) ?
            MatchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

         Init ();

         // decode SEQUENCE

         Asn1BerDecodeContext _context =
            new Asn1BerDecodeContext (buffer, llen);

         IntHolder elemLen = new IntHolder();

         // decode signingPeriod

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
            signingPeriod = new SigningPeriod();
            signingPeriod.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode commonRules

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
            commonRules = new CommonRules();
            commonRules.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode commitmentRules

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
            commitmentRules = new CommitmentRules();
            commitmentRules.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode signPolExtensions

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
            signPolExtensions = new SignPolExtensions();
            signPolExtensions.Decode (buffer, true, elemLen.mValue);
         }

      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = 0, len;

         // encode signPolExtensions

         if (signPolExtensions != null) {
            len = signPolExtensions.Encode (buffer, true);
            _aal += len;
         }

         // encode commitmentRules

         len = commitmentRules.Encode (buffer, true);
         _aal += len;

         // encode commonRules

         len = commonRules.Encode (buffer, true);
         _aal += len;

         // encode signingPeriod

         len = signingPeriod.Encode (buffer, true);
         _aal += len;

         if (explicitTagging) {
            _aal += buffer.EncodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
         }

         return (_aal);
      }

      public override void Print (System.IO.TextWriter _out, 
                                  string _varName, int _level)
      {
         Indent (_out, _level);
         _out.WriteLine (_varName + " {");
         if (signingPeriod != null) signingPeriod.Print (_out, "signingPeriod", _level+1);
         if (commonRules != null) commonRules.Print (_out, "commonRules", _level+1);
         if (commitmentRules != null) commitmentRules.Print (_out, "commitmentRules", _level+1);
         if (signPolExtensions != null) signPolExtensions.Print (_out, "signPolExtensions", _level+1);
         Indent (_out, _level);
         _out.WriteLine ("}");
      }
   }
}
