/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 04-Oct-2013.
 */
package tr.gov.tubitak.uekae.esya.asn.cms;

import com.objsys.asn1j.runtime.*;

public class CommitmentTypeIndication extends Asn1Type {
   private static final long serialVersionUID = 55;
   static {
      setKey (_etsi101733Rtkey._rtkey);
   }

   public Asn1ObjectIdentifier commitmentTypeId;
   public CommitmentTypeIndication_commitmentTypeQualifier commitmentTypeQualifier;  // optional

   public CommitmentTypeIndication () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public CommitmentTypeIndication (
      Asn1ObjectIdentifier commitmentTypeId_,
      CommitmentTypeIndication_commitmentTypeQualifier commitmentTypeQualifier_
   ) {
      super();
      commitmentTypeId = commitmentTypeId_;
      commitmentTypeQualifier = commitmentTypeQualifier_;
   }

   /**
    * This constructor is for required elements only.  It sets 
    * all elements to references to the given objects
    */
   public CommitmentTypeIndication (
      Asn1ObjectIdentifier commitmentTypeId_
   ) {
      super();
      commitmentTypeId = commitmentTypeId_;
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public CommitmentTypeIndication (int[] commitmentTypeId_,
      CommitmentTypeIndication_commitmentTypeQualifier commitmentTypeQualifier_
   ) {
      super();
      commitmentTypeId = new Asn1ObjectIdentifier (commitmentTypeId_);
      commitmentTypeQualifier = commitmentTypeQualifier_;
   }

   /**
    * This constructor is for required elements only.  It allows 
    * primitive data to be passed for all primitive elements.  
    * It will create new object wrappers for the primitive data 
    * and set other elements to references to the given objects. 
    */
   public CommitmentTypeIndication (
      int[] commitmentTypeId_
   ) {
      super();
      commitmentTypeId = new Asn1ObjectIdentifier (commitmentTypeId_);
   }

   public void init () {
      commitmentTypeId = null;
      commitmentTypeQualifier = null;
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode commitmentTypeId

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 6, elemLen, false)) {
         commitmentTypeId = new Asn1ObjectIdentifier();
         commitmentTypeId.decode (buffer, true, elemLen.value);
      }
      else throw new Asn1MissingRequiredException (buffer, "commitmentTypeId");

      // decode commitmentTypeQualifier

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
         commitmentTypeQualifier = new CommitmentTypeIndication_commitmentTypeQualifier();
         commitmentTypeQualifier.decode (buffer, true, elemLen.value);
      }

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 6) ||
             _tag.equals (Asn1Tag.UNIV, Asn1Tag.CONS, 16))
            throw new Asn1SeqOrderException ();

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode commitmentTypeQualifier

      if (commitmentTypeQualifier != null) {
         len = commitmentTypeQualifier.encode (buffer, true);
         _aal += len;
      }

      // encode commitmentTypeId

      if (commitmentTypeId != null) {
         len = commitmentTypeId.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("commitmentTypeId");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (commitmentTypeId != null) commitmentTypeId.print (_out, "commitmentTypeId", _level+1);
      if (commitmentTypeQualifier != null) commitmentTypeQualifier.print (_out, "commitmentTypeQualifier", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }
}
