// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.6.4, Date: 10-Oct-2013.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace tr.gov.tubitak.uekae.esya.asn.algorithms {

   public class FieldID : Asn1Type {
      public Asn1ObjectIdentifier fieldType;
      public Asn1OpenType parameters;

      static FieldID ()
      {
         Asn1Type.SetKey2 (_algorithmsValues._rtkey);
      }

      public FieldID () : base()
      {
         Init();
      }

      /// <summary>
      /// This constructor sets all elements to references to the 
      /// given objects
      /// </summary>
      public FieldID (
         Asn1ObjectIdentifier fieldType_,
         Asn1OpenType parameters_
      )
         : base ()
      {
         fieldType = fieldType_;
         parameters = parameters_;
      }

      /// <summary>
      /// This constructor allows primitive data to be passed for all 
      /// primitive elements.  It will create new object wrappers for 
      /// the primitive data and set other elements to references to 
      /// the given objects 
      /// </summary>
      public FieldID (int[] fieldType_,
         Asn1OpenType parameters_
      )
         : base ()
      {
         fieldType = new Asn1ObjectIdentifier (fieldType_);
         parameters = parameters_;
      }

      public void Init () {
         fieldType = null;
         parameters = null;
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = (explicitTagging) ?
            MatchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

         Init ();

         // decode SEQUENCE

         Asn1BerDecodeContext _context =
            new Asn1BerDecodeContext (buffer, llen);

         IntHolder elemLen = new IntHolder();

         // decode fieldType

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 6, elemLen, false)) {
            fieldType = new Asn1ObjectIdentifier();
            fieldType.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode parameters

         if (!_context.Expired ()) {
            parameters = new Asn1OpenType();
            parameters.Decode (buffer, true, 0);
         }
         else throw new Asn1MissingRequiredException (buffer);

      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = 0, len;

         // encode parameters

         len = parameters.Encode (buffer, true);
         _aal += len;

         // encode fieldType

         len = fieldType.Encode (buffer, true);
         _aal += len;

         if (explicitTagging) {
            _aal += buffer.EncodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
         }

         return (_aal);
      }

      public override void Print (System.IO.TextWriter _out, 
                                  string _varName, int _level)
      {
         Indent (_out, _level);
         _out.WriteLine (_varName + " {");
         if (fieldType != null) fieldType.Print (_out, "fieldType", _level+1);
         if (parameters != null) parameters.Print (_out, "parameters", _level+1);
         Indent (_out, _level);
         _out.WriteLine ("}");
      }
   }
}
