package tr.gov.tubitak.uekae.esya.api.common.bundle.cert;

import tr.gov.tubitak.uekae.esya.api.common.bundle.GenelBundle_az;


public class SertifikaBundle_az extends GenelBundle_az
{
     private static Object[][] mSertifikaContents =
     {
          {CertI18n.TAB1,"Sertifikat"},
          {CertI18n.TAB2,"Genişləndirilmiş görünüş"},
          {CertI18n.TAB3,"Sertifikat zənciri"},
          {CertI18n.SERTIFIKA_DOSYA,"Sertifikat dosyeləri"},
          {CertI18n.DATE_AFTER,"Etibarlılığın başlanğıcı"},
          {CertI18n.DATE_BEFORE,"Etibarlılıq sonu"},
          {CertI18n.SERTIFIKA_GOSTER,"Sertifikatı göstər"},
          {CertI18n.BC_TYPE,"Subyekt növü"},
          {CertI18n.BC_CA,"Sertifikat orqanı"},
          {CertI18n.BC_CA_DEGIL,"Sertifikat orqanı deyil"},
          {CertI18n.BC_PATH,"Yol uzunluğunun məhdudlaşdırılması"},
          {CertI18n.POLICY_IDENTIFIER,"Prinsip identifikatoru"},
          {CertI18n.POLICY_ID,"Prinsip spesifikatorunun kimliyi"},
          {CertI18n.POLICY_INFO,"Prinsip spesifikatorunun məlumatı"},
          {CertI18n.POLICY_QUALIFIER,"Spesifikator"},
          {CertI18n.POLICY_NOTICE,"İstifadəçi bildirişi"},
          {CertI18n.POLICY_CPS,"CPS"},
          {CertI18n.AKI_ID,"Açar identifikatoru"},
          {CertI18n.AKI_ISSUER,"Səlahiyyətli istifadəçi sertifikatını verən"},
          {CertI18n.AKI_SERIAL,"Səlahiyyətli istifadəçi sertifikat seriya nömrəsi"},
          {CertI18n.PM_IDP,"Sertifikatı təmin edən sahə prinsipi"},
          {CertI18n.PM_SDP,"Mövzu sahə prinsipi"},
          {CertI18n.NITELIKLI_COMPLIANCE,"Bu Sertifikat, ETSI TƏSDIQ 101 862 standartına görə yaradılmış yüksək keyfiyyətli elektron sertifikatdır."},
          {CertI18n.NITELIKLI_TK,"Telekommunikasiya qurumu tərəfindən müəyyən edilmiş keyfiyyətli elektron sertifikat profilinə uyğundur."},
          {CertI18n.NITELIKLI_MONEY_LIMIT,"Pul Limiti"},
          {CertI18n.KULLANIM,"İstifadə Məqsədləri"},
          {CertI18n.BILGI,"Sertifikat Məlumatları"},
          {CertI18n.TIP,"Tip"},
          {CertI18n.ESHS,"ESHS"},
          {CertI18n.BASLANGIC_TARIHI,"Başlanğıc tarixi"},
          {CertI18n.BITIS_TARIHI,"Bitmə tarixi"},
          {CertI18n.IMZA_SERTIFIKASI,"İmza sertifikatı"},
          {CertI18n.KONTROL_SONUCU,"Yoxlamanın nəticəsi"},
          {CertI18n.DELTA_CRL_INDICATOR_KONTROLU,"Delta CRL identifikator nəzarəti"},
          {CertI18n.DELTA_CRL_INDICATOR_VAR,"Delta CRL identifikator var"},
          {CertI18n.DELTA_CRL_INDICATOR_YOK,"Delta CRL identifikatoru yoxdur"},
          {CertI18n.FRESHEST_CRL_KONTROLU,"Freshest CRL nəzarəti"},
          {CertI18n.FRESHEST_CRL_VAR,"Freshest CRL var"},
          {CertI18n.FRESHEST_CRL_YOK,"Freshest CRL yoxdur"},
          {CertI18n.OCSP_CEVABI_KONTROLCU,"OCSP cavabının yoxlanılması"},
          {CertI18n.BASARILI,"Uğurlu"},
          {CertI18n.MALFORMED_REQUEST,"Malformed sorğusu"},
          {CertI18n.INTERNAL_ERROR,"Daxili xəta"},
          {CertI18n.TRY_LATER,"Bir azdan sınayın"},
          {CertI18n.SIG_REQUIRED,"Tələb olunan imza"},
          {CertI18n.UNAUTHORIZED,"Səlahiyyətsiz"},
          {CertI18n.OCSP_IMZALAYAN_SERTIFIKA_KONTROLU,"OCSP imzalayıcı sertifikat nəzarəti"},
          {CertI18n.IMZALAYAN_SERTIFIKA_GECERLI,"İmzalayan sertifikat etibarlı"},
          {CertI18n.IMZALAYAN_SERTIFIKA_GECERSIZ,"İmzalayan sertifikat etibarsız"},
          {CertI18n.OCSP_IMZA_KONTROLU,"OCSP cavabı İmza nəzarəti"},
          {CertI18n.CEVAP_IMZALI_DEGIL,"OCSP cavabı imzalı deyil"},
          {CertI18n.CEVAP_YAPISI_BOZUK,"OCSP cavab strukturu pozuqdur"},
          {CertI18n.CEVAPTA_SERTIFIKA_YOK,"OCSP cavabında sertifikat yox"},
          {CertI18n.SERTIFIKA_OCSP_SERTIFIKASI_DEGIL,"OCSP cavabındakı sertifikat OCSP sertifikatı deyil"},
          {CertI18n.DOGRULAMA_KRIPTO_HATASI,"Təsdiqetmə kripto xətası"},
          {CertI18n.IMZA_DOGRULANAMADI,"OCSP cavabının İmzası təsdiq oluna bilmədi"},
          {CertI18n.IMZA_DOGRULANDI,"OCSP cavabı imzası təsdiq olundu"},
          {CertI18n.OCSPDEN_IPTAL_KONTROLU,"OCSPdən ləğv nəzarəti"},
          {CertI18n.OCSP_CEVABI_GECERSIZ,"OCSP cavabı etibarsızdır"},
          {CertI18n.OCSP_CEVABI_BULUNAMADI,"OCSP cavabı tapıla bilmədi"},
          {CertI18n.SM_SERTIFIKASI_BULUNAMADI,"SM sertifikatı tapıla bilmədi"},
          {CertI18n.SERTIFIKA_OCSPDE_GECERLI,"Sertifikat OCSP-də etibarlıdır"},
          {CertI18n.SERTIFIKA_OCSPDE_GECERLI_DEGIL,"Sertifikat OCSP-də etibarlı deyil"},
          {CertI18n.SILDEN_IPTAL_KONTROLU,"Sildən ləğv nəzarəti"},
          {CertI18n.SIL_GECERSIZ,"CRL etibarsız"},
          {CertI18n.SERTIFIKA_LISTEDE,"Sertifikat Crldə ləğv edilib"},
          {CertI18n.SERTIFIKA_LISTEDE_DEGIL,"Sertifikat Crldə yoxdur"},
          {CertI18n.SIL_BULUNAMADI,"CRL tapıla bilmədi"},
          {CertI18n.BASE_SILDE_ASKIYA_ALINAN_DELTADA_REMOVE_EDILMIS,"Əsas Crldə asqıya alınmış sertifikat delta Crldə çıxarılmışdır"},
          {CertI18n.SERTIFIKA_DELTA_SILDE,"Sertifikat delta Crldə ləğv edilmiş"},
          {CertI18n.SERTIFIKA_DELTA_SILDE_REMOVE_EDILMIS,"Sertifikat delta Crldə çıxarılmış"},
          {CertI18n.SERI_NO_KONTROLU,"Seriya nömrəsi nəzarəti"},
          {CertI18n.SERI_NO_POZITIF,"Seriya nömrəsi pozitiv"},
          {CertI18n.SERI_NO_NEGATIF,"Seriya nömrəsi mənfidir"},
          {CertI18n.SERTIFIKA_EKLENTI_KONTROLU,"Sertifikat aksesuar nəzarəti"},
          {CertI18n.EKLENTI_YOK,"Sertifikatda aksesuar yoxdur"},
          {CertI18n.GECERSIZ_EKLENTI,"Sertifikatda etibarsız bir aksesuar var"},
          {CertI18n.AYNI_EXTENSION_BIRDEN_FAZLA,"Sertifikatda eyni aksesuardan birdən artıq var"},
          {CertI18n.EKLENTILER_GECERLI,"Sertifikat aksesuarları etibarlıdır"},
          {CertI18n.SERTIFIKA_TARIH_KONTROLU,"Sertifikat etibarlılıq tarixi nəzarəti"},
          {CertI18n.SERTIFIKA_TARIH_GECERLI,"Sertifikat tarixi etibarlıdır"},
          {CertI18n.SERTIFIKA_TARIH_GECERSIZ,"Sertifikat tarixi etibarsızdır"},
          {CertI18n.SERTIFIKA_SURESI_DOLMUS,"Sertifikat müddəti dolmuş"},
          {CertI18n.SERTIFIKA_TARIH_BILGISI_BOZUK,"Sertifikat tarix məlumatı strukturu pozuqdur"},
          {CertI18n.SIGNATURE_ALG_AYNIMI_KONTROLU,"İmzalama alqoritmi eynidirmi nəzarəti"},
          {CertI18n.SIGNATURE_ALG_AYNI,"İmzalama alqoritmi dəyərləri eynidir"},
          {CertI18n.SIGNATURE_ALG_FARKLI,"İmzalama alqoritmi dəyərləri fərqlidir"},
          {CertI18n.SERTIFIKA_VERSIYON_KONTROLU,"Sertifikat versiya nəzarəti"},
          {CertI18n.EXTENSION_VAR_DOGRU,"Aksesuar var, versiya 3"},
          {CertI18n.EXTENSION_VAR_YANLIS,"Aksesuar var, versiya 3 deyil"},
          {CertI18n.UID_VAR_DOGRU,"UID var, versiya 2 yaxud üstü"},
          {CertI18n.UID_VAR_YANLIS,"UID var, versiya 2 yaxud üstü deyil"},
          {CertI18n.BASIT_ALANLAR_VAR_DOGRU,"Bəsit Sahələr var, versiya 1 yaxud üstü"},
          {CertI18n.BASIT_ALANLAR_VAR_YANLIS,"Bəsit Sahələr var, versiya 1 yaxud üstü deyil"},
          {CertI18n.BASIC_CONST_CA_KONTROLU,"Əsas məhdudiyyətlər CA nəzarəti"},
          {CertI18n.BASIC_CONST_EKLENTI_YOK,"Əsas məhdudiyyətlər aksesuarı yoxdur"},
          {CertI18n.BASIC_CONST_EKLENTISI_BOZUK,"Əsas məhdudiyyətlər aksesuarı pozuqdur"},
          {CertI18n.BASIC_CONST_EKLENTI_CA_DEGERI_YOK,"Əsas məhdudiyyətlər aksesuarının CA dəyəri yoxdur"},
          {CertI18n.BASIC_CONST_EKLENTI_CA_DEGERI_YANLIS,"Əsas məhdudiyyətlər aksesuarının CA dəyəri yanlışdır"},
          {CertI18n.BASIC_CONST_EKLENTI_CA_DEGERI_DOGRU,"Əsas məhdudiyyətlər aksesuarının CA dəyəri doğrudur"},
          {CertI18n.KEY_IDENTIFIER_KONTROLU,"Açar identifikator nəzarəti"},
          {CertI18n.SERTIFIKA_AUTHORITY_KEY_IDENTIFIER_YOK,"Sertifikatda səlahiyyətli istifadəçi açar identifikatoru yoxdur"},
          {CertI18n.SMSERTIFIKA_SUBJECT_KEY_IDENTIFIER_YOK,"SM Sertifikatında mövzu açar identifikatoru"},
          {CertI18n.AUTHORITY_SUBJECT_KEY_IDENTIFIER_UYUMSUZ,"Sertifikatdakı səlahiyyətli istifadəçi açar identifikatoru ilə SM sertifikatındakı mövzu açar identifikatoru uğun deyil"},
          {CertI18n.AUTHORITY_SUBJECT_KEY_IDENTIFIER_UYUMLU,"Sertifikatdakı səlahiyyətli istifadəçi açar identifikatoru ilə SM sertifikatındakı mövzu açar identifikatoru uyğundur"},
          {CertI18n.PATH_LEN_CONSTRAINT_KONTROLU,"yol uzunluğu məhdudlaşdırıcısı nəzarəti"},
          {CertI18n.BASIC_CONST_EKLENTI_LEN_CONS_DEGERI_YOK,"Əsas məhdudiyyətlər aksesuarında yol uzunluğu məhdudlaşdırıcısı yoxdur"},
          {CertI18n.BASIC_CONST_EKLENTI_LEN_CONS_DEGERI_NEGATIF,"Əsas məhdudiyyətlər aksesuarında yol uzunluğu məhdudlaşdırıcısının dəyəri mənfidir"},
          {CertI18n.BASIC_CONST_EKLENTI_LEN_CONS_DEGERI_ASILDI,"Əsas məhdudiyyətlər aksesuarında yol uzunluğu məhdudlaşdırıcısının dəyər həddi keçildi"},
          {CertI18n.BASIC_CONST_EKLENTI_LEN_CONS_DEGERI_GECERLI,"Əsas məhdudiyyətlər aksesuarında yol uzunluğu məhdudlaşdırıcısı Dəyəri Etibarlıdır"},
          {CertI18n.SERTIFIKA_IMZA_KONTROLU,"Sertifikat İmza nəzarəti"},
          {CertI18n.SERTIFIKA_IMZALI_DEGIL,"Sertifikat imzalı deyil"},
          {CertI18n.SERTIFIKA_YAPISI_BOZUK,"Sertifikat strukturu pozuqdur"},
          {CertI18n.SERTIFIKADA_ACIK_ANAHTAR_YOK,"Sertifikatda açıq açar yoxdur"},
          {CertI18n.SERTIFIKADA_ACIK_ANAHTAR_BOZUK,"Sertifikatdakı açıq açar pozuqdur"},
          {CertI18n.SERTIFIKA_IMZA_DOGRULANAMADI,"Sertifikat İmzası Təsdiq oluna bilmədi"},
          {CertI18n.SERTIFIKA_IMZA_DOGRULANDI,"Sertifikat İmzası Təsdiq olundu"},
          
//          {CertI18n.KEY_USAGE_YOK,"Açar istifadəsi aksesuarı yoxdur"},
//          {CertI18n.KEY_USAGE_BOZUK,"Açar istifadəsi aksesuarı strukturu pozuqdur"},
//          {CertI18n.KEY_USAGE_SERTIFIKA_IMZALAYICI_DEGIL,"açar istifadəsi aksesuarı sertifikat imzalayıcı deyil"},
//          {CertI18n.KEY_USAGE_SERTIFIKA_IMZALAYICI,"açar istifadəsi aksesuarı sertifikat imzalayıcı"},
          {CertI18n.SIL_IMZA_KONTROLU,"CRL imza nəzarəti"},
          {CertI18n.SIL_IMZALI_DEGIL,"CRL imzalı deyil"},
          {CertI18n.SIL_YAPISI_BOZUK,"CRL strukturu pozuqdur"},
          {CertI18n.SIL_IMZA_DOGRULANAMADI,"CRL imzası təsdiq oluna bilmədi"},
          {CertI18n.SIL_IMZA_DOGRULANDI,"CRL imzası təsdiq olundu"},
          {CertI18n.SIL_KEY_USAGE_KONTROLU,"CRL açar istifadəsi aksesuarı nəzarəti"},
          {CertI18n.KEY_USAGE_SIL_IMZALAYICI_DEGIL,"Açar istifadəsi aksesuarı CRL imzalayıcı deyil"},
          {CertI18n.KEY_USAGE_SIL_IMZALAYICI,"Açar istifadəsi aksesuarı CRL imzalayıcı"},
          {CertI18n.SIL_NAME_KONTROLU,"CRL adı nəzarəti"},
          {CertI18n.SIL_EKLENTI_KONTROLU,"CRL aksesuar nəzarəti"},
          {CertI18n.SIL_TARIH_KONTROLU,"CRL tarix nəzarəti"},
          {CertI18n.GECERLI,"Sertifikat etibarlıdır"},
          {CertI18n.IPTAL_KONTROLU_SORUNLU,"Ləğv nəzarəti problemlidir"},
          {CertI18n.ZINCIR_SORUNLU,"Sertifikat zənciri problemlidir"},
          {CertI18n.IPTAL_EDILMIS,"Ləğv edilmiş sertifikat"},
          {CertI18n.ASKIDA,"Sertifikat asqıda"},

     };

     private static Object[][] mContents = new Object[mGenelContents.length + mSertifikaContents.length][];

     static
     {
          System.arraycopy(mGenelContents, 0, mContents, 0, mGenelContents.length);
          System.arraycopy(mSertifikaContents, 0, mContents, mGenelContents.length, mSertifikaContents.length);
     }

     @Override
     public Object[][] getContents () //NOPMD
     {
          return mContents;
     }
}

