/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.0.0, Date: 18-Mar-2016.
 */
package tr.gov.tubitak.uekae.esya.asn.attrcert;

import com.objsys.asn1j.runtime.*;
import tr.gov.tubitak.uekae.esya.asn.x509.GeneralNames;

public class V2Form extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      setKey (_attrcertRtkey._rtkey);
   }

   public String getAsn1TypeName()  {
      return "V2Form";
   }

   public GeneralNames issuerName;  // optional
   public IssuerSerial baseCertificateID;  // optional
   public ObjectDigestInfo objectDigestInfo;  // optional

   public V2Form () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public V2Form (
      GeneralNames issuerName_,
      IssuerSerial baseCertificateID_,
      ObjectDigestInfo objectDigestInfo_
   ) {
      super();
      issuerName = issuerName_;
      baseCertificateID = baseCertificateID_;
      objectDigestInfo = objectDigestInfo_;
   }

   public void init () {
      issuerName = null;
      baseCertificateID = null;
      objectDigestInfo = null;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return issuerName;
         case 1: return baseCertificateID;
         case 2: return objectDigestInfo;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "issuerName";
         case 1: return "baseCertificateID";
         case 2: return "objectDigestInfo";
         default: return null;
      }
   }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode issuerName

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
         issuerName = new GeneralNames();
         issuerName.decode (buffer, true, elemLen.value);
      }

      // decode baseCertificateID

      if (_context.matchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 0, elemLen, true)) {
         int offset = buffer.getByteCount();
         baseCertificateID = new IssuerSerial();
         baseCertificateID.decode (buffer, false, elemLen.value);

         int declen = buffer.getByteCount() - offset;
         if (declen != elemLen.value && elemLen.value != Asn1Status.INDEFLEN)
            throw new Asn1InvalidLengthException();

      }

      // decode objectDigestInfo

      if (_context.matchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 1, elemLen, true)) {
         int offset = buffer.getByteCount();
         objectDigestInfo = new ObjectDigestInfo();
         objectDigestInfo.decode (buffer, false, elemLen.value);

         int declen = buffer.getByteCount() - offset;
         if (declen != elemLen.value && elemLen.value != Asn1Status.INDEFLEN)
            throw new Asn1InvalidLengthException();

      }

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.CONS, 16) ||
             _tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 0) ||
             _tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 1))  {
            throw new Asn1SeqOrderException ();
         }
         else  {
            throw new Asn1UnexpectedElementException();
         }

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode objectDigestInfo

      if (objectDigestInfo != null) {
         len = objectDigestInfo.encode (buffer, false);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 1, len);
         _aal += len;
      }

      // encode baseCertificateID

      if (baseCertificateID != null) {
         len = baseCertificateID.encode (buffer, false);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
         _aal += len;
      }

      // encode issuerName

      if (issuerName != null) {
         len = issuerName.encode (buffer, true);
         _aal += len;
      }

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (issuerName != null) issuerName.print (_out, "issuerName", _level+1);
      if (baseCertificateID != null) baseCertificateID.print (_out, "baseCertificateID", _level+1);
      if (objectDigestInfo != null) objectDigestInfo.print (_out, "objectDigestInfo", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }

}
