/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 04-Oct-2013.
 */
package tr.gov.tubitak.uekae.esya.asn.x509;

import com.objsys.asn1j.runtime.*;

public class AnotherName extends Asn1Type {
   private static final long serialVersionUID = 55;
   static {
      setKey (_ImplicitRtkey._rtkey);
   }

   public Asn1ObjectIdentifier type_id;
   public Asn1OpenType value;

   public AnotherName () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public AnotherName (
      Asn1ObjectIdentifier type_id_,
      Asn1OpenType value_
   ) {
      super();
      type_id = type_id_;
      value = value_;
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public AnotherName (int[] type_id_,
      Asn1OpenType value_
   ) {
      super();
      type_id = new Asn1ObjectIdentifier (type_id_);
      value = value_;
   }

   public void init () {
      type_id = null;
      value = null;
   }

   public boolean equals( Object obj ) {
      if ( this == obj ) return true;
      if ( !(obj instanceof AnotherName) ) return false;

      AnotherName rhs = (AnotherName) obj;

      if (type_id == null) {
         if (rhs.type_id != null) return false;
      }
      else {
         if (!type_id.equals(rhs.type_id)) {
            return false;
         }
      }

      if (value == null) {
         if (rhs.value != null) return false;
      }
      else {
         if (!value.equals(rhs.value)) {
            return false;
         }
      }

      return true;
   }

   public int hashCode() {
      int __code = 1;

      if (type_id != null) __code = 31*__code + type_id.hashCode();
      if (value != null) __code = 31*__code + value.hashCode();

      return __code;
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode type_id

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 6, elemLen, false)) {
         type_id = new Asn1ObjectIdentifier();
         type_id.decode (buffer, true, elemLen.value);
      }
      else throw new Asn1MissingRequiredException (buffer, "type_id");

      // decode value

      if (_context.matchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 0, elemLen, true)) {
         value = new Asn1OpenType();
         value.decode (buffer, true, 0);
      }
      else throw new Asn1MissingRequiredException (buffer);

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 6))
            throw new Asn1SeqOrderException ();

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode value

      if (value != null) {
         len = value.encode (buffer, true);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("value");

      // encode type_id

      if (type_id != null) {
         len = type_id.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("type_id");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (type_id != null) type_id.print (_out, "type_id", _level+1);
      if (value != null) value.print (_out, "value", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }
}
