/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 04-Oct-2013.
 */
package tr.gov.tubitak.uekae.esya.asn.x509;

import com.objsys.asn1j.runtime.*;

public class PostalCode extends Asn1Choice {
   private static final long serialVersionUID = 55;
   static {
      setKey (_ExplicitRtkey._rtkey);
   }

   // Choice element identifier constants
   public final static byte _NUMERIC_CODE = 1;
   public final static byte _PRINTABLE_CODE = 2;

   public PostalCode () {
      super();
   }

   public PostalCode (byte choiceId_, Asn1Type element_) {
      super();
      setElement (choiceId_, element_);
   }

   public String getElemName () {
      switch (choiceID) {
      case _NUMERIC_CODE: return "numeric_code";
      case _PRINTABLE_CODE: return "printable_code";
      default: return "UNDEFINED";
      }
   }

   public void set_numeric_code (Asn1NumericString value) {
      setElement (_NUMERIC_CODE, value);
   }

   public void set_printable_code (Asn1PrintableString value) {
      setElement (_PRINTABLE_CODE, value);
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = implicitLength;

      // decode CHOICE

      Asn1Tag tag = new Asn1Tag ();
      buffer.mark (8);
      int len = buffer.decodeTagAndLength (tag);
      final int choiceLen = len;

      int offset = buffer.getByteCount(), declen;

      if (tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 18))
      {
         buffer.reset();
         Asn1NumericString numeric_code;
         numeric_code = new Asn1NumericString();
         numeric_code.decode (buffer, true, len);
         if (!((numeric_code.getLength() >= 1 && numeric_code.getLength() <= 16))) {
            throw new Asn1ConsVioException ("numeric_code.getLength()", numeric_code.getLength());
         }

         setElement (_NUMERIC_CODE, numeric_code);
      }
      else if (tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 19))
      {
         buffer.reset();
         Asn1PrintableString printable_code;
         printable_code = new Asn1PrintableString();
         printable_code.decode (buffer, true, len);
         if (!((printable_code.getLength() >= 1 && printable_code.getLength() <= 16))) {
            throw new Asn1ConsVioException ("printable_code.getLength()", printable_code.getLength());
         }

         setElement (_PRINTABLE_CODE, printable_code);
      }
      else {
         throw new Asn1InvalidChoiceOptionException (buffer, tag);
      }

      declen = buffer.getByteCount() - offset;
      if (choiceLen != Asn1Status.INDEFLEN && choiceLen != declen)
         throw new Asn1InvalidLengthException();
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;
      switch (choiceID) {
      // encode numeric_code
      case _NUMERIC_CODE:
         Asn1NumericString numeric_code = (Asn1NumericString) getElement();
         if (!((numeric_code.getLength() >= 1 && numeric_code.getLength() <= 16))) {
            throw new Asn1ConsVioException ("numeric_code.getLength()", numeric_code.getLength());
         }

         len = numeric_code.encode (buffer, true);
         _aal += len;
         break;

      // encode printable_code
      case _PRINTABLE_CODE:
         Asn1PrintableString printable_code = (Asn1PrintableString) getElement();
         if (!((printable_code.getLength() >= 1 && printable_code.getLength() <= 16))) {
            throw new Asn1ConsVioException ("printable_code.getLength()", printable_code.getLength());
         }

         len = printable_code.encode (buffer, true);
         _aal += len;
         break;

      default:
         throw new Asn1InvalidChoiceOptionException();
      }

      return _aal;
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (element != null) {
         element.print (_out, getElemName(), _level+1);
      }
      indent (_out, _level);
      _out.println ("}");
   }
}
