package tr.gov.tubitak.uekae.esya.api.cmssignature.bundle;

public enum E_KEYS {
		   //General Start
		   _0_MISSING_PARAMETER,
		   _0_WRONG_PARAMETER_TYPE_1_,
		
		  // Archive Time Stamp Attribute Checker Start
		  NO_ARCHIVE_TSA_IN_SIGNEDDATA,
		  ARCHIVE_TSA_DECODE_ERROR,
		  ARCHIVE_TSA_CHECK_UNSUCCESSFUL,
		  ARCHIVE_TSA_CHECK_SUCCESSFUL,
		  
		  //Signer
		  PARENT_SIGNER_ESAv2,
		  PARENT_SIGNER_ESAv3,

		  //Signing in two steps
		  NO_UNFINISHED_SIGNATURE,
		  NOT_VALID_SIGNATURE_VALUE_FOR_UNFINISHED_SIGNATURE,

		  
		  // Archive Time Stamp V2 Attribute Checker Start	
		  NO_ARCHIVE_TSA_V2_IN_SIGNEDDATA,
		  ARCHIVE_TSA_V2_DECODE_ERROR,
		  ARCHIVE_TSA_V2_CHECK_UNSUCCESSFUL,
		  ARCHIVE_TSA_V2_CHECK_SUCCESSFUL,

		  // Archive Time Stamp V3 Attribute Checker Start	
		  NO_ARCHIVE_TSA_V3_IN_SIGNEDDATA,
		  ARCHIVE_TSA_V3_DECODE_ERROR,
		  ARCHIVE_TSA_V3_CHECK_UNSUCCESSFUL,
		  ARCHIVE_TSA_V3_CHECK_SUCCESSFUL,
		  
		  // CAdES_C Time Stamp Attribute Checker Start	
		  NO_CADESC_TSA_IN_SIGNEDDATA,
		  CADESC_TSA_DECODE_ERROR,
		  CADESC_TSA_CHECK_UNSUCCESSFUL,
		  CADESC_TSA_CHECK_SUCCESSFUL,
		  
		  //Certificate Checker Start
		  NO_SIGNING_TIME,
		  CERTIFICATE_VALIDATION_SUCCESSFUL,
		  CERTIFICATE_VALIDATION_UNSUCCESSFUL,
		  CERTIFICATE_VALIDATION_INCOMPLETE,
		  CERTIFICATE_NO_PATH_FOUND,
		  CERTIFICATE_CHECKER_FAIL,
		  CERTIFICATE_REVOCATION_MAP_INCOMPLETE,
		  
		  //Certificate References Values Match Checker
		  NO_COMPLETE_CERTIFICATE_REFERENCES_IN_SIGNEDDATA,
		  COMPLETE_CERTIFICATE_REFERENCES_DECODE_ERROR,
		  NO_CERTIFICATE_VALUES_ATTRIBUTE_IN_SIGNEDDATA,
		  CERTIFICATE_VALUES_ATTRIBUTE_DECODE_ERROR,
		  CertificateRefsValuesMatchChecker_SUCCESSFUL,
		  CertificateRefsValuesMatchChecker_UNSUCCESSFUL,
		  
		  //Check All Checker
		  NO_MUST_ATTRIBUTE_IN_SIGNED_DATA,
		  NO_OPTIONAL_ATTRIBUTE_IN_SIGNED_DATA,
		  ALL_CHECKERS_SUCCESSFULL,
		  ALL_CHECKERS_UNSUCCESSFULL,
		  
		  //Check One Checker
		  NO_CHECKER_SUCCESSFULL,
		  
		  //Content Timestamp Checker
		  NO_CONTENT_TIMESTAMP_ATTRIBUTE_IN_SIGNEDDATA,
		  CONTENT_TIMESTAMP_ATTRIBUTE_DECODE_ERROR,
		  CONTENT_TIMESTAMP_ATTRIBUTE_CHECKER_SUCCESSFUL,
		  CONTENT_TIMESTAMP_ATTRIBUTE_CHECKER_UNSUCCESSFUL,
		  
		  //Content Type Checker
		  NO_CONTENT_TYPE_ATTRIBUTE_IN_SIGNED_DATA,
		  CONTENT_TYPE_ATTRIBUTE_DECODE_ERROR,
		  CONTENT_TYPE_ATTRIBUTE_CHECKER_SUCCESSFUL,
		  CONTENT_TYPE_ATTRIBUTE_CHECKER_UNSUCCESSFUL,
		  
		  //Crypto Checker
		  NO_SIGNER_CERTIFICATE_FOUND,
		  SIGNED_ATTRIBUTES_ENCODE_ERROR,
		  SIGNATURE_VERIFICATION_ERROR,
		  SIGNATURE_VERIFICATION_SUCCESSFUL,
		  SIGNATURE_VERIFICATION_UNSUCCESSFUL,
		  
		  //MessageDigest Checker
		  NO_MESSAGE_DIGEST_ATTRIBUTE_FOUND,
		  MESSAGE_DIGEST_ATTRIBUTE_DECODE_ERROR,
		  SIGNER_DIGEST_ALGORITHM_UNKNOWN,
		  MESSAGE_DIGEST_CHECKER_ERROR,
		  MESSAGE_DIGEST_ATTRIBUTE_CHECKER_SUCCESSFUL,
		  MESSAGE_DIGEST_ATTRIBUTE_CHECKER_UNSUCCESSFUL,
		  
		  //RevocationRefsValuesMatchChecker
		  REVOCATION_REFERENCES_ATTRIBUTE_NOT_FOUND,
		  REVOCATION_REFERENCES_ATTRIBUTE_DECODE_ERROR,
		  REVOCATION_VALUES_ATTRIBUTE_NOT_FOUND,
		  REVOCATION_VALUES_DECODE_ERROR,
		  REVOCATION_REFS_VALUES_MATCH_SUCCESSFUL,
		  REVOCATION_REFS_VALUES_MATCH_UNSUCCESSFUL,
		  
		  //Signature Policy Checker
		  SIGNATURE_POLICY_ATTRIBUTE_NOT_FOUND,
		  SIGNATURE_POLICY_ATTRIBUTE_DECODE_ERROR,
		  SIGNATURE_POLICY_ATTRIBUTE_DIGEST_CALCULATION_ERROR,
		  SIGNATURE_POLICY_ATTRIBUTE_CHECKER_SUCCESSFUL,
		  SIGNATURE_POLICY_ATTRIBUTE_CHECKER_UNSUCCESSFUL,
		  SIGNATURE_POLICY_VALUE_NOT_FOUND,
		  
		  //SignatureTimeStamp Checker
		  SIGNATURE_TS_NOT_FOUND,
		  SIGNATURE_TS_DECODE_ERROR,
		  SIGNATURE_TS_CHECK_SUCCESSFUL,
		  SIGNATURE_TS_CHECK_UNSUCCESSFUL,
		  
		  //SigningTime Checker
		  SIGNING_TIME_ATTRIBUTE_DECODE_ERROR,
		  SIGNING_TIME_CHECKER_SUCCESSFUL,
		  SIGNING_TIME_CHECKER_UNSUCCESSFUL,
		  SIGNING_TIME_EXISTS,
		  NO_SIGNING_TIME_ATTRIBUTE,
		  
		  
		  TS_DECODE_ERROR,
		  
		  //Timestamp Certificate Checker
		  TS_CERTIFICATE_NOT_FOUND,
		  TS_CERTIFICATE_NOT_QUALIFIED,
		  
		  //TimestampedCertsCrlsRefsAttrChecker
		  TIMESTAMPED_CERTS_CRLS_REFS_ATTRIBUTE_NOT_FOUND,
		  TIMESTAMPED_CERTS_CRLS_REFS_ATTRIBUTE_DECODE_ERROR,
		  TIMESTAMPED_CERTS_CRLS_REFS_ATTRIBUTE_CHECKER_SUCCESSFUL,
		  TIMESTAMPED_CERTS_CRLS_REFS_ATTRIBUTE_CHECKER_UNSUCCESSFUL,
		  
		  
		  //TimestampMessageDigest Checker
		  TS_MESSAGE_DIGEST_CHECKER_DECODE_ERROR,
		  TS_MESSAGE_DIGEST_CHECKER_DIGEST_CALCULATION_ERROR,
		  TS_MESSAGE_DIGEST_CHECKER_SUCCESSFUL,
		  TS_MESSAGE_DIGEST_CHECKER_UNSUCCESSFUL,
		  
		  //TimestampSignatureChecker
		  TS_SIGNATURE_CHECKER_SUCCESSFUL,
		  TS_SIGNATURE_CHECKER_UNSUCCESSFUL,
		  		  
		  //TimestampTimeChecker
		  TS_TIME_CHECKER_SIGNATURE_TS_NOT_FOUND,
		  TS_TIME_CHECKER_TIME_ERROR,
		  TS_TIME_CHECKER_COMPARISON_ERROR,
		  TS_TIME_CHECKER_ARCHIVE_BEFORE_EST,
		  TS_TIME_CHECKER_ARCHIVE_BEFORE_ESC,
		  TS_TIME_CHECKER_ARCHIVE_BEFORE_REFS,
		  TS_TIME_CHECKER_SUCCESSFUL,
		  TS_TIME_CHECKER_UNSUCCESSFUL,
		  
		  //SigningCertificate Attribute Checker
		  SIGNING_CERTIFICATE_DECODE_ERROR,
		  ISSUER_SERIAL_DOESNOT_MATCH_SIGNER_IDENTIFIER,
		  CERT_HASH_DOESNOT_MATCH,
		  SIGNING_CERTIFICATE_ATTRIBUTE_CHECK_SUCCESSFUL,
		  SIGNING_CERTIFICATE_ATTRIBUTE_HASH_CALCULATION_ERROR,
		  ISSUER_SERIAL_DOESNOT_EXISTS,
		  		  
		  //ParentSignatureChecker
		  PARENT_SIGNATURE_INVALID,
		  PARENT_SIGNATURE_VALID,
		  
		  //ProfileRevocationValueMatcherChecker
		  PROFILE_REVOCATION_VALUE_MATCHER_CHECKER_SUCCESSFUL,
		  PROFILE_REVOCATION_VALUE_MATCHER_CHECKER_UNSUCCESSFUL,
	      PROFILE_AND_SIGNATURE_TYPE_MATCH_UNSUCCESSFUL,
	      PROFILE_P3_DOESNOT_USE_CRL,
	      PROFILE_P4_DOESNOT_USE_OCSP,

		  //TurkishProfileAttributesChecker
		  TURKISH_PROFILE_ATTRIBUTES_CHECKER_SUCCESSFUL,
		  NOT_A_TURKISH_PROFILE,
		  PROFILE_POLICY_HASH_NOT_SHA256,
		  SIGNING_TIME_ATTRIBUTE_MISSING,
		  SIGNING_CERTIFICATE_V2_ATTRIBUTE_MISSING,
		  TS_TIME_NOT_AFTER_2H,
		  SIGNATURE_TIME_ERROR,
		 
		  //ATSHashIndexAttrChecker
		  ATS_HASH_INDEX_ATTRIBUTE_CHECKER_SUCCESSFUL,
		  UNSIGNED_ATTRIBUTE_NOT_INCLUDED,
		  UNSIGNED_ATTRIBUTE_MISSING,

		  
		  //Attributes
		  UNKNOWN_COMMITMENT_TYPE,
		  
		  
		  //Checker names
		  ARCHIVE_TIMESTAMP_ATTRIBUTE_CHECKER,
		  ARCHIVE_TIMESTAMP_V2_ATTRIBUTE_CHECKER,
		  ARCHIVE_TIMESTAMP_V3_ATTRIBUTE_CHECKER,		  
		  CADES_C_TIMESTAMP_ATTRIBUTE_CHECKER,
		  CERTIFICATE_VALIDATION_CHECKER,
		  CERTIFICATE_REFERENCES_VALUES_MATCH_CHECKER,
		  CHECK_ALL_CHECKER,
		  CHECK_ONE_CHECKER,
		  CONTENT_TIMESTAMP_ATTRIBUTE_CHECKER,
		  CONTENT_TYPE_ATTRIBUTE_CHECKER,
		  SIGNATURE_CHECKER,
		  MESSAGE_DIGEST_ATTRIBUTE_CHECKER,
		  REVOCATION_REFERENCES_AND_VALUES_MATCH_CHECKER,
		  SIGNATURE_POLICY_ATTRIBUTE_CHECKER,
		  SIGNATURETIMESTAMP_ATTRIBUTE_CHECKER,
		  SIGNING_CERTIFICATE_ATTRIBUTE_CHECKER,
		  SIGNING_CERTIFICATE_V2_ATTRIBUTE_CHECKER,
		  SIGNING_TIME_CHECKER,
		  SIGNING_TIME_EXISTENCE_CHECKER,
		  TIMESTAMP_CERTIFICATE_CHECKER,
		  TIMESTAMPED_CERTS_CRLS_REFS_ATTRIBUTE_CHECKER,
		  TIMESTAMP_MESSAGE_DIGEST_CHECKER,
		  TIMESTAMP_SIGNATURE_CHECKER,
		  TIMESTAMP_TIME_CHECKER,
		  PARENT_SIGNATURE_CHECKER,
		  PROFILE_REVOCATION_VALUE_MATCHER_CHECKER,
		  TURKISH_PROFILE_ATTRIBUTES_CHECKER,
		  ATS_HASH_INDEX_ATTRIBUTE_CHECKER,
		  
		  
		  
		  //SignedDataValidationResult
		  SIGNATURE_CHECKED_RESULTS,
		  SIGNER_CERTIFICATE,
		  
		  
		  //SignatureValidationResult
		  COUNTER_SIGNATURE_VERIFICATION_RESULTS,
		  COUNTER_SIGNATURE_CHECKED,
		  SIGNATURE_CHECKER_RESULTS,
		  PRE_VERIFICATION_DONE,
		  
		  CERTIFICATE_VALIDATION_EXCEPTION,

		  //VALIDATE_TIMESTAMP_WHILE_SIGNING
		  SIGNATURE_TIMESTAMP_INVALID,
		  CADES_C_TIMESTAMP_INVALID,
		  CERTSCRLS_TIMESTAMP_INVALID,
		  ARCHIVE_TIMESTAMP_INVALID,
		  
		  //CheckerResult
		  SUB_CHECKER_RESULTS,
		  
		  CERT_EXPIRED_ERROR_IN_TS,
		  CONTENT_AND_SIGNER_DOESNT_MATCH,
		  EXTERNAL_CONTENT_CANT_ATTACH,
	      CONTENT_NULL,

	      //Pades Signature
		  ONLY_LAST_USER_SIGNATURE_CAN_BE_UPGRADED
}
