/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.6, Date: 20-Feb-2014.
 */
#include "etsiqc.h"
#include "rtsrc/rtPrint.h"
#include "rtxsrc/rtxCommon.h"

void asn1Print_ETSIQC_Iso4217CurrencyCode 
   (const char* name, const ASN1T_ETSIQC_Iso4217CurrencyCode* pvalue)
{
   rtxPrintOpenBrace (name);

   switch (pvalue->t)
   {
      /* numeric */
      case 1:
      {
         rtxPrintIndent ();
         rtxPrintUnsigned ("numeric", pvalue->u.numeric);
         break;
      }
      /* alphabetic */
      case 2:
      {
         rtxPrintIndent ();
         rtxPrintCharStr ("alphabetic", pvalue->u.alphabetic);
         break;
      }
      default:;
   }

   rtxPrintCloseBrace ();
}

void ASN1C_ETSIQC_Iso4217CurrencyCode::Print (const char* name)
{
   asn1Print_ETSIQC_Iso4217CurrencyCode (name, &msgData);
}

void asn1Print_ETSIQC_MonetaryValue 
   (const char* name, const ASN1T_ETSIQC_MonetaryValue* pvalue)
{
   rtxPrintOpenBrace (name);

   asn1Print_ETSIQC_Iso4217CurrencyCode ("currency", &pvalue->currency);

   rtxPrintIndent ();
   rtxPrintInteger ("amount", pvalue->amount);

   rtxPrintIndent ();
   rtxPrintInteger ("exponent", pvalue->exponent);

   rtxPrintCloseBrace ();
}

void ASN1C_ETSIQC_MonetaryValue::Print (const char* name)
{
   asn1Print_ETSIQC_MonetaryValue (name, &msgData);
}

void asn1Print_ETSIQC_QcEuLimitValue 
   (const char* name, const ASN1T_ETSIQC_QcEuLimitValue* pvalue)
{
   asn1Print_ETSIQC_MonetaryValue (name, pvalue);
}

void ASN1C_ETSIQC_QcEuLimitValue::Print (const char* name)
{
   asn1Print_ETSIQC_QcEuLimitValue (name, &msgData);
}

