/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.0.0, Date: 18-Mar-2016.
 */
package tr.gov.tubitak.uekae.esya.asn.cmp;

import com.objsys.asn1j.runtime.*;
import tr.gov.tubitak.uekae.esya.asn.crmf.EncryptedValue;
import tr.gov.tubitak.uekae.esya.asn.crmf.PKIPublicationInfo;

public class CertifiedKeyPair extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      setKey (_cmpRtkey._rtkey);
   }

   public String getAsn1TypeName()  {
      return "CertifiedKeyPair";
   }

   public CertOrEncCert certOrEncCert;
   public EncryptedValue privateKey;  // optional
   public PKIPublicationInfo publicationInfo;  // optional

   public CertifiedKeyPair () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public CertifiedKeyPair (
      CertOrEncCert certOrEncCert_,
      EncryptedValue privateKey_,
      PKIPublicationInfo publicationInfo_
   ) {
      super();
      certOrEncCert = certOrEncCert_;
      privateKey = privateKey_;
      publicationInfo = publicationInfo_;
   }

   /**
    * This constructor is for required elements only.  It sets 
    * all elements to references to the given objects
    */
   public CertifiedKeyPair (
      CertOrEncCert certOrEncCert_
   ) {
      super();
      certOrEncCert = certOrEncCert_;
   }

   public void init () {
      certOrEncCert = null;
      privateKey = null;
      publicationInfo = null;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return certOrEncCert;
         case 1: return privateKey;
         case 2: return publicationInfo;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "certOrEncCert";
         case 1: return "privateKey";
         case 2: return "publicationInfo";
         default: return null;
      }
   }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode certOrEncCert

      if (!_context.expired()) {
         Asn1Tag tag = buffer.peekTag ();
         if (tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 0) ||
             tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 1))
         {
            certOrEncCert = new CertOrEncCert();
            certOrEncCert.decode (buffer, true, elemLen.value);
         }
         else throw new Asn1MissingRequiredException (buffer, "certOrEncCert");
      }
      else throw new Asn1MissingRequiredException (buffer, "certOrEncCert");

      // decode privateKey

      if (_context.matchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 0, elemLen, true)) {
         int offset = buffer.getByteCount();
         privateKey = new EncryptedValue();
         privateKey.decode (buffer, true, elemLen.value);

         int declen = buffer.getByteCount() - offset;
         if (declen != elemLen.value && elemLen.value != Asn1Status.INDEFLEN)
            throw new Asn1InvalidLengthException();

      }

      // decode publicationInfo

      if (_context.matchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 1, elemLen, true)) {
         int offset = buffer.getByteCount();
         publicationInfo = new PKIPublicationInfo();
         publicationInfo.decode (buffer, true, elemLen.value);

         int declen = buffer.getByteCount() - offset;
         if (declen != elemLen.value && elemLen.value != Asn1Status.INDEFLEN)
            throw new Asn1InvalidLengthException();

      }

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 0) ||
             _tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 1))  {
            throw new Asn1SeqOrderException ();
         }
         else  {
            throw new Asn1UnexpectedElementException();
         }

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode publicationInfo

      if (publicationInfo != null) {
         len = publicationInfo.encode (buffer, true);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 1, len);
         _aal += len;
      }

      // encode privateKey

      if (privateKey != null) {
         len = privateKey.encode (buffer, true);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
         _aal += len;
      }

      // encode certOrEncCert

      if (certOrEncCert != null) {
         len = certOrEncCert.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("certOrEncCert");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (certOrEncCert != null) certOrEncCert.print (_out, "certOrEncCert", _level+1);
      if (privateKey != null) privateKey.print (_out, "privateKey", _level+1);
      if (publicationInfo != null) publicationInfo.print (_out, "publicationInfo", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }

}
