/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.0.0, Date: 18-Mar-2016.
 */
package tr.gov.tubitak.uekae.esya.asn.ocsp;

import com.objsys.asn1j.runtime.*;
import tr.gov.tubitak.uekae.esya.asn.x509.AlgorithmIdentifier;

public class Signature extends Asn1Seq {
   private static final long serialVersionUID = 55;
   static {
      setKey (_ocspRtkey._rtkey);
   }

   public String getAsn1TypeName()  {
      return "Signature";
   }

   public AlgorithmIdentifier signatureAlgorithm;
   public Asn1BitString signature;
   public _SeqOfCertificate certs;  // optional

   public Signature () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public Signature (
      AlgorithmIdentifier signatureAlgorithm_,
      Asn1BitString signature_,
      _SeqOfCertificate certs_
   ) {
      super();
      signatureAlgorithm = signatureAlgorithm_;
      signature = signature_;
      certs = certs_;
   }

   /**
    * This constructor is for required elements only.  It sets 
    * all elements to references to the given objects
    */
   public Signature (
      AlgorithmIdentifier signatureAlgorithm_,
      Asn1BitString signature_
   ) {
      super();
      signatureAlgorithm = signatureAlgorithm_;
      signature = signature_;
   }

   public void init () {
      signatureAlgorithm = null;
      signature = null;
      certs = null;
   }

   public int getElementCount() { return 3; }


   public Object getElementValue(int index){
      switch(index)  {
         case 0: return signatureAlgorithm;
         case 1: return signature;
         case 2: return certs;
         default: return null;
      }
   }


   public String getElementName(int index){
      switch(index)  {
         case 0: return "signatureAlgorithm";
         case 1: return "signature";
         case 2: return "certs";
         default: return null;
      }
   }


   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode signatureAlgorithm

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
         signatureAlgorithm = new AlgorithmIdentifier();
         signatureAlgorithm.decode (buffer, true, elemLen.value);
      }
      else throw new Asn1MissingRequiredException (buffer, "signatureAlgorithm");

      // decode signature

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 3, elemLen, false)) {
         signature = new Asn1BitString();
         signature.decode (buffer, true, elemLen.value);
      }
      else throw new Asn1MissingRequiredException (buffer, "signature");

      // decode certs

      if (_context.matchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 0, elemLen, true)) {
         int offset = buffer.getByteCount();
         certs = new _SeqOfCertificate();
         certs.decode (buffer, true, elemLen.value);

         int declen = buffer.getByteCount() - offset;
         if (declen != elemLen.value && elemLen.value != Asn1Status.INDEFLEN)
            throw new Asn1InvalidLengthException();

      }

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.CONS, 16) ||
             _tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 3) ||
             _tag.equals (Asn1Tag.CTXT, Asn1Tag.CONS, 0))  {
            throw new Asn1SeqOrderException ();
         }
         else  {
            throw new Asn1UnexpectedElementException();
         }

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode certs

      if (certs != null) {
         len = certs.encode (buffer, true);
         len += buffer.encodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
         _aal += len;
      }

      // encode signature

      if (signature != null) {
         len = signature.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("signature");

      // encode signatureAlgorithm

      if (signatureAlgorithm != null) {
         len = signatureAlgorithm.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("signatureAlgorithm");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintWriter _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (signatureAlgorithm != null) signatureAlgorithm.print (_out, "signatureAlgorithm", _level+1);
      if (signature != null) signature.print (_out, "signature", _level+1);
      if (certs != null) certs.print (_out, "certs", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }

}
