// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.6.4, Date: 10-Oct-2013.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace tr.gov.tubitak.uekae.esya.asn.x509 {

   public class InhibitAnyPolicy : Asn1Integer {
      static InhibitAnyPolicy ()
      {
         Asn1Type.SetKey2 (_ImplicitValues._rtkey);
      }

      public InhibitAnyPolicy () : base()
      {
      }

      public InhibitAnyPolicy (long value_) : base(value_)
      {
      }

   }
}
