// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.6.4, Date: 10-Oct-2013.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace tr.gov.tubitak.uekae.esya.asn.cmp {

   using Certificate = tr.gov.tubitak.uekae.esya.asn.x509.Certificate;
   using SelfDescCVC = tr.gov.tubitak.uekae.esya.asn.cvc.SelfDescCVC;
   using NonSelfDescCVCwithHeader = tr.gov.tubitak.uekae.esya.asn.cvc.NonSelfDescCVCwithHeader;

   public class OOBCert : CMPCertificate {
      static OOBCert ()
      {
         Asn1Type.SetKey2 (_cmpValues._rtkey);
      }

      public OOBCert () : base()
      {
      }

      public OOBCert (byte choiceId_, Asn1Type element_)
         : base(choiceId_, element_)
      {
      }

   }
}
