#ifndef  __ESYA_AYAR_DIL_DIL_H__
#define  __ESYA_AYAR_DIL_DIL_H__

/**************************** AYAR SINIFLARI İLE İLGİLİ DİL İFADELERİ *****************/
#define DIL_AYAR_SINIF_BASLIK_AcilisIslemleri                         QObject::trUtf8("Açılış İşlemleri")
#define DIL_AYAR_SINIF_ACIKLAMA_AcilisIslemleri                       QObject::trUtf8("Açılışta yapılacak işlemler ile ilgili ayarlar")
#define DIL_AYAR_SINIF_BASLIK_Algoritma                               QObject::trUtf8("Algoritma")
#define DIL_AYAR_SINIF_ACIKLAMA_Algoritma                             QObject::trUtf8("Sistemde kullanılan imzalama ve şifreleme algoritmaları tanımları")
#define DIL_AYAR_SINIF_BASLIK_EPosta                                  QObject::trUtf8("E-Posta")
#define DIL_AYAR_SINIF_ACIKLAMA_EPosta                                QObject::trUtf8("EPosta modülü ile ilgili ayarlar")
#define DIL_AYAR_SINIF_BASLIK_GDM                                     QObject::trUtf8("GDM(Güvenli Dizin Modülü)")
#define DIL_AYAR_SINIF_ACIKLAMA_GDM                                   QObject::trUtf8("GDM ile ilgili ayarlar")
#define DIL_AYAR_SINIF_BASLIK_IslemOzellikleri                        QObject::trUtf8("İşlem Özellikleri")
#define DIL_AYAR_SINIF_ACIKLAMA_IslemOzellikleri                      QObject::trUtf8("İmzalama ve şifreleme işlemleri sırasındaki kullanılan varsayılan seçenekler")
#define DIL_AYAR_SINIF_BASLIK_IstemciRaporlama                        QObject::trUtf8("Durum Raporlama")
#define DIL_AYAR_SINIF_ACIKLAMA_IstemciRaporlama                      QObject::trUtf8("Raporlama ile ilgili sunucu ayarları")
#define DIL_AYAR_SINIF_BASLIK_LOG                                     QObject::trUtf8("Sistem Log")
#define DIL_AYAR_SINIF_ACIKLAMA_LOG                                   QObject::trUtf8("Log ayarları")
#define DIL_AYAR_SINIF_BASLIK_MGM                                     QObject::trUtf8("MGM(Masaüstü Güvenlik Modülü)")
#define DIL_AYAR_SINIF_ACIKLAMA_MGM                                   QObject::trUtf8("MGM(Masaüstü Güvenlik Modülü) ile ilgili ayarlar")
#define DIL_AYAR_SINIF_BASLIK_Parola                                  QObject::trUtf8("Parola Seçenekleri")
#define DIL_AYAR_SINIF_ACIKLAMA_Parola                                QObject::trUtf8("Parola ile ilgili ayarlar")
#define DIL_AYAR_SINIF_BASLIK_SertifikaDeposu                         QObject::trUtf8("Sertifika Deposu")
#define DIL_AYAR_SINIF_ACIKLAMA_SertifikaDeposu                       QObject::trUtf8("Sertifika Deposu ayarları")
#define DIL_AYAR_SINIF_BASLIK_SertifikaDogrulama                      QObject::trUtf8("Sertifika Doğrulama")
#define DIL_AYAR_SINIF_ACIKLAMA_SertifikaDogrulama                    QObject::trUtf8("Sertifika Doğrulama parametreleri")
#define DIL_AYAR_SINIF_BASLIK_SertifikaYardimcisi                     QObject::trUtf8("Sertifika Yardımcısı")
#define DIL_AYAR_SINIF_ACIKLAMA_SertifikaYardimcisi                   QObject::trUtf8("Sertifika yardımcısında kullanılan ayarlar")
#define DIL_AYAR_SINIF_BASLIK_ZamanDamgasi                            QObject::trUtf8("Zaman Damgası")
#define DIL_AYAR_SINIF_ACIKLAMA_ZamanDamgasi                          QObject::trUtf8("Zaman Damgası eklenirken kullanılacak ayarlar")
#define DIL_AYAR_SINIF_BASLIK_DosyaBul                                QObject::trUtf8("Dosya Bul")
#define DIL_AYAR_SINIF_ACIKLAMA_DosyaBul                              QObject::trUtf8("Dosya Bul ekranı ile ilgili ayarlar")
/****************************************************************************************/


/**************************** AYAR BASLIK VE ACIKLAMALARI İLE İLGİLİ DİL İFADELERİ *****************/
#define DIL_AYAR_BASLIK_EskimeSuresi                                  QObject::trUtf8("Parola eskime süresi (gün)")
#define DIL_AYAR_ACIKLAMA_EskimeSuresi                                QObject::trUtf8("Kart parolasının kaç gün sonra değiştirilmek zorunda oluğunu belirtir.")
#define DIL_AYAR_BASLIK_DegisimZorunlu                                QObject::trUtf8("Parola değiştirme zorunlu")
#define DIL_AYAR_ACIKLAMA_DegisimZorunlu                              QObject::trUtf8("Süresi biten parolayı değiştirmenin zorunlu olup olmadığını belirtir.")
#define DIL_AYAR_BASLIK_ParolaPrensibi                                QObject::trUtf8("Parola Prensibi")
#define DIL_AYAR_ACIKLAMA_ParolaPrensibi                              QObject::trUtf8("Parola belirlemede kullanılacak parola prensibini belirtir.")
#define DIL_AYAR_BASLIK_EskimeOncesiHaberVermeSuresi                  QObject::trUtf8("Parola Eskime Öncesi Haber Verme Süresi (Gün)")
#define DIL_AYAR_ACIKLAMA_EskimeOncesiHaberVermeSuresi                QObject::trUtf8("Parolanın bitmesine kaç gün kala kullanıcının uyarılacağını belirtir.")
#define DIL_AYAR_BASLIK_SunucuIP                                      QObject::trUtf8("Sunucu IP")
#define DIL_AYAR_ACIKLAMA_SunucuIP                                    QObject::trUtf8("İstemci Raporlama IP Adresi")
#define DIL_AYAR_BASLIK_SucunuPort                                    QObject::trUtf8("Sunucu Port")
#define DIL_AYAR_ACIKLAMA_SucunuPort                                  QObject::trUtf8("İstemci Raporlama IP Portu")
#define DIL_AYAR_BASLIK_RaporlamaNesnesi                              QObject::trUtf8("Raporlama Nesnesi Adı")
#define DIL_AYAR_ACIKLAMA_RaporlamaNesnesi                            QObject::trUtf8("İstemci Raporlama nesnesi (Servlet Dİzini/Servlet adı)")
#define DIL_AYAR_BASLIK_EtkinEnable                                   QObject::trUtf8("GDM Etkin yada Pasif hale getirilebilsin mi")
#define DIL_AYAR_ACIKLAMA_EtkinEnable                                 QObject::trUtf8("GDM'nin kullanıcı tarafından etkin yada pasif hale getirilip getirilmeyeceğini belirtmek için kullanılır.")
#define DIL_AYAR_BASLIK_CikisEnable                                   QObject::trUtf8("GDM Kapatılabilir mi")
#define DIL_AYAR_ACIKLAMA_CikisEnable                                 QObject::trUtf8("GDM'nin kapatılıp kapatılamayacağını belirtmek için kullanılır.")
#define DIL_AYAR_BASLIK_SecenekEnable                                 QObject::trUtf8("Seçenekler değiştirilebilsin mi")
#define DIL_AYAR_ACIKLAMA_SecenekEnable                               QObject::trUtf8("GDM Seçeneklerinin kullanıcı tarafından değiştirilip değiştirilemeyeceğini ayarlamak için kullanılır.")
#define DIL_AYAR_BASLIK_MessageBoxDelay                               QObject::trUtf8("Mesaj kutusunu ekranda zorunlu olarak tutulma süresi")
#define DIL_AYAR_ACIKLAMA_MessageBoxDelay                             QObject::trUtf8("Mesaj kutusunun ekranda bekleme süresini belirtir.")
#define DIL_AYAR_BASLIK_DizinlerDinlensin                             QObject::trUtf8("Dizinler Dinlensin")
#define DIL_AYAR_ACIKLAMA_DizinlerDinlensin                           QObject::trUtf8("GDM Dizinleri dinlensin mi")
#define DIL_AYAR_BASLIK_TempDizinYolu                                 QObject::trUtf8("Geçici dizin yolu")
#define DIL_AYAR_ACIKLAMA_TempDizinYolu                               QObject::trUtf8("İşlemlerde geçici dosyaların saklanması için kullanılacak dizin yolunu belirtir.")
#define DIL_AYAR_BASLIK_AttributeKoru                                 QObject::trUtf8("Özellik Koru")
#define DIL_AYAR_ACIKLAMA_AttributeKoru                               QObject::trUtf8("İşlemler sonrasında dosya özelliklerinin korunup korunmayacağını belirtir.")
#define DIL_AYAR_BASLIK_GuvenliDizindeOlustur                         QObject::trUtf8("Güvenli Dizinde Oluştur")
#define DIL_AYAR_ACIKLAMA_GuvenliDizindeOlustur                       QObject::trUtf8("İşlemler sonucunda dosya kullanıcı güvenli dizininde mi oluşturulsun")
#define DIL_AYAR_BASLIK_SonucDialogGoster                             QObject::trUtf8("Sonuç ekranını göster")
#define DIL_AYAR_ACIKLAMA_SonucDialogGoster                           QObject::trUtf8("Masaüstü işlemlerinden sonra sonuç ekranının gösterilip gösterilmeyeceğini belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_DosyaSecenekleriGoster                        QObject::trUtf8("İmzalama seçeneklerini göster")
#define DIL_AYAR_ACIKLAMA_DosyaSecenekleriGoster                      QObject::trUtf8("İmzalama ve imzalama/şifreleme işlemlerinde seçeneklerin gösterilip gösterilmeyeceğini belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_EkranKoruyucuSuresi                           QObject::trUtf8("Ekran koruyucu devreye giriş süresi")
#define DIL_AYAR_ACIKLAMA_EkranKoruyucuSuresi                         QObject::trUtf8("Ekran koruyunun devreye girme süresini ayarlamak için kullanılır.")
#define DIL_AYAR_BASLIK_DurumGoster                                   QObject::trUtf8("İşlem durumu göster")
#define DIL_AYAR_ACIKLAMA_DurumGoster                                 QObject::trUtf8("İşlemlerde işlem durumunun gösterilip gösterilmeyeceğini belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_SimSifAlg                                     QObject::trUtf8("Simetrik Şifreleme Algoritması")
#define DIL_AYAR_ACIKLAMA_SimSifAlg                                   QObject::trUtf8("Simetrik Şifreleme Algoritması")
#define DIL_AYAR_BASLIK_ImzOzetAlg                                    QObject::trUtf8("İmzalama Özet Algoritması")
#define DIL_AYAR_ACIKLAMA_ImzOzetAlg                                  QObject::trUtf8("İmzalama Özet Algoritması")
#define DIL_AYAR_BASLIK_WebSMAdresi                                   QObject::trUtf8("Web SM Adresi")
#define DIL_AYAR_ACIKLAMA_WebSMAdresi                                 QObject::trUtf8("Bilinmeyen sertifikaların aranacağı sunucu adresi.")
#define DIL_AYAR_BASLIK_VarsayilanDizin                               QObject::trUtf8("Varsayılan Dizin Adı")
#define DIL_AYAR_ACIKLAMA_VarsayilanDizin                             QObject::trUtf8("Kullanıcı sertifika deposu varsayılan dizin adını belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_LogDizinYolu                                  QObject::trUtf8("Log Dosyası")
#define DIL_AYAR_ACIKLAMA_LogDizinYolu                                QObject::trUtf8("Log dosya yeri")
#define DIL_AYAR_BASLIK_LogEsikDegeri                                 QObject::trUtf8("Log Eşik Değeri")
#define DIL_AYAR_ACIKLAMA_LogEsikDegeri                               QObject::trUtf8("Log eşik değerini belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_SecureDizinYolu                               QObject::trUtf8("Güvenli Dizin Yolu")
#define DIL_AYAR_ACIKLAMA_SecureDizinYolu                             QObject::trUtf8("Kullanıcı geçici güvenli dizin yolunu belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_IsOverride                                    QObject::trUtf8("Üzerine Yaz")
#define DIL_AYAR_ACIKLAMA_IsOverride                                  QObject::trUtf8("Varsayılan olarak hedef dosyanın üzerine yazılıp yazılmayacağını belirtir.")
#define DIL_AYAR_BASLIK_AltDizinlerideKontrolEt                       QObject::trUtf8("Alt dizinleri kontrol et")
#define DIL_AYAR_ACIKLAMA_AltDizinlerideKontrolEt                     QObject::trUtf8("İşlemlerde alt dizinlerin kontrol edilip edilmeyeceğini belirtmek için kullanılır.")
#define DIL_AYAR_BASLIK_PBESifAlg                                     QObject::trUtf8("Parola tabanlı şifreleme algoritması")
#define DIL_AYAR_ACIKLAMA_PBESifAlg                                   QObject::trUtf8("Parola tabanlı şifreleme algoritması")
#define DIL_AYAR_BASLIK_VarsayilanDizinTipi                           QObject::trUtf8("Varsayılan dizin tipi")
#define DIL_AYAR_ACIKLAMA_VarsayilanDizinTipi                         QObject::trUtf8("Varsayılan dizin tipini belirtmek için kullanılır.")
#define DIL_AYAR_BASLIK_VarsayilanOzneSecimTipi                       QObject::trUtf8("Varsayılan Özne Seçim Tipi")
#define DIL_AYAR_ACIKLAMA_VarsayilanOzneSecimTipi                     QObject::trUtf8("Varsayılan özne seçim tipini belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_RegisterImages                                QObject::trUtf8("Resim dosyaları için ilişkili uygulamayı değiştir")
#define DIL_AYAR_ACIKLAMA_RegisterImages                              QObject::trUtf8("Resim dosyaları için ilişkili uygulamayı değiştir")
#define DIL_AYAR_BASLIK_ImageTypes                                    QObject::trUtf8("İlişkili uygulaması değiştirilecek resim tipleri")
#define DIL_AYAR_ACIKLAMA_ImageTypes                                  QObject::trUtf8("İlişkili uygulaması değiştirilecek resim tipleri")
#define DIL_AYAR_BASLIK_ImageViewer2003                               QObject::trUtf8("Office 2003 kurulu ise ilişkilendirilecek uygulama")
#define DIL_AYAR_ACIKLAMA_ImageViewer2003                             QObject::trUtf8("Office 2003 kurulu ise ilişkilendirilecek uygulama")
#define DIL_AYAR_BASLIK_ImageViewerOther                              QObject::trUtf8("Başka Office versiyonu kurulu ise ilişkilendirilecek uygulama")
#define DIL_AYAR_ACIKLAMA_ImageViewerOther                            QObject::trUtf8("Başka Office versiyonu kurulu ise ilişkilendirilecek uygulama")
#define DIL_AYAR_BASLIK_VarsayilanGuvenlikSeviyesi                    QObject::trUtf8("Varsayılan güvenlik seviyesi")
#define DIL_AYAR_ACIKLAMA_VarsayilanGuvenlikSeviyesi                  QObject::trUtf8("Varsayılan güvenlik seviyesi")
#define DIL_AYAR_BASLIK_KendineSifrele                                QObject::trUtf8("EPosta gönderirken kendine şifrele")
#define DIL_AYAR_ACIKLAMA_KendineSifrele                              QObject::trUtf8("EPosta gönderirken kendine şifrele")
#define DIL_AYAR_BASLIK_GuvenlikSeviyesi                              QObject::trUtf8("Güvenlik Seviyesi ayarları")
#define DIL_AYAR_ACIKLAMA_GuvenlikSeviyesi                            QObject::trUtf8("Herbir güvenlik seviyesi için epostanın imzalı mı şifreli mi gönderileceğini ve değişiklik yapılıp yapılamayacağını belirtir.")
#define DIL_AYAR_BASLIK_WebSertifikaSaglayiciAdres                    QObject::trUtf8("Web Sertifika Sağlayıcı Adresi")
#define DIL_AYAR_ACIKLAMA_WebSertifikaSaglayiciAdres                  QObject::trUtf8("Sertifika yardımcısındaki kullanılan sertifika alma sayfasının adresini belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_HizmeteOzelSimSifAlg                          QObject::trUtf8("Hizmete Özel-Simetrik Şifreleme Algoritması")
#define DIL_AYAR_ACIKLAMA_HizmeteOzelSimSifAlg                        QObject::trUtf8("Hizmete Özel EPostaların Simetrik şifreleme Algoritması")
#define DIL_AYAR_BASLIK_OzelImzOzetAlg                                QObject::trUtf8("Özel-İmzalama Özet Algoritması")
#define DIL_AYAR_ACIKLAMA_OzelImzOzetAlg                              QObject::trUtf8("Özel dereceli epostalarda kullanılacak imzalama özet algoritması")
#define DIL_AYAR_BASLIK_GizliSimSifAlg                                QObject::trUtf8("Gizli-Simetrik Şifreleme Algoritması")
#define DIL_AYAR_ACIKLAMA_GizliSimSifAlg                              QObject::trUtf8("Gizli dereceli epostalarda kullanılacak simetrik şifreleme kullanılacak olan algoritma")
#define DIL_AYAR_BASLIK_OzelSimSifAlg                                 QObject::trUtf8("Özel-Simetrik Şifreleme Algoritması")
#define DIL_AYAR_ACIKLAMA_OzelSimSifAlg                               QObject::trUtf8("Özel dereceli epostalarda kullanılacak simetrik şifreleme kullanılacak olan algoritma")
#define DIL_AYAR_BASLIK_TasnifDisiSimSifAlg                           QObject::trUtf8("Tasnif Dışı-Simetrik Şifreleme Algoritması")
#define DIL_AYAR_ACIKLAMA_TasnifDisiSimSifAlg                         QObject::trUtf8("Tasnif Dışı dereceli epostalarda kullanılacak simetrik şifreleme kullanılacak olan algoritma")
#define DIL_AYAR_BASLIK_GizliImzOzetAlg                               QObject::trUtf8("Gizli-İmzalama Özet Algoritması")
#define DIL_AYAR_ACIKLAMA_GizliImzOzetAlg                             QObject::trUtf8("Gizli dereceli epostalarda kullanılacak imzalama özet algoritması")
#define DIL_AYAR_BASLIK_HizmeteOzelImzOzetAlg                         QObject::trUtf8("Hizmete Özel-İmzalama Özet Algoritması")
#define DIL_AYAR_ACIKLAMA_HizmeteOzelImzOzetAlg                       QObject::trUtf8("Hizmete Özeli dereceli epostalarda kullanılacak imzalama özet algoritması")
#define DIL_AYAR_BASLIK_TasnifDisiImzOzetAlg                          QObject::trUtf8("Tasnif Dışı-İmzalama Özet Algoritması")
#define DIL_AYAR_ACIKLAMA_TasnifDisiImzOzetAlg                        QObject::trUtf8("Tasnif Dışı dereceli epostalarda kullanılacak imzalama özet algoritması")
#define DIL_AYAR_BASLIK_SertifikaKontroluYap                          QObject::trUtf8("Açılışta Kullanıcı Sertifika Kontrolü Yapılsın")
#define DIL_AYAR_ACIKLAMA_SertifikaKontroluYap                        QObject::trUtf8("Açılışta sertifika kontrollerinin yapılıp yapılmayacağını belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_KullaniciDurumuRaporla                        QObject::trUtf8("Açılışta Kullanıcı Durumunu Raporla")
#define DIL_AYAR_ACIKLAMA_KullaniciDurumuRaporla                      QObject::trUtf8("Açılışta kullanıcının kullandığı versiyon,sertifika bilgisini raporlama işleminin yapılıp yapılmayacağını belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_UyariMesajiBeklemeSuresi                      QObject::trUtf8("İşlemlerdeki uyarı mesajı bekleme süresi (Saniye)")
#define DIL_AYAR_ACIKLAMA_UyariMesajiBeklemeSuresi                    QObject::trUtf8("Uyarı mesajı bekleme süresi")
#define DIL_AYAR_BASLIK_SertifikaBitmeyeYakinHaberVermeSuresi         QObject::trUtf8("Sertifika geçerliliğinin bitmesine yakın haber verme süresi (Gün)")
#define DIL_AYAR_ACIKLAMA_SertifikaBitmeyeYakinHaberVermeSuresi       QObject::trUtf8("Kullanıcının sertifikalarının süresinin sona ermesine kaç gün kala uyarı verilmeye başlanacağını belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_ProgramDili                                   QObject::trUtf8("Kermen çalışma dili")
#define DIL_AYAR_ACIKLAMA_ProgramDili                                 QObject::trUtf8("Kermen programının çalısma dilini belirlemek için kullanılır.")
#define DIL_AYAR_BASLIK_MaximumLogDosyaBoyutu                         QObject::trUtf8("Maksimum Log Dosya Boyutu (MB)")
#define DIL_AYAR_ACIKLAMA_MaximumLogDosyaBoyutu                       QObject::trUtf8("Log dosyasının maksimum boyutunu belirler")
#define DIL_AYAR_BASLIK_CevrimdisiCalis                               QObject::trUtf8("Çevrimdışı çalış")
#define DIL_AYAR_ACIKLAMA_CevrimdisiCalis                             QObject::trUtf8("Istemci calisirken sertifika dogrulamasi ve SIL kontrolu yapılıp yapılmayacagını belirtir")
#define DIL_AYAR_BASLIK_ParolaSakla                                   QObject::trUtf8("Parolayı Sakla")
#define DIL_AYAR_ACIKLAMA_ParolaSakla                                 QObject::trUtf8("Kermenle çalışırken parolanın saklanıp saklanmayacağını belirtir.")
#define DIL_AYAR_BASLIK_MailZamanDamgaliGonder                        QObject::trUtf8("Zaman Damgası Ekle")
#define DIL_AYAR_ACIKLAMA_MailZamanDamgaliGonder                      QObject::trUtf8("Gönderilecek epostalara zaman damgası eklenip eklenmeyeceğini belirtir")
#define DIL_AYAR_BASLIK_SunucuIP                                      QObject::trUtf8("Sunucu IP")
#define DIL_AYAR_ACIKLAMA_SunucuIP                                    QObject::trUtf8("Zaman damgası sunucusu IP adresi")
#define DIL_AYAR_BASLIK_SunucuPort                                    QObject::trUtf8("Sunucu Port")
#define DIL_AYAR_ACIKLAMA_SunucuPort                                  QObject::trUtf8("Zaman damgası sunucusu port numarası")
#define DIL_AYAR_BASLIK_VekilSunucuIP                                 QObject::trUtf8("Vekil Sunucu IP")
#define DIL_AYAR_ACIKLAMA_VekilSunucuIP                               QObject::trUtf8("Vekil Zaman damgası sunucusu IP adresi")
#define DIL_AYAR_BASLIK_VekilSunucuPort                               QObject::trUtf8("Vekil Sunucu Port")
#define DIL_AYAR_ACIKLAMA_VekilSunucuPort                             QObject::trUtf8("Vekil Zaman damgası sunucusu Port adresi")
#define DIL_AYAR_BASLIK_KullaniciNo                                   QObject::trUtf8("Kullanıcı Numarası")
#define DIL_AYAR_ACIKLAMA_KullaniciNo                                 QObject::trUtf8("Zaman damgasi sunucusu kullanıcı adı")
#define DIL_AYAR_BASLIK_Parola                                        QObject::trUtf8("Kullanıcı Parolası")
#define DIL_AYAR_ACIKLAMA_Parola                                      QObject::trUtf8("Zaman damgasi sunucusu kullanıcı parolası")
#define DIL_AYAR_BASLIK_OzetAlgoritmasi                               QObject::trUtf8("İstek Özet Algoritması")
#define DIL_AYAR_ACIKLAMA_OzetAlgoritmasi                             QObject::trUtf8("Zaman damgası isteği gönderilirken kullanılacak özet algoritması")
#define DIL_AYAR_BASLIK_OrtakDizinTipi                                QObject::trUtf8("Ortak Dizin Tipi")
#define DIL_AYAR_ACIKLAMA_OrtakDizinTipi                              QObject::trUtf8("Ortak dizinin tipini belirtir. 0 ise lokaldeki ortak dizini,1 ise server üzerindeki ortak dizini ifade eder.")
#define DIL_AYAR_BASLIK_OrtakDizinAdi                                 QObject::trUtf8("Ortak Dizin Adı")
#define DIL_AYAR_ACIKLAMA_OrtakDizinAdi                               QObject::trUtf8("Ortak Dizinin adı")
#define DIL_AYAR_BASLIK_OrtakDizinSunucuYolu                          QObject::trUtf8("Ortak Dizin Sunucusu")
#define DIL_AYAR_ACIKLAMA_OrtakDizinSunucuYolu                        QObject::trUtf8("Ortak Dizinlerin bulunduğu dosya sunucusunun yolu")
#define DIL_AYAR_BASLIK_SubeOrtakAdi                                  QObject::trUtf8("Şube Ortak Dizini")
#define DIL_AYAR_ACIKLAMA_SubeOrtakAdi                                QObject::trUtf8("Şube ortak dizinin adı")
#define DIL_AYAR_BASLIK_AramaKriterLDAPAlanAdi                        QObject::trUtf8("Arama LDAP alanı")
#define DIL_AYAR_ACIKLAMA_AramaKriterLDAPAlanAdi                      QObject::trUtf8("Dosya bulma sırasında kullanıcının aranacağı alanın adı")
#define DIL_AYAR_BASLIK_VarsayilanKullaniciTipi                       QObject::trUtf8("Kullanıcı Tipi")
#define DIL_AYAR_ACIKLAMA_VarsayilanKullaniciTipi                     QObject::trUtf8("Kartlı kullanıcı = 0,PFX li kullanıcı =1")
#define DIL_AYAR_BASLIK_AltDizinlereUygula                            QObject::trUtf8("Alt dizinlere uygula")
#define DIL_AYAR_ACIKLAMA_AltDizinlereUygula                          QObject::trUtf8("İşlem yaparken alt dizinlere uygula")
#define DIL_AYAR_BASLIK_ServisMaxSorguBuyukluk                        QObject::trUtf8("Max sorgu eleman sayısı")
#define DIL_AYAR_ACIKLAMA_ServisMaxSorguBuyukluk                      QObject::trUtf8("LDAP sorgularında kaçar kaçar eleman çekileceği")
#define DIL_AYAR_BASLIK_GuvenliDizinEnable                            QObject::trUtf8("Güvenli Dizin ayarları değiştirebilsin mi")
#define DIL_AYAR_ACIKLAMA_GuvenliDizinEnable                          QObject::trUtf8("Güvenli Dizin ayarları kullanıcı tarafından değiştirilebilemeyeceğini belirtir.")
#define DIL_AYAR_BASLIK_KullaniciyaSertifikaSectir                    QObject::trUtf8("Sertifika Seçtir")
#define DIL_AYAR_ACIKLAMA_KullaniciyaSertifikaSectir                  QObject::trUtf8("Kullanıcının birden fazla sertifikası bulunursa kullanıcıya seçtir.")
/****************************************************************************************/

#endif
