#ifndef ORTAKLIBRARY_GLOBAL_H
#define ORTAKLIBRARY_GLOBAL_H

#include <Qt/qglobal.h>

#ifdef ORTAKLIBRARY_LIB
# define ORTAKLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define ORTAKLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // ORTAKLIBRARY_GLOBAL_H
