#ifndef _PERFORMANS_OLCUMLERI_H_
#define _PERFORMANS_OLCUMLERI_H_

#define PERFORMANS_ASIMETRIK_SIFRELEME "Performans_Asimetrik_Sifreleme"
#define PERFORMANS_ASIMETRIK_SIFRECI_EKLEME "Performans_Asimetrik_Sifreci_Ekleme"
#define PERFORMANS_IMZALAMA "Performans_Imzalama"
#define PERFORMANS_IMZA_DOGRULAMA "Performans_Imza_Dogrulama"
#define PERFORMANS_SIFRE_COZME "Performans_Sifre_Cozme"

#define PERFORMANS_PBE_SIFRELEME "Performans_PBE_Sifreleme"
#define PERFORMANS_PBE_SIFRE_COZME "Performans_PBE_Sifre_Cozme"
#define PERFORMANS_Eski_PBE_SIFRE_COZME "Performans_Eski_PBE_Sifre_Cozme"

#define PERFORMANS_IMZALA_SIFRELE "Performans_Imzala_Sifrele"
#define PERFORMANS_SIFRE_COZ_IMZA_DOGRULA "Performans_Sifre_Coz_Imzala"

#define PERFORMANS_SERTIFIKA_DOGRULAMA "Performans_Sertifika_Dogrulama"

#define PERFORMANS_DEPO_LDAP_SERTIFIKA_BULMA "Performans_Depo_LDAP_Sertifika_Bulma"
#define PERFORMANS_DEPODAN_SERTIFIKA_BULMA "Performans_Depodan_Sertifika_Bulma"
#define PERFORMANS_LDAPTAN_SERTIFIKA_BULMA "Performans_LDAPtan_Sertifika_Bulma"

#define PERFORMANS_DEPOYA_SERTIFIKA_EKLEME "Performans_Depoya_Sertifika_Ekleme"
#define PERFORMANS_GRUP_ELEMAN_SERTIFIKA_BULMA "Performans_Grup_Eleman_Sertifika_Bulma"
#define PERFORMANS_GRUP_ELEMAN_LDAP_MAIL_BULMA "Performans_Grup_Eleman_LDAP_Mail_Bulma"

#define PERFORMANS_ALT_DOSYA_ISLEMI "Performans_Alt_Dosya_Islemi"

#define PERFORMANS_KARTTA_OTURUM_ACMA "Performans_Kartta_Oturum_Acma"
#define PERFORMANS_KART_DOLU_SLOT_LISTESI_GETIRME "Performans_Kart_Dolu_Slot_Listesini_Getirme"
#define PERFORMANS_KART_SERI_NUMARASI_ALMA "Performans_Kart_Seri_Numarasý_Alma"

#define PERFORMANS_KRIPTO_SIFRELEME "Performans_Kripto_Sifreleme"

#define PERFORMANS_KRIPTO_EPOSTA_GONDERME "Performans_EPosta_Gonderme"
#define PERFORMANS_KRIPTO_EPOSTA_ACMA_GORUNTULEME "Performans_EPosta_Acma_Goruntuleme"

#define PERFORMANS_KRIPTO_EPOSTA_DOSYAYA_KAYDETME "Performans_EPosta_Dosyaya_Kaydetme"
#define PERFORMANS_KRIPTO_EPOSTA_SERTIFIKA_BULUNMASI "Performans_EPosta_Sertifika_Bulunmasý"
#define PERFORMANS_KRIPTO_EPOSTA_ALICI_DUZENLEME "Performans_EPosta_Alýcý_Duzenleme"
#define PERFORMANS_KRIPTO_EPOSTA_TUM_EKLENTILERI_SILINMESI "Performans_EPosta_Tum_Eklentilerin_Silinmesi"
#define PERFORMANS_KRIPTO_EPOSTA_EKLENTI_EKLENMESI "Performans_EPosta_Tum_Eklenti_Eklenmesi"
#define PERFORMANS_KRIPTO_EPOSTA_OUTLOOK_ACILIS_KONTROLLERI "Performans_Outlook_Acilis_Kontrolleri"

#define PERFORMANS_KERMEN_ACILIS_ISLEMLERI "Performans_Kermen_Acilis_Islemleri"
#define PERFORMANS_KERMEN_ACILIS_ISLEM_ADIMI "Performans_Kermen_Acilis_Islem_Adimi"
#define PERFORMANS_KERMEN_UNINSTALL_ISLEMLERI "Performans_Kermen_Uninstall_Islemleri"


#define PERFORMANS_GUVENLI_COP_KUTUSUNA_ATMA "Performans_Guvenli_Cop_Kutusuna_Atma"
#define PERFORMANS_GUVENLI_SILME "Performans_Guvenli_Silme"
#define PERFORMANS_DOSYA_ISLEM_GECICI_DOSYA_KOPYALAMA "Performans_Dosya_Islem_Gecici_Dosya_Kopyalama"


#define PERFORMANS_XML_LISANS_KONTROLU "Performans_XML_Lisans_Kontrolu"
#define PERFORMANS_DOSYA_BILGISI_GORUNTULEME "Performans_Dosya_Bilgisi_Goruntuleme"
#define PERFORMANS_DOSYA_IMZACI_BILGI_ALMA "Performans_Dosya_Imzaci_Bilgi_Alma"
#define PERFORMANS_DOSYA_SIFRECI_BILGI_ALMA "Performans_Dosya_Sifreci_Bilgi_Alma"

#define PERFORMANS_DOSYA_IMZA_SIFRE_BILGI_SERTIFIKA_BULMA "Performans_Dosya_Imza_Sifre_Bilgi_Bulma"
#define PERFORMANS_DOSYA_IMZA_SIFRE_BILGI_SERTIFIKA_DEPO_SERTIFIKA_BULMA "Performans_Dosya_Imza_Sifre_Bilgi_Sertifika_Depo_Sertifika_Bulma"
#define PERFORMANS_DOSYA_IMZA_SIFRE_BILGI_SBS_SERTIFIKA_BULMA "Performans_Dosya_Imza_Sifre_Bilgi_SBS_Sertifika_Bulma"

#define PERFORMANS_SERTIFIKA_YARDIMCISI_AKTARMA_ONCESI_SERT_KONTROL "Performans_Sertifika_Yardimcisi_Aktarma_Oncesi_Sert_Kontrol"
#define PERFORMANS_SERTIFIKA_YARDIMCISI_FIREFOX_DEPOSUNA_AKTARMA "Performans_Sertifika_Yardimcisi_Firefox_Deposuna_Aktarma"
#define PERFORMANS_SERTIFIKA_YARDIMCISI_MICROSOFT_DEPOSUNA_AKTARMA "Performans_Sertifika_Yardimcisi_Microsoft_Deposuna_Aktarma"
#define PERFORMANS_SERTIFIKA_YARDIMCISI_KARTTAN_MICROSOFT_DEPOSUNA_AKTARMA "Performans_Sertifika_Yardimcisi_Karttan_Microsoft_Deposuna_Aktarma"

#define PERFORMANS_SERTIFIKA_YARDIMCISI_DEPOYA_SERTIFIKA_ANAHTAR_EKLEME "Performans_Sertifika_Yardimcisi_Depoya_Sertifika_Anahtar_Ekleme"
#define PERFORMANS_SERTIFIKA_YARDIMCISI_DEPOYA_SERTIFIKA_KARTBILGISI_EKLEME "Performans_Sertifika_Yardimcisi_Depoya_Sertifika_KartBilgisi_Ekleme"

#define PERFORMANS_SERTIFIKA_YARDIMCISI_KARTTAN_SERTIFIKA_YUKLEME "Performans_Sertifika_Yardimcisi_Karttan_Sertifika_Yukleme"
#define PERFORMANS_SERTIFIKA_YARDIMCISI_PFXDEN_SERTIFIKA_YUKLEME "Performans_Sertifika_Yardimcisi_PFXden_Sertifika_Yukleme"

#define PERFORMANS_SERTIFIKA_YARDIMCISI_PFXDEN_SERTIFIKA_ANAHTAR_OKUMA "Performans_Sertifika_Yardimcisi_PFXden_Sertifika_Anahtar_Okuma"
#define PERFORMANS_SERTIFIKA_YARDIMCISI_KARTTAN_SERTIFIKA_ID_OKUMA "Performans_Sertifika_Yardimcisi_Karttan_Sertifika_ID_Okuma"
#define PERFORMANS_SERTIFIKA_YARDIMCISI_KARTTAN_SERTIFIKA_LABEL_OKUMA "Performans_Sertifika_Yardimcisi_Karttan_Sertifika_Label_Okuma"
#endif


