// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.6.4, Date: 16-Jan-2019.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace tr.gov.tubitak.uekae.esya.asn.cms {
    

   public class AuthEnvelopedData : Asn1Type {
      public CMSVersion version;
      public OriginatorInfo originatorInfo;  // optional
      public RecipientInfos recipientInfos;
      public EncryptedContentInfo authEncryptedContentInfo;
      public AuthAttributes authAttrs;  // optional
      public Asn1OctetString mac;
      public UnauthAttributes unauthAttrs;  // optional

      static AuthEnvelopedData ()
      {
         Asn1Type.SetKey2 (_cmsValues._rtkey);
      }

      public AuthEnvelopedData () : base()
      {
         Init();
      }

      /// <summary>
      /// This constructor sets all elements to references to the 
      /// given objects
      /// </summary>
      public AuthEnvelopedData (
         CMSVersion version_,
         OriginatorInfo originatorInfo_,
         RecipientInfos recipientInfos_,
         EncryptedContentInfo authEncryptedContentInfo_,
         AuthAttributes authAttrs_,
         Asn1OctetString mac_,
         UnauthAttributes unauthAttrs_
      )
         : base ()
      {
         version = version_;
         originatorInfo = originatorInfo_;
         recipientInfos = recipientInfos_;
         authEncryptedContentInfo = authEncryptedContentInfo_;
         authAttrs = authAttrs_;
         mac = mac_;
         unauthAttrs = unauthAttrs_;
      }

      /// <summary>
      /// This constructor is for required elements only.  It sets 
      /// all elements to references to the given objects
      /// </summary>
      public AuthEnvelopedData (
         CMSVersion version_,
         RecipientInfos recipientInfos_,
         EncryptedContentInfo authEncryptedContentInfo_,
         Asn1OctetString mac_
      )
         : base ()
      {
         version = version_;
         recipientInfos = recipientInfos_;
         authEncryptedContentInfo = authEncryptedContentInfo_;
         mac = mac_;
      }

      /// <summary>
      /// This constructor allows primitive data to be passed for all 
      /// primitive elements.  It will create new object wrappers for 
      /// the primitive data and set other elements to references to 
      /// the given objects 
      /// </summary>
      public AuthEnvelopedData (long version_,
         OriginatorInfo originatorInfo_,
         RecipientInfos recipientInfos_,
         EncryptedContentInfo authEncryptedContentInfo_,
         AuthAttributes authAttrs_,
         byte[] mac_,
         UnauthAttributes unauthAttrs_
      )
         : base ()
      {
         version = new CMSVersion (version_);
         originatorInfo = originatorInfo_;
         recipientInfos = recipientInfos_;
         authEncryptedContentInfo = authEncryptedContentInfo_;
         authAttrs = authAttrs_;
         mac = new Asn1OctetString (mac_);
         unauthAttrs = unauthAttrs_;
      }

      /// <summary>
      /// This constructor is for required elements only.  It allows 
      /// primitive data to be passed for all primitive elements.  
      /// It will create new object wrappers for the primitive data 
      /// and set other elements to references to the given objects. 
      /// </summary>
      public AuthEnvelopedData (
         long version_,
         RecipientInfos recipientInfos_,
         EncryptedContentInfo authEncryptedContentInfo_,
         byte[] mac_
      )
         : base ()
      {
         version = new CMSVersion (version_);
         recipientInfos = recipientInfos_;
         authEncryptedContentInfo = authEncryptedContentInfo_;
         mac = new Asn1OctetString (mac_);
      }

      public void Init () {
         version = null;
         originatorInfo = null;
         recipientInfos = null;
         authEncryptedContentInfo = null;
         authAttrs = null;
         mac = null;
         unauthAttrs = null;
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = (explicitTagging) ?
            MatchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

         Init ();

         // decode SEQUENCE

         Asn1BerDecodeContext _context =
            new Asn1BerDecodeContext (buffer, llen);

         IntHolder elemLen = new IntHolder();

         // decode version

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 2, elemLen, false)) {
            version = new CMSVersion();
            version.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode originatorInfo

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 0, elemLen, true)) {
            int offset = buffer.ByteCount;
            originatorInfo = new OriginatorInfo();
            originatorInfo.Decode (buffer, false, elemLen.mValue);
            int declen = buffer.ByteCount - offset;
            if (declen != elemLen.mValue && elemLen.mValue != Asn1Status.INDEFLEN)
               throw new Asn1InvalidLengthException();
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         // decode recipientInfos

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 17, elemLen, false)) {
            recipientInfos = new RecipientInfos();
            recipientInfos.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode authEncryptedContentInfo

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 16, elemLen, false)) {
            authEncryptedContentInfo = new EncryptedContentInfo();
            authEncryptedContentInfo.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode authAttrs

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 1, elemLen, true)) {
            int offset = buffer.ByteCount;
            authAttrs = new AuthAttributes();
            authAttrs.Decode (buffer, false, elemLen.mValue);
            int declen = buffer.ByteCount - offset;
            if (declen != elemLen.mValue && elemLen.mValue != Asn1Status.INDEFLEN)
               throw new Asn1InvalidLengthException();
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         // decode mac

         if (_context.MatchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 4, elemLen, false)) {
            mac = new Asn1OctetString();
            mac.Decode (buffer, true, elemLen.mValue);
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode unauthAttrs

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 2, elemLen, true)) {
            int offset = buffer.ByteCount;
            unauthAttrs = new UnauthAttributes();
            unauthAttrs.Decode (buffer, false, elemLen.mValue);
            int declen = buffer.ByteCount - offset;
            if (declen != elemLen.mValue && elemLen.mValue != Asn1Status.INDEFLEN)
               throw new Asn1InvalidLengthException();
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         if (explicitTagging && llen == Asn1Status.INDEFLEN) {
            MatchTag (buffer, Asn1Tag.EOC);
         }
      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = 0, len;

         // encode unauthAttrs

         if (unauthAttrs != null) {
            len = unauthAttrs.Encode (buffer, false);
            len += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 2, len);
            _aal += len;
         }

         // encode mac

         len = mac.Encode (buffer, true);
         _aal += len;

         // encode authAttrs

         if (authAttrs != null) {
            len = authAttrs.Encode (buffer, false);
            len += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 1, len);
            _aal += len;
         }

         // encode authEncryptedContentInfo

         len = authEncryptedContentInfo.Encode (buffer, true);
         _aal += len;

         // encode recipientInfos

         len = recipientInfos.Encode (buffer, true);
         _aal += len;

         // encode originatorInfo

         if (originatorInfo != null) {
            len = originatorInfo.Encode (buffer, false);
            len += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
            _aal += len;
         }

         // encode version

         len = version.Encode (buffer, true);
         _aal += len;

         if (explicitTagging) {
            _aal += buffer.EncodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
         }

         return (_aal);
      }

      public override void Print (System.IO.TextWriter _out, 
                                  string _varName, int _level)
      {
         Indent (_out, _level);
         _out.WriteLine (_varName + " {");
         if (version != null) version.Print (_out, "version", _level+1);
         if (originatorInfo != null) originatorInfo.Print (_out, "originatorInfo", _level+1);
         if (recipientInfos != null) recipientInfos.Print (_out, "recipientInfos", _level+1);
         if (authEncryptedContentInfo != null) authEncryptedContentInfo.Print (_out, "authEncryptedContentInfo", _level+1);
         if (authAttrs != null) authAttrs.Print (_out, "authAttrs", _level+1);
         if (mac != null) mac.Print (_out, "mac", _level+1);
         if (unauthAttrs != null) unauthAttrs.Print (_out, "unauthAttrs", _level+1);
         Indent (_out, _level);
         _out.WriteLine ("}");
      }
   }
}
