// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.6.4, Date: 10-Oct-2013.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace tr.gov.tubitak.uekae.esya.asn.cms {

   public class SMIMEEncryptionKeyPreference : Asn1Choice {
      // Choice element identifier constants
      public const byte _ISSUERANDSERIALNUMBER = 1;
      public const byte _RECEIPENTKEYID = 2;
      public const byte _SUBJECTALTKEYIDENTIFIER = 3;

      static SMIMEEncryptionKeyPreference ()
      {
         Asn1Type.SetKey2 (_cmsValues._rtkey);
      }

      public SMIMEEncryptionKeyPreference () : base()
      {
      }

      public SMIMEEncryptionKeyPreference (byte choiceId_, Asn1Type element_) : base()
      {
         SetElement (choiceId_, element_);
      }

      public override string ElemName {
         get {
            switch (choiceID) {
            case _ISSUERANDSERIALNUMBER: return "issuerAndSerialNumber";
            case _RECEIPENTKEYID: return "receipentKeyId";
            case _SUBJECTALTKEYIDENTIFIER: return "subjectAltKeyIdentifier";
            default: return "UNDEFINED";
            }
         }
      }

      public void Set_issuerAndSerialNumber (IssuerAndSerialNumber value) {
         SetElement (_ISSUERANDSERIALNUMBER, value);
      }

      public void Set_receipentKeyId (RecipientKeyIdentifier value) {
         SetElement (_RECEIPENTKEYID, value);
      }

      public void Set_subjectAltKeyIdentifier (Asn1OctetString value) {
         SetElement (_SUBJECTALTKEYIDENTIFIER, value);
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = implicitLength;

         // decode CHOICE

         Asn1Tag tag = new Asn1Tag ();
         buffer.Mark ();
         int len = buffer.DecodeTagAndLength (tag);

         if (tag.Equals (Asn1Tag.CTXT, Asn1Tag.CONS, 0))
         {
            IssuerAndSerialNumber issuerAndSerialNumber;
            issuerAndSerialNumber = new IssuerAndSerialNumber();
            issuerAndSerialNumber.Decode (buffer, false, len);
            SetElement (_ISSUERANDSERIALNUMBER, issuerAndSerialNumber);
            if (len == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else if (tag.Equals (Asn1Tag.CTXT, Asn1Tag.CONS, 1))
         {
            RecipientKeyIdentifier receipentKeyId;
            receipentKeyId = new RecipientKeyIdentifier();
            receipentKeyId.Decode (buffer, false, len);
            SetElement (_RECEIPENTKEYID, receipentKeyId);
            if (len == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else if (tag.Equals (Asn1Tag.CTXT, Asn1Tag.PRIM, 2)) {
            Asn1OctetString subjectAltKeyIdentifier;
            subjectAltKeyIdentifier = new Asn1OctetString();
            subjectAltKeyIdentifier.Decode (buffer, false, len);
            SetElement (_SUBJECTALTKEYIDENTIFIER, subjectAltKeyIdentifier);
         }
         else {
            throw new Asn1InvalidChoiceOptionException (buffer, tag);
         }
      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = 0, len;
         switch (choiceID) {
         // encode issuerAndSerialNumber
         case _ISSUERANDSERIALNUMBER:
            IssuerAndSerialNumber issuerAndSerialNumber = (IssuerAndSerialNumber) GetElement();
            len = issuerAndSerialNumber.Encode (buffer, false);
            len += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
            _aal += len;
            break;

         // encode receipentKeyId
         case _RECEIPENTKEYID:
            RecipientKeyIdentifier receipentKeyId = (RecipientKeyIdentifier) GetElement();
            len = receipentKeyId.Encode (buffer, false);
            len += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 1, len);
            _aal += len;
            break;

         // encode subjectAltKeyIdentifier
         case _SUBJECTALTKEYIDENTIFIER:
            Asn1OctetString subjectAltKeyIdentifier = (Asn1OctetString) GetElement();
            len = subjectAltKeyIdentifier.Encode (buffer, false);
            len += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.PRIM, 2, len);
            _aal += len;
            break;

         default:
            throw new Asn1InvalidChoiceOptionException();
         }

         return _aal;
      }

      public override void Print (System.IO.TextWriter _out, 
                                  string _varName, int _level)
      {
         Indent (_out, _level);
         _out.WriteLine (_varName + " {");
         if (element != null) {
            element.Print (_out, ElemName, _level+1);
         }
         Indent (_out, _level);
         _out.WriteLine ("}");
      }
   }
}
