/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 04-Oct-2013.
 */
package tr.gov.tubitak.uekae.esya.asn.signaturepolicies;

import com.objsys.asn1j.runtime.*;

public class SigningPeriod extends Asn1Type {
   private static final long serialVersionUID = 55;
   static {
      setKey (_signaturepoliciesRtkey._rtkey);
   }

   public Asn1GeneralizedTime notBefore;
   public Asn1GeneralizedTime notAfter;  // optional

   public SigningPeriod () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public SigningPeriod (
      Asn1GeneralizedTime notBefore_,
      Asn1GeneralizedTime notAfter_
   ) {
      super();
      notBefore = notBefore_;
      notAfter = notAfter_;
   }

   /**
    * This constructor is for required elements only.  It sets 
    * all elements to references to the given objects
    */
   public SigningPeriod (
      Asn1GeneralizedTime notBefore_
   ) {
      super();
      notBefore = notBefore_;
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public SigningPeriod (String notBefore_,
      String notAfter_
   ) {
      super();
      notBefore = new Asn1GeneralizedTime (notBefore_);
      notAfter = new Asn1GeneralizedTime (notAfter_);
   }

   /**
    * This constructor is for required elements only.  It allows 
    * primitive data to be passed for all primitive elements.  
    * It will create new object wrappers for the primitive data 
    * and set other elements to references to the given objects. 
    */
   public SigningPeriod (
      String notBefore_
   ) {
      super();
      notBefore = new Asn1GeneralizedTime (notBefore_);
   }

   public void init () {
      notBefore = null;
      notAfter = null;
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode notBefore

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 24, elemLen, false)) {
         notBefore = new Asn1GeneralizedTime (true);
         notBefore.decode (buffer, true, elemLen.value);
      }
      else throw new Asn1MissingRequiredException (buffer, "notBefore");

      // decode notAfter

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 24, elemLen, false)) {
         notAfter = new Asn1GeneralizedTime (true);
         notAfter.decode (buffer, true, elemLen.value);
      }

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 24))
            throw new Asn1SeqOrderException ();

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode notAfter

      if (notAfter != null) {
         len = notAfter.encode (buffer, true);
         _aal += len;
      }

      // encode notBefore

      if (notBefore != null) {
         len = notBefore.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("notBefore");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (notBefore != null) notBefore.print (_out, "notBefore", _level+1);
      if (notAfter != null) notAfter.print (_out, "notAfter", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }
}
