/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 04-Oct-2013.
 */
package tr.gov.tubitak.uekae.esya.asn.attrcert;

import com.objsys.asn1j.runtime.*;

public class AttCertValidityPeriod extends Asn1Type {

	private static final long serialVersionUID = 55;
	static {
		setKey(_attrcertRtkey._rtkey);
	}

   public Asn1GeneralizedTime notBeforeTime;
   public Asn1GeneralizedTime notAfterTime;

   public AttCertValidityPeriod () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public AttCertValidityPeriod (
      Asn1GeneralizedTime notBeforeTime_,
      Asn1GeneralizedTime notAfterTime_
   ) {
      super();
      notBeforeTime = notBeforeTime_;
      notAfterTime = notAfterTime_;
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public AttCertValidityPeriod (String notBeforeTime_,
      String notAfterTime_
   ) {
      super();
      notBeforeTime = new Asn1GeneralizedTime (notBeforeTime_);
      notAfterTime = new Asn1GeneralizedTime (notAfterTime_);
   }

   public void init () {
      notBeforeTime = null;
      notAfterTime = null;
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode notBeforeTime

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 24, elemLen, false)) {
         notBeforeTime = new Asn1GeneralizedTime (true);
         notBeforeTime.decode (buffer, true, elemLen.value);
      }
      else throw new Asn1MissingRequiredException (buffer, "notBeforeTime");

      // decode notAfterTime

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 24, elemLen, false)) {
         notAfterTime = new Asn1GeneralizedTime (true);
         notAfterTime.decode (buffer, true, elemLen.value);
      }
      else throw new Asn1MissingRequiredException (buffer, "notAfterTime");

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 24))
            throw new Asn1SeqOrderException ();

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode notAfterTime

      if (notAfterTime != null) {
         len = notAfterTime.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("notAfterTime");

      // encode notBeforeTime

      if (notBeforeTime != null) {
         len = notBeforeTime.encode (buffer, true);
         _aal += len;
      }
      else throw new Asn1MissingRequiredException ("notBeforeTime");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (notBeforeTime != null) notBeforeTime.print (_out, "notBeforeTime", _level+1);
      if (notAfterTime != null) notAfterTime.print (_out, "notAfterTime", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }
}