package tr.gov.tubitak.uekae.esya.api.certificate.validation.check;

import tr.gov.tubitak.uekae.esya.api.certificate.i18n.CertI18n;

/**
 * @author ahmety
 * date: Jan 19, 2010
 */
public enum PathValidationResult
{

    SUCCESS                                 (0, CertI18n.PVR_SUCCESS),

    SERIALNUMBER_NOT_POSITIVE               (1, CertI18n.PVR_SERIALNUMBER_NOT_POSITIVE),
    CERTIFICATE_EXTENSIONS_FAILURE          (2, CertI18n.PVR_CERTIFICATE_EXTENSIONS_FAILURE),
    CERTIFICATE_EXPIRED                     (3, CertI18n.PVR_CERTIFICATE_EXPIRED),
    SIGNATURE_ALGORITHM_DIFFERENT           (4, CertI18n.PVR_SIGNATURE_ALGORITHM_DIFFERENT),
    VERSION_CONTROL_FAILURE                 (5, CertI18n.PVR_VERSION_CONTROL_FAILURE),

    REVOCATION_CONTROL_FAILURE              (6, CertI18n.PVR_REVOCATION_CONTROL_FAILURE),
    CERTIFICATE_REVOKED                     (7, CertI18n.PVR_CERTIFICATE_REVOKED),

    SIGNATURE_CONTROL_FAILURE               (8, CertI18n.PVR_SIGNATURE_CONTROL_FAILURE),
    BASICCONSTRAINTS_FAILURE                (9, CertI18n.PVR_BASICCONSTRAINTS_FAILURE),
    CDP_CONTROL_FAILURE                     (10, CertI18n.PVR_CDP_CONTROL_FAILURE),
    KEYID_CONTROL_FAILURE                   (11, CertI18n.PVR_KEYID_CONTROL_FAILURE),
    NAMECONSTRAINTS_CONTROL_FAILURE         (12, CertI18n.PVR_NAMECONSTRAINTS_FAILURE),
    PATHLENCONSTRAINTS_FAILURE              (13, CertI18n.PVR_PATHLENCONSTRAINTS_FAILURE),
    POLICYCONSTRAINTS_CONTROL_FAILURE       (14, CertI18n.PVR_POLICYCONSTRAINTS_CONTROL_FAILURE),
    KEYUSAGE_CONTROL_FAILURE                (15, CertI18n.PVR_KEYUSAGE_CONTROL_FAILURE),
    NAME_CONTROL_FAILURE                    (16, CertI18n.PVR_NAME_CONTROL_FAILURE),

    CRL_EXPIRED                             (17, CertI18n.PVR_CRL_EXPIRED),
    CRL_EXTENSIONS_CONTROL_FAILURE          (18, CertI18n.PVR_CRL_EXTENSIONS_CONTROL_FAILURE),

    CRL_SIGNATURE_CONTROL_FAILURE           (19, CertI18n.PVR_CRL_SIGNATURE_CONTROL_FAILURE),
    CRL_KEYUSAGE_CONTROL_FAILURE            (20, CertI18n.PVR_CRL_KEYUSAGE_CONTROL_FAILURE),
    CRL_NAME_CONTROL_FAILURE                (21, CertI18n.PVR_CRL_NAME_CONTROL_FAILURE),

    OCSP_RESPONSESTATUS_CONTROL_FAILURE     (22, CertI18n.PVR_OCSP_RESPONSESTATUS_CONTROL_FAILURE),
    OCSP_SIGNATURE_CONTROL_FAILURE          (23, CertI18n.PVR_OCSP_SIGNATURE_CONTROL_FAILURE),
    OCSP_RESPONSEDATE_EXPIRED			    (24, CertI18n.PVR_OCSP_RESPONSEDATE_EXPIRED),
    OCSP_RESPONSEDATE_INVALID			    (25, CertI18n.PVR_OCSP_RESPONSEDATE_INVALID),

    CRL_FRESHESTCRL_CONTROL_FAILURE         (26, CertI18n.PVR_CRL_FRESHESTCRL_CONTROL_FAILURE),
    CRL_DELTACRLINDICATOR_CONTROL_FAILURE   (27, CertI18n.PVR_CRL_DELTACRLINDICATOR_CONTROL_FAILURE),

    POLICYMAPPING_CONTROL_FAILURE           (28, CertI18n.PVR_POLICYMAPPING_CONTROL_FAILURE),

    INVALID_PATH                            (29, CertI18n.PVR_INVALID_PATH),
    INCOMPLETE_VALIDATION                   (30, CertI18n.PVR_INCOMPLETE_VALIDATION),	
   
    QCC_NO_STATEMENT_ID						(31, CertI18n.PVR_QCC_NO_STATEMENT_ID) ,
    QCC_NO_USER_NOTICE                      (32, CertI18n.PVR_QCC_NO_USER_NOTICE),

    EXTENDED_KEYUSAGE_CONTROL_FAILURE       (33, CertI18n.PVR_EXTENDED_KEYUSAGE_CONTROL_FAILURE),
    WRONG_FORMAT_QCC_STATEMENT				(34, CertI18n.WRONG_FORMAT_QCC_STATEMENT)

    ;


    int mCode;
    String mMessageId;

    PathValidationResult(int aCode, String aMessageId)
    {
        mCode = aCode;
        mMessageId = aMessageId;
    }

    public int getCode(){
        return mCode;
    }

    public String getMessage(){
        return CertI18n.message(mMessageId);
    }
    
}
