/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.4, Date: 19-Sep-2017.
 */
package tr.gov.tubitak.uekae.esya.asn.passport;

import com.objsys.asn1j.runtime.*;

public class CscaMasterList extends Asn1Type {
   private static final long serialVersionUID = 55;
   static {
      setKey (_CscaMasterListRtkey._rtkey);
   }

   public CscaMasterListVersion version;
   public _SetOfCertificate certList;

   public CscaMasterList () {
      super();
      init();
   }

   /**
    * This constructor sets all elements to references to the 
    * given objects
    */
   public CscaMasterList (
      CscaMasterListVersion version_,
      _SetOfCertificate certList_
   ) {
      super();
      version = version_;
      certList = certList_;
   }

   /**
    * This constructor allows primitive data to be passed for all 
    * primitive elements.  It will create new object wrappers for 
    * the primitive data and set other elements to references to 
    * the given objects 
    */
   public CscaMasterList (long version_,
      _SetOfCertificate certList_
   ) {
      super();
      version = new CscaMasterListVersion (version_);
      certList = certList_;
   }

   public void init () {
      version = null;
      certList = null;
   }

   public void decode
      (Asn1BerDecodeBuffer buffer, boolean explicit, int implicitLength)
      throws Asn1Exception, java.io.IOException
   {
      int llen = (explicit) ?
         matchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

      init ();

      // decode SEQUENCE

      Asn1BerDecodeContext _context =
         new Asn1BerDecodeContext (buffer, llen);

      IntHolder elemLen = new IntHolder();

      // decode version

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.PRIM, 2, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("version", -1);

         version = new CscaMasterListVersion();
         version.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("version", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "version");

      // decode certList

      if (_context.matchElemTag (Asn1Tag.UNIV, Asn1Tag.CONS, 17, elemLen, false)) {
         buffer.getContext().eventDispatcher.startElement("certList", -1);

         certList = new _SetOfCertificate();
         certList.decode (buffer, true, elemLen.value);

         buffer.getContext().eventDispatcher.endElement("certList", -1);
      }
      else throw new Asn1MissingRequiredException (buffer, "certList");

      if (!_context.expired()) {
         Asn1Tag _tag = buffer.peekTag ();
         if (_tag.equals (Asn1Tag.UNIV, Asn1Tag.PRIM, 2) ||
             _tag.equals (Asn1Tag.UNIV, Asn1Tag.CONS, 17))
            throw new Asn1SeqOrderException ();

      }
   }

   public int encode (Asn1BerEncodeBuffer buffer, boolean explicit)
      throws Asn1Exception
   {
      int _aal = 0, len;

      // encode certList

      if (certList != null) {
         buffer.getContext().eventDispatcher.startElement("certList", -1);

         len = certList.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("certList", -1);
      }
      else throw new Asn1MissingRequiredException ("certList");

      // encode version

      if (version != null) {
         buffer.getContext().eventDispatcher.startElement("version", -1);

         len = version.encode (buffer, true);
         _aal += len;

         buffer.getContext().eventDispatcher.endElement("version", -1);
      }
      else throw new Asn1MissingRequiredException ("version");

      if (explicit) {
         _aal += buffer.encodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
      }

      return (_aal);
   }

   public void print (java.io.PrintStream _out, String _varName, int _level)
   {
      indent (_out, _level);
      _out.println (_varName + " {");
      if (version != null) version.print (_out, "version", _level+1);
      if (certList != null) certList.print (_out, "certList", _level+1);
      indent (_out, _level);
      _out.println ("}");
   }
}
